# -*- coding: utf-8 -*-
"""
Ausfuehrliche Langtexte fuer die wichtigsten AI-Themen (mehrseitige Erklaerung).
Sprache: sehr einfaches Deutsch, IT-Begriffe im Original.
Aufbau je Thema: mehrere Abschnitte (h = Ueberschrift, p = Absaetze) + web = im Internet gefundene Texte.
Wird von build_curriculum.py ueber den Themen-Titel zugeordnet.
"""

def S(h, *paragraphs):
    return {"h": h, "p": list(paragraphs)}

AI_DEEP = {}

# ===========================================================================
AI_DEEP["Retrieval Augmented Generation"] = {
 "web": [
   ("Fraunhofer IESE: RAG - Chat mit eigenen Daten", "https://www.iese.fraunhofer.de/blog/retrieval-augmented-generation-rag/"),
   ("virtido: Was ist RAG? Kompletter Leitfaden 2026", "https://virtido.com/de/blog/was-ist-rag-retrieval-augmented-generation-leitfaden"),
   ("zweitag: Wie funktioniert RAG?", "https://www.zweitag.de/en/blog/wie-funktioniert-retrieval-augmented-generation-rag"),
   ("moin.ai: RAG einfach erklaert", "https://www.moin.ai/en/chatbot-wiki/retrieval-augmented-generation-rag"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Sprachmodell (LLM) wie ChatGPT hat sehr viel gelernt, aber es kennt weder eure internen Unterlagen noch die neuesten Preise, Konditionen oder Hausregeln eurer Bank. Wenn man es einfach fragt, rät es notfalls - und rät manchmal falsch (das nennt man Halluzination).",
    "Retrieval Augmented Generation (RAG) löst genau dieses Problem. Der Trick ist einfach: Bevor die KI antwortet, sucht das System zuerst in euren echten Dokumenten nach der passenden Stelle und legt sie der KI vor. Die KI formuliert dann die Antwort NUR aus diesem gefundenen Wissen. 'Augmented' heißt 'angereichert': Die Antwort der KI wird mit eurem eigenen Wissen angereichert.",
    "Ein Bild dazu: Stell dir einen sehr klugen neuen Mitarbeiter vor, der alles Allgemeine weiß, aber eure Bank noch nicht kennt. RAG ist so, als würdest du ihm vor jeder Kundenfrage schnell die richtige Seite aus dem Handbuch auf den Tisch legen. Er liest sie und antwortet daraus - statt aus dem Bauch."),
  S("Wie es funktioniert (Schritt für Schritt)",
    "1. Vorbereitung (einmalig): Alle eure Unterlagen - PDFs, Wikis, Handbücher, FAQ - werden eingesammelt und gereinigt. Dann werden sie in kleine Stücke geschnitten (Chunks), damit man später gezielt die richtige Stelle findet.",
    "2. Embeddings: Jedes Textstück wird in eine Zahlenreihe (Vektor) umgewandelt, die seine Bedeutung darstellt. Ähnliche Bedeutungen bekommen ähnliche Zahlen. Diese Zahlen werden in einer Vector Database gespeichert.",
    "3. Frage kommt rein: Stellt ein Kunde eine Frage, wird auch die Frage in so eine Zahlenreihe umgewandelt.",
    "4. Suche (Retrieval): Das System vergleicht die Frage-Zahlen mit allen gespeicherten Text-Zahlen und holt die am besten passenden Textstücke heraus - nach Bedeutung, nicht nach exakten Wörtern.",
    "5. Antwort (Generation): Die gefundenen Textstücke werden zusammen mit der Frage an das LLM gegeben, mit der Anweisung: 'Antworte nur aus diesem Wissen.' Das LLM formuliert daraus eine klare, natürliche Antwort - oft mit Quellenangabe."),
  S("Wie man es einsetzt (Praxis in der Bank)",
    "RAG ist die wichtigste Technik, um in einer Bank einen vertrauenswürdigen KI-Assistenten zu bauen, weil die Antworten auf echten, geprüften Dokumenten beruhen und man die Quelle anzeigen kann.",
    "Typische Wissensquellen sind laut Praxis-Berichten: interne Wikis, Produkt- und Konditionsblätter, Verträge, Richtlinien, Support-Artikel, Handbücher und Datenbanken. Genau dieselbe Idee steckt hinter der Genesys Knowledge Base, die ihr im Genesys-Teil dieses Plans lernt - Genesys nutzt RAG-ähnliche Technik im Hintergrund.",
    "Einsatzfelder in der Bank: ein Kundenservice-Bot, der Fragen zu Konto, Karte und Kredit aus den offiziellen Unterlagen beantwortet; ein Agent-Assist-System, das dem Mitarbeiter live den passenden Wissens-Artikel einblendet; ein internes Suchsystem, in dem Mitarbeiter Regelwerke in Sekunden durchsuchen."),
  S("Konkretes Beispiel",
    "Ein Kunde fragt den Bot: 'Was kostet eine Ersatzkarte?' Ohne RAG würde die KI vielleicht irgendeinen Betrag raten. Mit RAG sucht das System zuerst im aktuellen Preis- und Leistungsverzeichnis, findet den Abschnitt 'Kartenservice - Ersatzkarte: 10 Euro' und die KI antwortet: 'Eine Ersatzkarte kostet 10 Euro (Quelle: Preisverzeichnis, Stand Juli 2026).'",
    "Ändert die Bank morgen den Preis, muss man NICHT die KI neu trainieren - man aktualisiert einfach das Dokument. Beim nächsten Mal findet die Suche automatisch den neuen Wert. Das ist der große Vorteil gegenüber Fine-Tuning."),
  S("Vorteile",
    "Weniger Halluzinationen: Die KI antwortet aus echten Quellen statt aus dem Bauch.",
    "Immer aktuell: Neues Wissen = einfach neues Dokument einpflegen, kein teures Neutraining.",
    "Nachvollziehbar: Man kann die Quelle jeder Antwort anzeigen - wichtig für Vertrauen und Aufsicht.",
    "Datenschutzfreundlicher: Das eigene Wissen bleibt in eurem System; man muss es nicht in ein fremdes Modell 'einbrennen'."),
  S("Grenzen, Risiken & Datenschutz",
    "RAG ist nur so gut wie eure Dokumente. Sind sie veraltet, widersprüchlich oder schlecht geschrieben, gibt die KI auch schlechte Antworten ('garbage in, garbage out').",
    "Findet die Suche die falsche Stelle, antwortet die KI selbstbewusst falsch. Deshalb sind gutes Chunking und regelmäßige Prüfung (RAG Evaluation) wichtig.",
    "In der Bank gilt: Auch bei RAG dürfen keine sensiblen Kundendaten ungeschützt in externe Modelle fließen. Man klärt vorher, wo das LLM läuft (EU-Region oder On-Prem) und was gespeichert wird - siehe DSGVO und Private AI im AI-Teil dieses Plans."),
  S("Typische Fehler",
    "Chunks zu groß (die KI bekommt zu viel Beiwerk) oder zu klein (der Zusammenhang fehlt).",
    "Keine Quellenangabe - dann kann niemand die Antwort prüfen.",
    "Kein Plan für 'nichts gefunden': Der Bot sollte dann ehrlich sagen, dass er es nicht weiß, und an einen Menschen übergeben, statt zu raten.",
    "Wissen wird einmal eingepflegt und nie gepflegt - dann veraltet der Bot schleichend."),
  S("Best Practices / Checkliste",
    "Dokumente sauber, kurz und eindeutig halten (eine Frage - eine Antwort).",
    "Immer die Quelle mit anzeigen.",
    "Regelmäßig mit echten Testfragen prüfen, ob die Antworten stimmen (Evaluation).",
    "Feedback der Nutzer (Daumen hoch/runter) einsammeln und Wissenslücken schließen.",
    "Klaren Fallback bauen: Bei Unsicherheit nachfragen oder an einen Menschen übergeben."),
  S("So lernst du weiter",
    "Im AI-Teil dieses Plans gehören die Themen Embeddings, Vector Search, Chunking, RAG Architektur und RAG Evaluation direkt dazu - arbeite sie in dieser Reihenfolge durch.",
    "Die Fraunhofer- und virtido-Texte unten erklären RAG noch einmal ausführlich und mit Praxis-Beispielen. Zum Selbst-Ausprobieren eignen sich die GitHub-Bibliotheken LlamaIndex und LangChain."),
 ],
}

# ===========================================================================
AI_DEEP["Large Language Models"] = {
 "web": [
   ("Fraunhofer IESE: Wie funktionieren LLMs?", "https://www.iese.fraunhofer.de/blog/wie-funktionieren-llms/"),
   ("Fraunhofer IESE: Was sind LLMs - worauf achten?", "https://www.iese.fraunhofer.de/blog/large-language-models-ki-sprachmodelle/"),
   ("Haufe Akademie: LLM verstehen und anwenden", "https://www.haufe-akademie.de/skill-it/blog/large-language-models"),
   ("Alexander Thamm: LLM - eine Einfuehrung", "https://www.alexanderthamm.com/de/blog/large-language-models-eine-einfuehrung/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Large Language Model (LLM) ist ein sehr großes KI-Sprachmodell. Man kann es sich als eine extrem gute Autovervollständigung vorstellen: Es sagt immer voraus, welches Wort als Nächstes am wahrscheinlichsten kommt - und macht das so gut, dass ganze sinnvolle Texte, Antworten und sogar Programmcode entstehen.",
    "Bekannte LLMs sind GPT (ChatGPT), Claude, Gemini und Llama. Sie haben aus riesigen Textmengen (großen Teilen des Internets, Büchern usw.) gelernt, wie Sprache funktioniert. Wichtig: Ein LLM 'versteht' nicht wie ein Mensch - es rechnet Wahrscheinlichkeiten. Trotzdem sind die Ergebnisse oft verblüffend gut."),
  S("Wie es funktioniert (einfach)",
    "Technisch ist ein LLM ein Deep-Learning-Modell mit der sogenannten Transformer-Architektur (die lernst du in diesem Plan gleich danach). Es hat Milliarden von 'Stellschrauben' (Parameter/Gewichte), die beim Training eingestellt wurden.",
    "Beim Training liest das Modell Unmengen Text und übt, das jeweils nächste Wort vorherzusagen. Liegt es daneben, werden die Stellschrauben ein winziges Stück korrigiert - milliardenfach. So 'lernt' das Modell Grammatik, Fakten und Zusammenhänge.",
    "Text wird dabei in Tokens (Wort-Teile) zerlegt. Das Modell arbeitet mit Tokens, und nach diesen Tokens richten sich auch die Kosten: Je mehr Text rein- und rausgeht, desto teurer wird ein Aufruf."),
  S("Wie man es einsetzt (Praxis im Unternehmen)",
    "Laut den Praxis-Quellen sind die häufigsten Einsätze im Unternehmen: Kundenservice automatisieren (Chatbots), Texte erstellen und zusammenfassen, große Textmengen analysieren, Übersetzen sowie Programmier-Unterstützung.",
    "In einer Bank heißt das konkret: Anfragen vorsortieren und beantworten, Gesprächsnotizen automatisch zusammenfassen (siehe Genesys Conversation Summary), E-Mails und Beschwerden klassifizieren, Mitarbeitern beim Formulieren helfen, oder als Basis eines RAG-Systems mit eigenem Wissen dienen.",
    "Wichtig ist die Entscheidung, WELCHES Modell und WO es läuft: als fertiger Dienst über eine API (OpenAI, Anthropic Claude, Azure) oder selbst betrieben (Open-Source-LLM, On-Prem) für maximalen Datenschutz - beides behandelt der AI-Teil dieses Plans."),
  S("Konkretes Beispiel",
    "Ein Agent beendet ein 12-minütiges Kundengespräch. Statt selbst eine Notiz zu tippen, lässt er das LLM zusammenfassen: 'Kunde meldete verlorene Karte, Karte wurde gesperrt, Ersatzkarte bestellt, Lieferung in 5 Werktagen.' Der Agent prüft kurz, korrigiert bei Bedarf und speichert. Das spart pro Gespräch 1-2 Minuten Nacharbeit - bei tausenden Gesprächen viel Zeit."),
  S("Vorteile",
    "Sehr vielseitig: dasselbe Modell kann schreiben, zusammenfassen, sortieren, übersetzen.",
    "Spart Zeit bei Sprach- und Textaufgaben.",
    "Rund um die Uhr verfügbar und gut skalierbar.",
    "Über RAG und Tools mit eigenem Wissen und echten Systemen kombinierbar."),
  S("Grenzen, Risiken & Datenschutz",
    "Halluzinationen: Ein LLM kann Falsches sehr überzeugend behaupten. Wichtige Antworten müssen geprüft oder mit RAG auf Quellen gestützt werden.",
    "Kein aktuelles Wissen: Ohne RAG kennt es nur seinen Trainingsstand, nicht eure heutigen Preise.",
    "Datenschutz: Keine Kundendaten oder Geheimnisse in öffentliche Tools eingeben. In der Bank braucht es klare Regeln (welches Modell, welche Region, was wird gespeichert) - Stichworte DSGVO, EU AI Act, Private AI.",
    "Kosten & Sicherheit: Tokens kosten Geld, und LLMs sind für Angriffe wie Prompt Injection anfällig (siehe AI Security)."),
  S("Typische Fehler",
    "Dem LLM blind vertrauen, ohne Ergebnisse zu prüfen.",
    "Erwarten, dass es interne/aktuelle Fakten kennt (dafür braucht es RAG).",
    "Sensible Daten in öffentliche Tools kopieren.",
    "Das teuerste Modell für einfache Aufgaben nehmen, wo ein kleines (SLM) reichen würde."),
  S("Best Practices / Checkliste",
    "Für Fakten immer RAG (eigene Quellen) nutzen und Quellen anzeigen.",
    "Klare Prompts schreiben (siehe Prompt Engineering).",
    "Modell und Betriebsort nach Datenschutz und Kosten wählen.",
    "Ausgaben prüfen, besonders bei rechtlich/finanziell heiklen Themen.",
    "Kosten (Tokens) überwachen."),
  S("So lernst du weiter",
    "Als Nächstes im Plan: Transformer-Architektur und Attention (das Innenleben), dann Prompting und RAG (das Anwenden). Die Fraunhofer-Texte unten erklären das Innenleben Schritt für Schritt in einfachem Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Prompt Engineering"] = {
 "web": [
   ("Prompt Engineering Guide (deutsch)", "https://www.promptingguide.ai/de"),
   ("Google Cloud: Was ist Prompt Engineering?", "https://cloud.google.com/discover/what-is-prompt-engineering"),
   ("IBM: Guide to Prompt Engineering", "https://www.ibm.com/think/prompt-engineering"),
   ("Microsoft Learn: Prompt-Engineering-Techniken", "https://learn.microsoft.com/de-de/azure/foundry/openai/concepts/prompt-engineering"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Prompt ist die Anweisung, die du der KI gibst. Prompt Engineering ist die Kunst und das Handwerk, diese Anweisung so zu formulieren, dass die KI genau das liefert, was du brauchst. Kurz: Bessere Frage, bessere Antwort.",
    "Das Schöne daran: Man braucht dafür nicht programmieren zu können. Es ist reine Sprache. Aber es ist erlernbar und wiederholbar - deshalb 'Engineering'. Schon kleine Änderungen im Prompt können das Ergebnis stark verbessern."),
  S("Wie es funktioniert: die Bausteine eines guten Prompts",
    "Eine in der Praxis bewährte Struktur ist die RKAI-Formel: Rolle, Kontext, Aufgabe, Instruktionen.",
    "Rolle: Sag der KI, wer sie sein soll ('Du bist ein erfahrener, freundlicher Bankberater'). Je konkreter die Rolle, desto passender der Ton.",
    "Kontext: Gib die nötigen Hintergrund-Infos ('Der Kunde hat ein Girokonto und fragt nach Gebühren').",
    "Aufgabe: Sag klar, was zu tun ist ('Erkläre die Kontoführungsgebühr in 3 einfachen Sätzen').",
    "Instruktionen: Gib Format und Regeln vor ('Nutze einfache Sprache, keine Fachbegriffe, antworte auf Deutsch').",
    "Zwei weitere starke Techniken: Few-shot (gib 1-3 Beispiele für gute Antworten mit) und Chain-of-Thought ('Denke Schritt für Schritt', hilft bei kniffligen Aufgaben)."),
  S("Wie man es einsetzt (Praxis)",
    "Der empfohlene Weg (laut Google/IBM/Microsoft-Guides): Starte mit einer einfachen, klaren Anweisung und erweitere sie schrittweise - füge Kontext, Format-Vorgaben und Beispiele hinzu, bis das Ergebnis passt. Testen und Verbessern gehört dazu.",
    "In der Bank steckt Prompt Engineering überall: hinter den Antworten eines Bots, hinter Agent-Assist-Vorschlägen, hinter automatischen Zusammenfassungen. Wer die Prompts gut baut, bekommt zuverlässigere, sicherere und einheitlichere Ergebnisse.",
    "Weil Prompts im Echtbetrieb wichtig sind, versioniert man sie wie Code (Prompt Versioning) und testet Änderungen, bevor sie live gehen."),
  S("Konkretes Beispiel",
    "Schwacher Prompt: 'Schreib was zu Kontogebühren.' Ergebnis: vage, evtl. falscher Ton.",
    "Starker Prompt: 'Du bist ein freundlicher Bankberater (Rolle). Ein Privatkunde mit Girokonto fragt nach der monatlichen Kontoführungsgebühr (Kontext). Erkläre die Gebühr und wie man sie sparen kann (Aufgabe). Nutze sehr einfache Sprache, maximal 4 Sätze, keine Fachbegriffe, freundlicher Ton (Instruktionen).' Ergebnis: klar, freundlich, verwendbar."),
  S("Vorteile",
    "Sofort bessere Ergebnisse - ohne Programmieren.",
    "Günstig: Man verbessert die KI durch bessere Sprache statt durch teures Training.",
    "Wiederholbar: Ein guter Prompt liefert dauerhaft gute Antworten.",
    "Steuerbar: Ton, Länge und Sicherheit lassen sich vorgeben."),
  S("Grenzen, Risiken & Datenschutz",
    "Prompting ersetzt kein echtes Wissen: Für aktuelle Fakten braucht es RAG, sonst rät die KI.",
    "Sicherheit: Angreifer versuchen per Prompt Injection, deine Anweisungen zu überschreiben. Man muss Nutzereingaben von den festen Anweisungen trennen (siehe AI Security).",
    "Keine sensiblen Daten in Beispiel-Prompts öffentlicher Tools schreiben."),
  S("Typische Fehler",
    "Zu vage ('mach was Gutes') statt konkret.",
    "Keine Rolle, kein Format, keine Länge vorgegeben.",
    "Alles in einen riesigen Prompt packen, statt klar zu gliedern.",
    "Nicht testen: Der erste Prompt ist selten der beste - iterieren!"),
  S("Best Practices / Checkliste",
    "Rolle, Kontext, Aufgabe, Instruktionen angeben (RKAI).",
    "Format und Länge klar vorgeben.",
    "Bei kniffligen Aufgaben: Beispiele geben (Few-shot) oder 'Schritt für Schritt' denken lassen.",
    "Iterieren: testen, anpassen, erneut testen.",
    "Wichtige Prompts versionieren und vor Live-Gang prüfen."),
  S("So lernst du weiter",
    "Der deutschsprachige Prompt Engineering Guide unten ist eine hervorragende, kostenlose Lernquelle mit vielen Techniken und Beispielen. Danach im Plan: Context Engineering und Advanced Prompting."),
 ],
}

# ===========================================================================
AI_DEEP["Was ist Machine Learning?"] = {
 "web": [
   ("Alexander Thamm: Machine Learning kompakt erklaert", "https://www.alexanderthamm.com/de/blog/machine-learning/"),
   ("Der Bank Blog: Machine Learning im Banking", "https://www.der-bank-blog.de/machine-learning/technologie/37652231/"),
   ("Geldinstitute: Vorteile von ML fuer Banken", "https://www.geldinstitute.de/it-itk/2021/die-vorteile-von-machine-learning-fuer-banken.html"),
   ("Daten verstehen: Machine Learning einfach erklaert", "https://datenverstehen.de/machine-learning-einfach-erklaert/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Machine Learning (ML), auf Deutsch maschinelles Lernen, ist ein Teilbereich der Künstlichen Intelligenz. Die Idee: Ein Computer lernt Regeln selbst aus Daten, statt dass ein Mensch jede Regel vorgibt.",
    "Klassisch würde man einem Computer sagen: 'Wenn Betrag über 10000 UND Ausland, dann verdächtig.' Das ist mühsam und lückenhaft. ML dreht es um: Man zeigt dem Computer tausende alte Fälle mit der Info 'war Betrug / war kein Betrug', und er findet die Muster selbst - auch solche, die kein Mensch als Regel formuliert hätte."),
  S("Die drei Grundarten",
    "Supervised Learning (überwacht): Lernen mit Lösung. Jedes Beispiel hat die richtige Antwort (Label) dabei. Beispiel: alte Kreditfälle mit 'zurückgezahlt/ausgefallen'. Das ist die häufigste Art in Banken.",
    "Unsupervised Learning (unüberwacht): Lernen ohne Lösung. Das Modell findet selbst Gruppen in den Daten, z.B. Kundentypen. Gut, wenn man die Antwort noch nicht kennt.",
    "Reinforcement Learning: Lernen durch Belohnung und Bestrafung, wie beim Hunde-Training. Das Modell probiert Aktionen aus und lernt, welche sich lohnen."),
  S("Wie es funktioniert (Ablauf eines ML-Projekts)",
    "1. Daten sammeln und reinigen (Data Cleaning) - meist der größte Aufwand.",
    "2. Features und Label festlegen: Features sind die Eingaben (Betrag, Uhrzeit, Ort), das Label ist die gesuchte Antwort (Betrug ja/nein).",
    "3. Daten aufteilen in Trainings-, Validierungs- und Testdaten.",
    "4. Ein Modell trainieren (z.B. Decision Tree, Random Forest).",
    "5. Prüfen mit den Testdaten - ehrlich, mit Metriken wie Precision und Recall.",
    "6. In Betrieb nehmen und überwachen (MLOps), denn die Welt ändert sich (Model Drift)."),
  S("Wie man es einsetzt (Praxis in der Bank)",
    "Laut den Fachquellen ist ML im Banking längst Alltag. Die wichtigsten Einsätze:",
    "Kreditwürdigkeitsprüfung (Credit Scoring): Aus historischen Daten schätzt ein Modell die Ausfallwahrscheinlichkeit. Achtung: Das ist laut EU AI Act ein Hochrisiko-Bereich und muss streng geprüft und erklärbar sein - die Letztentscheidung bleibt beim Menschen.",
    "Betrugserkennung: Modelle erkennen verdächtige Muster in Echtzeit und schlagen Alarm.",
    "Kundenservice und Robo-Advisory: Empfehlungen im Portfoliomanagement, Vorsortieren von Anfragen.",
    "Prozessautomatisierung: Routineaufgaben werden übernommen, Mitarbeiter für Komplexes frei."),
  S("Konkretes Beispiel",
    "Betrugserkennung: Man füttert ein Modell mit Millionen alten Transaktionen, jeweils markiert als 'Betrug' oder 'kein Betrug'. Das Modell lernt die Muster. Kommt eine neue Zahlung um 3 Uhr nachts, aus dem Ausland, über einen ungewöhnlich hohen Betrag, meldet es: 'zu 92 % verdächtig'. Ein Mitarbeiter prüft und entscheidet."),
  S("Vorteile",
    "Erkennt Muster in riesigen Datenmengen, die Menschen entgehen.",
    "Rund um die Uhr, schnell und in gleichbleibender Qualität.",
    "Senkt Kosten durch Automatisierung von Routine.",
    "Verbessert Risiko-Einschätzung und Betrugsabwehr."),
  S("Grenzen, Risiken & Datenschutz",
    "Ein Modell ist nur so gut wie seine Daten. Verzerrte Daten führen zu unfairen Entscheidungen (Bias) - in der Bank besonders heikel bei Kredit.",
    "Erklärbarkeit: Aufsicht und Kunden dürfen eine nachvollziehbare Begründung erwarten (siehe Explainability, EU AI Act).",
    "Datenschutz: Personenbezogene Daten nur mit Rechtsgrundlage, sparsam und geschützt (DSGVO).",
    "Model Drift: Modelle veralten, wenn sich die Welt ändert - deshalb überwachen und nachtrainieren."),
  S("Typische Fehler",
    "Mit denselben Daten prüfen, mit denen trainiert wurde (dann kennt das Modell die Antworten - Testdaten sind heilig).",
    "Nur auf Accuracy schauen - bei seltenen Fällen wie Betrug täuscht das (nutze Precision/Recall).",
    "Bias in den Daten übersehen.",
    "Das Modell nach dem Start nie wieder pflegen."),
  S("Best Practices / Checkliste",
    "Erst die Daten in Ordnung bringen, dann das Modell.",
    "Sauber in Trainings-/Test-Daten trennen.",
    "Passende Metriken wählen (bei seltenen Ereignissen Precision/Recall/F1).",
    "Auf Bias und Erklärbarkeit achten - besonders bei Kredit.",
    "Im Betrieb überwachen (MLOps) und regelmäßig nachtrainieren."),
  S("So lernst du weiter",
    "Im Plan folgen die Details: Features & Labels, Overfitting, Cross-Validation, Metriken - und danach Deep Learning. Die Bank-Blog- und Geldinstitute-Texte unten zeigen viele echte Banking-Anwendungen."),
 ],
}

# ===========================================================================
AI_DEEP["Transformer Architektur"] = {
 "web": [
   ("Der Transformer illustriert (deutsch, nach Jay Alammar)", "https://www.michaelkipp.de/deeplearning/Transformer-illustriert.html"),
   ("Wikipedia (DE): Transformer (Maschinelles Lernen)", "https://de.wikipedia.org/wiki/Transformer_(Maschinelles_Lernen)"),
   ("liora.io: Das Transformer Neural Network", "https://liora.io/de/das-transformer-neural-network-eine-revolution-im-nlp-bereich"),
   ("heise: Implementierung eines Transformers", "https://www.heise.de/blog/Kuenstliche-Neuronale-Netze-im-Ueberblick-11-Implementierung-eines-Transformers-10700202.html"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Der Transformer ist die Bauweise (Architektur) hinter allen modernen großen Sprachmodellen - GPT, Claude, Gemini. Ohne den Transformer gäbe es kein ChatGPT. Er wurde 2017 in dem berühmten Aufsatz 'Attention Is All You Need' vorgestellt.",
    "Seine Superkraft: Er kann einen ganzen Satz oder Text auf einmal betrachten und selbst herausfinden, welche Wörter zusammengehören - egal wie weit sie auseinanderstehen. Ältere Modelle lasen Text mühsam Wort für Wort; der Transformer schaut aufs Ganze."),
  S("Wie es funktioniert (einfach)",
    "Kernstück ist der Attention-Mechanismus ('Aufmerksamkeit'). Für jedes Wort entscheidet das Modell: Auf welche anderen Wörter muss ich achten, um dieses Wort richtig zu verstehen?",
    "Beispiel: Im Satz 'Die Bank am Fluss' erkennt der Transformer aus dem Wort 'Fluss', dass mit 'Bank' das Ufer gemeint ist, nicht das Geldinstitut. Attention verbindet 'Bank' mit 'Fluss'.",
    "Ein weiterer Vorteil, den die Fachquellen betonen: Weil der Transformer nicht Wort für Wort vorgehen muss, kann er viele Teile parallel verarbeiten. Das macht das Training auf GPUs sehr schnell - und erst dadurch wurden so große Modelle möglich.",
    "Grob besteht ein Transformer aus Encoder- und/oder Decoder-Blöcken mit Self-Attention und einfachen Rechenschichten (Feedforward). Für ein erstes Verständnis reicht: Attention findet die Zusammenhänge, viele Schichten verfeinern das Verständnis."),
  S("Wie man es einsetzt (Praxis)",
    "Als normaler Anwender oder Bot-Bauer baust du keinen Transformer selbst - du nutzt fertige, vortrainierte Transformer-Modelle über eine API (Claude, GPT) oder als Open-Source-Modell (über die Bibliothek Hugging Face Transformers).",
    "Wichtig ist zu verstehen, WARUM diese Modelle so gut sind: Dadurch triffst du bessere Entscheidungen - etwa dass ein LLM Zusammenhänge im Text erfasst, aber trotzdem für aktuelle Fakten RAG braucht.",
    "Transformer stecken heute nicht nur in Text, sondern auch in Übersetzung, Sprache-zu-Text und multimodalen Modellen (Bild + Text)."),
  S("Konkretes Beispiel",
    "Übersetzung: Frühere Systeme übersetzten oft Wort für Wort und verloren den Sinn. Ein Transformer betrachtet den ganzen Satz, erkennt Bezüge (wer tut was) und liefert eine flüssige, sinnvolle Übersetzung. Genau dieselbe Fähigkeit macht ihn auch beim Verstehen von Kundenanfragen stark."),
  S("Vorteile",
    "Erfasst Zusammenhänge über lange Texte hinweg.",
    "Sehr gut parallelisierbar - dadurch schnelles Training und große Modelle.",
    "Universell: gleiche Grundidee für Text, Sprache, Bilder.",
    "Basis praktisch aller heutigen Spitzen-KI."),
  S("Grenzen & Einordnung",
    "Große Transformer brauchen sehr viel Rechenleistung (GPUs) und Energie - deshalb sind Training und Betrieb teuer (siehe GPU-Grundlagen, Green AI).",
    "Ein Transformer 'versteht' nicht wie ein Mensch; er erkennt statistische Muster. Halluzinationen bleiben möglich.",
    "Für den Einsatz zählt weniger, den Transformer im Detail zu bauen, als zu wissen, wie man die fertigen Modelle gut und sicher nutzt."),
  S("So lernst du weiter",
    "Direkt davor im Plan: neuronale Netze, Gewichte, Attention. Direkt danach: Pretraining vs Fine-Tuning und die Anwendung (LLM, Prompting, RAG). Der bebilderte deutsche Text 'Der Transformer illustriert' unten ist der beste Einstieg zum Nachschauen."),
 ],
}

# ===========================================================================
AI_DEEP["Agentic AI"] = {
 "web": [
   ("Fraunhofer IESE: Agentic AI & Multi-Agenten-Systeme", "https://www.iese.fraunhofer.de/blog/agentic-ai-multi-agenten-systeme/"),
   ("IHK Regensburg: KI-Agenten & Nutzen fuer Unternehmen", "https://www.ihk.de/regensburg/fachthemen/digitalisierung/kuenstliche-intelligenz/ki-agenten-und-ihr-nutzen-fuer-unternehmen-6706606"),
   ("BDO: Vom Assistenten zum Akteur - KI-Agenten", "https://www.bdo.de/de-de/insights/aktuelles/advisory-service/vom-assistenten-zum-akteur-wie-ki-agenten-unternehmen-in-die-aera-der-agentic-ai-fuehren"),
   ("IBM: What is Agentic AI?", "https://www.ibm.com/think/topics/agentic-ai"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Es gibt einen berühmten Merksatz: 'Ein Chatbot antwortet - ein Agent handelt.' Agentic AI beschreibt KI-Systeme, die nicht nur auf Fragen reagieren, sondern ein Ziel verfolgen: Sie planen selbst die nötigen Schritte, nutzen Werkzeuge, prüfen ihr Ergebnis und korrigieren sich.",
    "Ein KI-Agent verbindet dazu ein Sprachmodell (das 'Gehirn') mit Werkzeugen (Tools, z.B. eine Kunden-API), einem Gedächtnis (Memory) und einem Ziel. So wird aus einem reinen Textgenerator ein digitaler 'Mitarbeiter', der Aufgaben erledigt."),
  S("Wie es funktioniert (der Denk-Handel-Kreislauf)",
    "Ein Agent arbeitet in einer Schleife (Loop): 1. Denken - was ist mein Ziel, was der nächste Schritt? 2. Handeln - ein Werkzeug benutzen (z.B. Kundendaten holen, einen Termin buchen). 3. Beobachten - was kam heraus? 4. Erneut denken - bin ich fertig oder brauche ich einen weiteren Schritt?",
    "Diese Schleife wiederholt sich, bis das Ziel erreicht ist. Damit sie nicht endlos läuft oder Unsinn macht, setzt man Grenzen: ein Schritt-Limit (Loop Engineering) und feste Regeln (Guardrails).",
    "Man unterscheidet Single-Agent-Systeme (ein Agent macht alles) und Multi-Agent-Systeme (mehrere Agenten mit Rollen arbeiten zusammen, wie ein Team) - Letzteres beschreibt Fraunhofer als das Modell für komplexere Aufgaben."),
  S("Wie man es einsetzt (Praxis im Unternehmen)",
    "Laut den Fachquellen (IHK, BDO, IBM) automatisieren Agenten heute ganze Routineabläufe: Kundenauskünfte, Berichtserstellung, Dokumentenbearbeitung. Sie greifen auf Wissensdatenbanken zu und lösen bis zu 80 % der Standardtickets eigenständig.",
    "In der Bank denkbar: Ein Agent nimmt eine Beschwerde auf, sucht die Kundenhistorie, prüft die Regeln, bereitet eine Lösung vor und legt sie einem Mitarbeiter zur Freigabe vor. Oder: ein Agent, der bei einem Kartenverlust eigenständig sperrt, Ersatz bestellt und den Kunden informiert - kritische Schritte immer mit menschlicher Freigabe.",
    "Wichtig ist die Kontrolle: Human-in-the-loop (Mensch bestätigt kritische Schritte) oder Human-on-the-loop (Mensch überwacht und kann eingreifen). Gerade in Banken ist das Pflicht."),
  S("Konkretes Beispiel",
    "Ein Kunde schreibt: 'Ich habe eine Abbuchung, die ich nicht kenne.' Ein Agent könnte: die Transaktion heraussuchen, prüfen, ob sie als verdächtig markiert ist, dem Kunden Details zeigen, eine vorläufige Kartensperre vorbereiten und einen Reklamationsvorgang anlegen - und dann einen Menschen fragen: 'Sperre bestätigen?' So erledigt der Agent die Fleißarbeit, der Mensch entscheidet das Heikle."),
  S("Vorteile",
    "Erledigt mehrstufige Aufgaben selbstständig, nicht nur einzelne Antworten.",
    "Automatisiert Routine über mehrere Systeme hinweg.",
    "Rund um die Uhr, entlastet Mitarbeiter für Komplexes.",
    "Gartner erwartet, dass bis 2028 ein Drittel der Unternehmenssoftware Agentic AI enthält - der Trend ist groß."),
  S("Grenzen, Risiken & Datenschutz",
    "Nicht alles ist heute zuverlässig: Agenten können Fehler machen, sich verrennen oder in Schleifen hängen. Ehrliche Einordnung: 'Beyond the Hype' - klein und kontrolliert starten.",
    "Excessive Agency: Ein Agent mit zu vielen Rechten kann bei einem Fehler großen Schaden anrichten. Nur nötige Werkzeuge freigeben (Least Privilege).",
    "Sicherheit: Agenten sind angreifbar (Prompt Injection). Und alle Aktionen sollten protokolliert werden (Audit Logging).",
    "In der Bank: kritische Aktionen immer mit menschlicher Freigabe und klaren Guardrails."),
  S("Typische Fehler",
    "Einem Agenten zu früh zu viel Verantwortung/Rechte geben.",
    "Keine Grenzen (Schritt-Limit, Guardrails) setzen.",
    "Keine Nachvollziehbarkeit (kein Tracing/Logging) - dann versteht niemand, was schiefging.",
    "Ohne Pilot direkt groß ausrollen."),
  S("Best Practices / Checkliste",
    "Klein anfangen: eine klar begrenzte Aufgabe, viel Kontrolle.",
    "Human-in-the-loop für kritische Schritte.",
    "Nur nötige Tools freigeben, Guardrails setzen.",
    "Jeden Schritt aufzeichnen (Observability/Tracing) und auswerten.",
    "Erfolg messen (Evaluation), dann vorsichtig ausweiten."),
  S("So lernst du weiter",
    "Im Plan gehören dazu: KI-Agenten-Grundlagen, Single-/Multi-Agent, Agent Memory/Planning/Tools, Guardrails, Human-in-the-loop und AgentOps. Die Fraunhofer- und IHK-Texte unten sind ein guter, seriöser Einstieg auf Deutsch."),
 ],
}
