# -*- coding: utf-8 -*-
"""
Ausfuehrliche Langtexte fuer die wichtigsten AI-Themen (mehrseitige Erklaerung).
Sprache: sehr einfaches Deutsch, IT-Begriffe im Original.
Aufbau je Thema: mehrere Abschnitte (h = Ueberschrift, p = Absaetze) + web = im Internet gefundene Texte.
Wird von build_curriculum.py ueber den Themen-Titel zugeordnet.
"""

def S(h, *paragraphs):
    return {"h": h, "p": list(paragraphs)}

AI_DEEP = {}

# ===========================================================================
AI_DEEP["Retrieval Augmented Generation"] = {
 "web": [
   ("Fraunhofer IESE: RAG - Chat mit eigenen Daten", "https://www.iese.fraunhofer.de/blog/retrieval-augmented-generation-rag/"),
   ("virtido: Was ist RAG? Kompletter Leitfaden 2026", "https://virtido.com/de/blog/was-ist-rag-retrieval-augmented-generation-leitfaden"),
   ("zweitag: Wie funktioniert RAG?", "https://www.zweitag.de/en/blog/wie-funktioniert-retrieval-augmented-generation-rag"),
   ("moin.ai: RAG einfach erklaert", "https://www.moin.ai/en/chatbot-wiki/retrieval-augmented-generation-rag"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Sprachmodell (LLM) wie ChatGPT hat sehr viel gelernt, aber es kennt weder eure internen Unterlagen noch die neuesten Preise, Konditionen oder Hausregeln eurer Bank. Wenn man es einfach fragt, rät es notfalls - und rät manchmal falsch (das nennt man Halluzination).",
    "Retrieval Augmented Generation (RAG) löst genau dieses Problem. Der Trick ist einfach: Bevor die KI antwortet, sucht das System zuerst in euren echten Dokumenten nach der passenden Stelle und legt sie der KI vor. Die KI formuliert dann die Antwort NUR aus diesem gefundenen Wissen. 'Augmented' heißt 'angereichert': Die Antwort der KI wird mit eurem eigenen Wissen angereichert.",
    "Ein Bild dazu: Stell dir einen sehr klugen neuen Mitarbeiter vor, der alles Allgemeine weiß, aber eure Bank noch nicht kennt. RAG ist so, als würdest du ihm vor jeder Kundenfrage schnell die richtige Seite aus dem Handbuch auf den Tisch legen. Er liest sie und antwortet daraus - statt aus dem Bauch."),
  S("Wie es funktioniert (Schritt für Schritt)",
    "1. Vorbereitung (einmalig): Alle eure Unterlagen - PDFs, Wikis, Handbücher, FAQ - werden eingesammelt und gereinigt. Dann werden sie in kleine Stücke geschnitten (Chunks), damit man später gezielt die richtige Stelle findet.",
    "2. Embeddings: Jedes Textstück wird in eine Zahlenreihe (Vektor) umgewandelt, die seine Bedeutung darstellt. Ähnliche Bedeutungen bekommen ähnliche Zahlen. Diese Zahlen werden in einer Vector Database gespeichert.",
    "3. Frage kommt rein: Stellt ein Kunde eine Frage, wird auch die Frage in so eine Zahlenreihe umgewandelt.",
    "4. Suche (Retrieval): Das System vergleicht die Frage-Zahlen mit allen gespeicherten Text-Zahlen und holt die am besten passenden Textstücke heraus - nach Bedeutung, nicht nach exakten Wörtern.",
    "5. Antwort (Generation): Die gefundenen Textstücke werden zusammen mit der Frage an das LLM gegeben, mit der Anweisung: 'Antworte nur aus diesem Wissen.' Das LLM formuliert daraus eine klare, natürliche Antwort - oft mit Quellenangabe."),
  S("Wie man es einsetzt (Praxis in der Bank)",
    "RAG ist die wichtigste Technik, um in einer Bank einen vertrauenswürdigen KI-Assistenten zu bauen, weil die Antworten auf echten, geprüften Dokumenten beruhen und man die Quelle anzeigen kann.",
    "Typische Wissensquellen sind laut Praxis-Berichten: interne Wikis, Produkt- und Konditionsblätter, Verträge, Richtlinien, Support-Artikel, Handbücher und Datenbanken. Genau dieselbe Idee steckt hinter der Genesys Knowledge Base, die ihr im Genesys-Teil dieses Plans lernt - Genesys nutzt RAG-ähnliche Technik im Hintergrund.",
    "Einsatzfelder in der Bank: ein Kundenservice-Bot, der Fragen zu Konto, Karte und Kredit aus den offiziellen Unterlagen beantwortet; ein Agent-Assist-System, das dem Mitarbeiter live den passenden Wissens-Artikel einblendet; ein internes Suchsystem, in dem Mitarbeiter Regelwerke in Sekunden durchsuchen."),
  S("Konkretes Beispiel",
    "Ein Kunde fragt den Bot: 'Was kostet eine Ersatzkarte?' Ohne RAG würde die KI vielleicht irgendeinen Betrag raten. Mit RAG sucht das System zuerst im aktuellen Preis- und Leistungsverzeichnis, findet den Abschnitt 'Kartenservice - Ersatzkarte: 10 Euro' und die KI antwortet: 'Eine Ersatzkarte kostet 10 Euro (Quelle: Preisverzeichnis, Stand Juli 2026).'",
    "Ändert die Bank morgen den Preis, muss man NICHT die KI neu trainieren - man aktualisiert einfach das Dokument. Beim nächsten Mal findet die Suche automatisch den neuen Wert. Das ist der große Vorteil gegenüber Fine-Tuning."),
  S("Vorteile",
    "Weniger Halluzinationen: Die KI antwortet aus echten Quellen statt aus dem Bauch.",
    "Immer aktuell: Neues Wissen = einfach neues Dokument einpflegen, kein teures Neutraining.",
    "Nachvollziehbar: Man kann die Quelle jeder Antwort anzeigen - wichtig für Vertrauen und Aufsicht.",
    "Datenschutzfreundlicher: Das eigene Wissen bleibt in eurem System; man muss es nicht in ein fremdes Modell 'einbrennen'."),
  S("Grenzen, Risiken & Datenschutz",
    "RAG ist nur so gut wie eure Dokumente. Sind sie veraltet, widersprüchlich oder schlecht geschrieben, gibt die KI auch schlechte Antworten ('garbage in, garbage out').",
    "Findet die Suche die falsche Stelle, antwortet die KI selbstbewusst falsch. Deshalb sind gutes Chunking und regelmäßige Prüfung (RAG Evaluation) wichtig.",
    "In der Bank gilt: Auch bei RAG dürfen keine sensiblen Kundendaten ungeschützt in externe Modelle fließen. Man klärt vorher, wo das LLM läuft (EU-Region oder On-Prem) und was gespeichert wird - siehe DSGVO und Private AI im AI-Teil dieses Plans."),
  S("Typische Fehler",
    "Chunks zu groß (die KI bekommt zu viel Beiwerk) oder zu klein (der Zusammenhang fehlt).",
    "Keine Quellenangabe - dann kann niemand die Antwort prüfen.",
    "Kein Plan für 'nichts gefunden': Der Bot sollte dann ehrlich sagen, dass er es nicht weiß, und an einen Menschen übergeben, statt zu raten.",
    "Wissen wird einmal eingepflegt und nie gepflegt - dann veraltet der Bot schleichend."),
  S("Best Practices / Checkliste",
    "Dokumente sauber, kurz und eindeutig halten (eine Frage - eine Antwort).",
    "Immer die Quelle mit anzeigen.",
    "Regelmäßig mit echten Testfragen prüfen, ob die Antworten stimmen (Evaluation).",
    "Feedback der Nutzer (Daumen hoch/runter) einsammeln und Wissenslücken schließen.",
    "Klaren Fallback bauen: Bei Unsicherheit nachfragen oder an einen Menschen übergeben."),
  S("So lernst du weiter",
    "Im AI-Teil dieses Plans gehören die Themen Embeddings, Vector Search, Chunking, RAG Architektur und RAG Evaluation direkt dazu - arbeite sie in dieser Reihenfolge durch.",
    "Die Fraunhofer- und virtido-Texte unten erklären RAG noch einmal ausführlich und mit Praxis-Beispielen. Zum Selbst-Ausprobieren eignen sich die GitHub-Bibliotheken LlamaIndex und LangChain."),
 ],
}

# ===========================================================================
AI_DEEP["Large Language Models"] = {
 "web": [
   ("Fraunhofer IESE: Wie funktionieren LLMs?", "https://www.iese.fraunhofer.de/blog/wie-funktionieren-llms/"),
   ("Fraunhofer IESE: Was sind LLMs - worauf achten?", "https://www.iese.fraunhofer.de/blog/large-language-models-ki-sprachmodelle/"),
   ("Haufe Akademie: LLM verstehen und anwenden", "https://www.haufe-akademie.de/skill-it/blog/large-language-models"),
   ("Alexander Thamm: LLM - eine Einfuehrung", "https://www.alexanderthamm.com/de/blog/large-language-models-eine-einfuehrung/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Large Language Model (LLM) ist ein sehr großes KI-Sprachmodell. Man kann es sich als eine extrem gute Autovervollständigung vorstellen: Es sagt immer voraus, welches Wort als Nächstes am wahrscheinlichsten kommt - und macht das so gut, dass ganze sinnvolle Texte, Antworten und sogar Programmcode entstehen.",
    "Bekannte LLMs sind GPT (ChatGPT), Claude, Gemini und Llama. Sie haben aus riesigen Textmengen (großen Teilen des Internets, Büchern usw.) gelernt, wie Sprache funktioniert. Wichtig: Ein LLM 'versteht' nicht wie ein Mensch - es rechnet Wahrscheinlichkeiten. Trotzdem sind die Ergebnisse oft verblüffend gut."),
  S("Wie es funktioniert (einfach)",
    "Technisch ist ein LLM ein Deep-Learning-Modell mit der sogenannten Transformer-Architektur (die lernst du in diesem Plan gleich danach). Es hat Milliarden von 'Stellschrauben' (Parameter/Gewichte), die beim Training eingestellt wurden.",
    "Beim Training liest das Modell Unmengen Text und übt, das jeweils nächste Wort vorherzusagen. Liegt es daneben, werden die Stellschrauben ein winziges Stück korrigiert - milliardenfach. So 'lernt' das Modell Grammatik, Fakten und Zusammenhänge.",
    "Text wird dabei in Tokens (Wort-Teile) zerlegt. Das Modell arbeitet mit Tokens, und nach diesen Tokens richten sich auch die Kosten: Je mehr Text rein- und rausgeht, desto teurer wird ein Aufruf."),
  S("Wie man es einsetzt (Praxis im Unternehmen)",
    "Laut den Praxis-Quellen sind die häufigsten Einsätze im Unternehmen: Kundenservice automatisieren (Chatbots), Texte erstellen und zusammenfassen, große Textmengen analysieren, Übersetzen sowie Programmier-Unterstützung.",
    "In einer Bank heißt das konkret: Anfragen vorsortieren und beantworten, Gesprächsnotizen automatisch zusammenfassen (siehe Genesys Conversation Summary), E-Mails und Beschwerden klassifizieren, Mitarbeitern beim Formulieren helfen, oder als Basis eines RAG-Systems mit eigenem Wissen dienen.",
    "Wichtig ist die Entscheidung, WELCHES Modell und WO es läuft: als fertiger Dienst über eine API (OpenAI, Anthropic Claude, Azure) oder selbst betrieben (Open-Source-LLM, On-Prem) für maximalen Datenschutz - beides behandelt der AI-Teil dieses Plans."),
  S("Konkretes Beispiel",
    "Ein Agent beendet ein 12-minütiges Kundengespräch. Statt selbst eine Notiz zu tippen, lässt er das LLM zusammenfassen: 'Kunde meldete verlorene Karte, Karte wurde gesperrt, Ersatzkarte bestellt, Lieferung in 5 Werktagen.' Der Agent prüft kurz, korrigiert bei Bedarf und speichert. Das spart pro Gespräch 1-2 Minuten Nacharbeit - bei tausenden Gesprächen viel Zeit."),
  S("Vorteile",
    "Sehr vielseitig: dasselbe Modell kann schreiben, zusammenfassen, sortieren, übersetzen.",
    "Spart Zeit bei Sprach- und Textaufgaben.",
    "Rund um die Uhr verfügbar und gut skalierbar.",
    "Über RAG und Tools mit eigenem Wissen und echten Systemen kombinierbar."),
  S("Grenzen, Risiken & Datenschutz",
    "Halluzinationen: Ein LLM kann Falsches sehr überzeugend behaupten. Wichtige Antworten müssen geprüft oder mit RAG auf Quellen gestützt werden.",
    "Kein aktuelles Wissen: Ohne RAG kennt es nur seinen Trainingsstand, nicht eure heutigen Preise.",
    "Datenschutz: Keine Kundendaten oder Geheimnisse in öffentliche Tools eingeben. In der Bank braucht es klare Regeln (welches Modell, welche Region, was wird gespeichert) - Stichworte DSGVO, EU AI Act, Private AI.",
    "Kosten & Sicherheit: Tokens kosten Geld, und LLMs sind für Angriffe wie Prompt Injection anfällig (siehe AI Security)."),
  S("Typische Fehler",
    "Dem LLM blind vertrauen, ohne Ergebnisse zu prüfen.",
    "Erwarten, dass es interne/aktuelle Fakten kennt (dafür braucht es RAG).",
    "Sensible Daten in öffentliche Tools kopieren.",
    "Das teuerste Modell für einfache Aufgaben nehmen, wo ein kleines (SLM) reichen würde."),
  S("Best Practices / Checkliste",
    "Für Fakten immer RAG (eigene Quellen) nutzen und Quellen anzeigen.",
    "Klare Prompts schreiben (siehe Prompt Engineering).",
    "Modell und Betriebsort nach Datenschutz und Kosten wählen.",
    "Ausgaben prüfen, besonders bei rechtlich/finanziell heiklen Themen.",
    "Kosten (Tokens) überwachen."),
  S("So lernst du weiter",
    "Als Nächstes im Plan: Transformer-Architektur und Attention (das Innenleben), dann Prompting und RAG (das Anwenden). Die Fraunhofer-Texte unten erklären das Innenleben Schritt für Schritt in einfachem Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Prompt Engineering"] = {
 "web": [
   ("Prompt Engineering Guide (deutsch)", "https://www.promptingguide.ai/de"),
   ("Google Cloud: Was ist Prompt Engineering?", "https://cloud.google.com/discover/what-is-prompt-engineering"),
   ("IBM: Guide to Prompt Engineering", "https://www.ibm.com/think/prompt-engineering"),
   ("Microsoft Learn: Prompt-Engineering-Techniken", "https://learn.microsoft.com/de-de/azure/foundry/openai/concepts/prompt-engineering"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Prompt ist die Anweisung, die du der KI gibst. Prompt Engineering ist die Kunst und das Handwerk, diese Anweisung so zu formulieren, dass die KI genau das liefert, was du brauchst. Kurz: Bessere Frage, bessere Antwort.",
    "Das Schöne daran: Man braucht dafür nicht programmieren zu können. Es ist reine Sprache. Aber es ist erlernbar und wiederholbar - deshalb 'Engineering'. Schon kleine Änderungen im Prompt können das Ergebnis stark verbessern."),
  S("Wie es funktioniert: die Bausteine eines guten Prompts",
    "Eine in der Praxis bewährte Struktur ist die RKAI-Formel: Rolle, Kontext, Aufgabe, Instruktionen.",
    "Rolle: Sag der KI, wer sie sein soll ('Du bist ein erfahrener, freundlicher Bankberater'). Je konkreter die Rolle, desto passender der Ton.",
    "Kontext: Gib die nötigen Hintergrund-Infos ('Der Kunde hat ein Girokonto und fragt nach Gebühren').",
    "Aufgabe: Sag klar, was zu tun ist ('Erkläre die Kontoführungsgebühr in 3 einfachen Sätzen').",
    "Instruktionen: Gib Format und Regeln vor ('Nutze einfache Sprache, keine Fachbegriffe, antworte auf Deutsch').",
    "Zwei weitere starke Techniken: Few-shot (gib 1-3 Beispiele für gute Antworten mit) und Chain-of-Thought ('Denke Schritt für Schritt', hilft bei kniffligen Aufgaben)."),
  S("Wie man es einsetzt (Praxis)",
    "Der empfohlene Weg (laut Google/IBM/Microsoft-Guides): Starte mit einer einfachen, klaren Anweisung und erweitere sie schrittweise - füge Kontext, Format-Vorgaben und Beispiele hinzu, bis das Ergebnis passt. Testen und Verbessern gehört dazu.",
    "In der Bank steckt Prompt Engineering überall: hinter den Antworten eines Bots, hinter Agent-Assist-Vorschlägen, hinter automatischen Zusammenfassungen. Wer die Prompts gut baut, bekommt zuverlässigere, sicherere und einheitlichere Ergebnisse.",
    "Weil Prompts im Echtbetrieb wichtig sind, versioniert man sie wie Code (Prompt Versioning) und testet Änderungen, bevor sie live gehen."),
  S("Konkretes Beispiel",
    "Schwacher Prompt: 'Schreib was zu Kontogebühren.' Ergebnis: vage, evtl. falscher Ton.",
    "Starker Prompt: 'Du bist ein freundlicher Bankberater (Rolle). Ein Privatkunde mit Girokonto fragt nach der monatlichen Kontoführungsgebühr (Kontext). Erkläre die Gebühr und wie man sie sparen kann (Aufgabe). Nutze sehr einfache Sprache, maximal 4 Sätze, keine Fachbegriffe, freundlicher Ton (Instruktionen).' Ergebnis: klar, freundlich, verwendbar."),
  S("Vorteile",
    "Sofort bessere Ergebnisse - ohne Programmieren.",
    "Günstig: Man verbessert die KI durch bessere Sprache statt durch teures Training.",
    "Wiederholbar: Ein guter Prompt liefert dauerhaft gute Antworten.",
    "Steuerbar: Ton, Länge und Sicherheit lassen sich vorgeben."),
  S("Grenzen, Risiken & Datenschutz",
    "Prompting ersetzt kein echtes Wissen: Für aktuelle Fakten braucht es RAG, sonst rät die KI.",
    "Sicherheit: Angreifer versuchen per Prompt Injection, deine Anweisungen zu überschreiben. Man muss Nutzereingaben von den festen Anweisungen trennen (siehe AI Security).",
    "Keine sensiblen Daten in Beispiel-Prompts öffentlicher Tools schreiben."),
  S("Typische Fehler",
    "Zu vage ('mach was Gutes') statt konkret.",
    "Keine Rolle, kein Format, keine Länge vorgegeben.",
    "Alles in einen riesigen Prompt packen, statt klar zu gliedern.",
    "Nicht testen: Der erste Prompt ist selten der beste - iterieren!"),
  S("Best Practices / Checkliste",
    "Rolle, Kontext, Aufgabe, Instruktionen angeben (RKAI).",
    "Format und Länge klar vorgeben.",
    "Bei kniffligen Aufgaben: Beispiele geben (Few-shot) oder 'Schritt für Schritt' denken lassen.",
    "Iterieren: testen, anpassen, erneut testen.",
    "Wichtige Prompts versionieren und vor Live-Gang prüfen."),
  S("So lernst du weiter",
    "Der deutschsprachige Prompt Engineering Guide unten ist eine hervorragende, kostenlose Lernquelle mit vielen Techniken und Beispielen. Danach im Plan: Context Engineering und Advanced Prompting."),
 ],
}

# ===========================================================================
AI_DEEP["Was ist Machine Learning?"] = {
 "web": [
   ("Alexander Thamm: Machine Learning kompakt erklaert", "https://www.alexanderthamm.com/de/blog/machine-learning/"),
   ("Der Bank Blog: Machine Learning im Banking", "https://www.der-bank-blog.de/machine-learning/technologie/37652231/"),
   ("Geldinstitute: Vorteile von ML fuer Banken", "https://www.geldinstitute.de/it-itk/2021/die-vorteile-von-machine-learning-fuer-banken.html"),
   ("Daten verstehen: Machine Learning einfach erklaert", "https://datenverstehen.de/machine-learning-einfach-erklaert/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Machine Learning (ML), auf Deutsch maschinelles Lernen, ist ein Teilbereich der Künstlichen Intelligenz. Die Idee: Ein Computer lernt Regeln selbst aus Daten, statt dass ein Mensch jede Regel vorgibt.",
    "Klassisch würde man einem Computer sagen: 'Wenn Betrag über 10000 UND Ausland, dann verdächtig.' Das ist mühsam und lückenhaft. ML dreht es um: Man zeigt dem Computer tausende alte Fälle mit der Info 'war Betrug / war kein Betrug', und er findet die Muster selbst - auch solche, die kein Mensch als Regel formuliert hätte."),
  S("Die drei Grundarten",
    "Supervised Learning (überwacht): Lernen mit Lösung. Jedes Beispiel hat die richtige Antwort (Label) dabei. Beispiel: alte Kreditfälle mit 'zurückgezahlt/ausgefallen'. Das ist die häufigste Art in Banken.",
    "Unsupervised Learning (unüberwacht): Lernen ohne Lösung. Das Modell findet selbst Gruppen in den Daten, z.B. Kundentypen. Gut, wenn man die Antwort noch nicht kennt.",
    "Reinforcement Learning: Lernen durch Belohnung und Bestrafung, wie beim Hunde-Training. Das Modell probiert Aktionen aus und lernt, welche sich lohnen."),
  S("Wie es funktioniert (Ablauf eines ML-Projekts)",
    "1. Daten sammeln und reinigen (Data Cleaning) - meist der größte Aufwand.",
    "2. Features und Label festlegen: Features sind die Eingaben (Betrag, Uhrzeit, Ort), das Label ist die gesuchte Antwort (Betrug ja/nein).",
    "3. Daten aufteilen in Trainings-, Validierungs- und Testdaten.",
    "4. Ein Modell trainieren (z.B. Decision Tree, Random Forest).",
    "5. Prüfen mit den Testdaten - ehrlich, mit Metriken wie Precision und Recall.",
    "6. In Betrieb nehmen und überwachen (MLOps), denn die Welt ändert sich (Model Drift)."),
  S("Wie man es einsetzt (Praxis in der Bank)",
    "Laut den Fachquellen ist ML im Banking längst Alltag. Die wichtigsten Einsätze:",
    "Kreditwürdigkeitsprüfung (Credit Scoring): Aus historischen Daten schätzt ein Modell die Ausfallwahrscheinlichkeit. Achtung: Das ist laut EU AI Act ein Hochrisiko-Bereich und muss streng geprüft und erklärbar sein - die Letztentscheidung bleibt beim Menschen.",
    "Betrugserkennung: Modelle erkennen verdächtige Muster in Echtzeit und schlagen Alarm.",
    "Kundenservice und Robo-Advisory: Empfehlungen im Portfoliomanagement, Vorsortieren von Anfragen.",
    "Prozessautomatisierung: Routineaufgaben werden übernommen, Mitarbeiter für Komplexes frei."),
  S("Konkretes Beispiel",
    "Betrugserkennung: Man füttert ein Modell mit Millionen alten Transaktionen, jeweils markiert als 'Betrug' oder 'kein Betrug'. Das Modell lernt die Muster. Kommt eine neue Zahlung um 3 Uhr nachts, aus dem Ausland, über einen ungewöhnlich hohen Betrag, meldet es: 'zu 92 % verdächtig'. Ein Mitarbeiter prüft und entscheidet."),
  S("Vorteile",
    "Erkennt Muster in riesigen Datenmengen, die Menschen entgehen.",
    "Rund um die Uhr, schnell und in gleichbleibender Qualität.",
    "Senkt Kosten durch Automatisierung von Routine.",
    "Verbessert Risiko-Einschätzung und Betrugsabwehr."),
  S("Grenzen, Risiken & Datenschutz",
    "Ein Modell ist nur so gut wie seine Daten. Verzerrte Daten führen zu unfairen Entscheidungen (Bias) - in der Bank besonders heikel bei Kredit.",
    "Erklärbarkeit: Aufsicht und Kunden dürfen eine nachvollziehbare Begründung erwarten (siehe Explainability, EU AI Act).",
    "Datenschutz: Personenbezogene Daten nur mit Rechtsgrundlage, sparsam und geschützt (DSGVO).",
    "Model Drift: Modelle veralten, wenn sich die Welt ändert - deshalb überwachen und nachtrainieren."),
  S("Typische Fehler",
    "Mit denselben Daten prüfen, mit denen trainiert wurde (dann kennt das Modell die Antworten - Testdaten sind heilig).",
    "Nur auf Accuracy schauen - bei seltenen Fällen wie Betrug täuscht das (nutze Precision/Recall).",
    "Bias in den Daten übersehen.",
    "Das Modell nach dem Start nie wieder pflegen."),
  S("Best Practices / Checkliste",
    "Erst die Daten in Ordnung bringen, dann das Modell.",
    "Sauber in Trainings-/Test-Daten trennen.",
    "Passende Metriken wählen (bei seltenen Ereignissen Precision/Recall/F1).",
    "Auf Bias und Erklärbarkeit achten - besonders bei Kredit.",
    "Im Betrieb überwachen (MLOps) und regelmäßig nachtrainieren."),
  S("So lernst du weiter",
    "Im Plan folgen die Details: Features & Labels, Overfitting, Cross-Validation, Metriken - und danach Deep Learning. Die Bank-Blog- und Geldinstitute-Texte unten zeigen viele echte Banking-Anwendungen."),
 ],
}

# ===========================================================================
AI_DEEP["Transformer Architektur"] = {
 "web": [
   ("Der Transformer illustriert (deutsch, nach Jay Alammar)", "https://www.michaelkipp.de/deeplearning/Transformer-illustriert.html"),
   ("Wikipedia (DE): Transformer (Maschinelles Lernen)", "https://de.wikipedia.org/wiki/Transformer_(Maschinelles_Lernen)"),
   ("liora.io: Das Transformer Neural Network", "https://liora.io/de/das-transformer-neural-network-eine-revolution-im-nlp-bereich"),
   ("heise: Implementierung eines Transformers", "https://www.heise.de/blog/Kuenstliche-Neuronale-Netze-im-Ueberblick-11-Implementierung-eines-Transformers-10700202.html"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Der Transformer ist die Bauweise (Architektur) hinter allen modernen großen Sprachmodellen - GPT, Claude, Gemini. Ohne den Transformer gäbe es kein ChatGPT. Er wurde 2017 in dem berühmten Aufsatz 'Attention Is All You Need' vorgestellt.",
    "Seine Superkraft: Er kann einen ganzen Satz oder Text auf einmal betrachten und selbst herausfinden, welche Wörter zusammengehören - egal wie weit sie auseinanderstehen. Ältere Modelle lasen Text mühsam Wort für Wort; der Transformer schaut aufs Ganze."),
  S("Wie es funktioniert (einfach)",
    "Kernstück ist der Attention-Mechanismus ('Aufmerksamkeit'). Für jedes Wort entscheidet das Modell: Auf welche anderen Wörter muss ich achten, um dieses Wort richtig zu verstehen?",
    "Beispiel: Im Satz 'Die Bank am Fluss' erkennt der Transformer aus dem Wort 'Fluss', dass mit 'Bank' das Ufer gemeint ist, nicht das Geldinstitut. Attention verbindet 'Bank' mit 'Fluss'.",
    "Ein weiterer Vorteil, den die Fachquellen betonen: Weil der Transformer nicht Wort für Wort vorgehen muss, kann er viele Teile parallel verarbeiten. Das macht das Training auf GPUs sehr schnell - und erst dadurch wurden so große Modelle möglich.",
    "Grob besteht ein Transformer aus Encoder- und/oder Decoder-Blöcken mit Self-Attention und einfachen Rechenschichten (Feedforward). Für ein erstes Verständnis reicht: Attention findet die Zusammenhänge, viele Schichten verfeinern das Verständnis."),
  S("Wie man es einsetzt (Praxis)",
    "Als normaler Anwender oder Bot-Bauer baust du keinen Transformer selbst - du nutzt fertige, vortrainierte Transformer-Modelle über eine API (Claude, GPT) oder als Open-Source-Modell (über die Bibliothek Hugging Face Transformers).",
    "Wichtig ist zu verstehen, WARUM diese Modelle so gut sind: Dadurch triffst du bessere Entscheidungen - etwa dass ein LLM Zusammenhänge im Text erfasst, aber trotzdem für aktuelle Fakten RAG braucht.",
    "Transformer stecken heute nicht nur in Text, sondern auch in Übersetzung, Sprache-zu-Text und multimodalen Modellen (Bild + Text)."),
  S("Konkretes Beispiel",
    "Übersetzung: Frühere Systeme übersetzten oft Wort für Wort und verloren den Sinn. Ein Transformer betrachtet den ganzen Satz, erkennt Bezüge (wer tut was) und liefert eine flüssige, sinnvolle Übersetzung. Genau dieselbe Fähigkeit macht ihn auch beim Verstehen von Kundenanfragen stark."),
  S("Vorteile",
    "Erfasst Zusammenhänge über lange Texte hinweg.",
    "Sehr gut parallelisierbar - dadurch schnelles Training und große Modelle.",
    "Universell: gleiche Grundidee für Text, Sprache, Bilder.",
    "Basis praktisch aller heutigen Spitzen-KI."),
  S("Grenzen & Einordnung",
    "Große Transformer brauchen sehr viel Rechenleistung (GPUs) und Energie - deshalb sind Training und Betrieb teuer (siehe GPU-Grundlagen, Green AI).",
    "Ein Transformer 'versteht' nicht wie ein Mensch; er erkennt statistische Muster. Halluzinationen bleiben möglich.",
    "Für den Einsatz zählt weniger, den Transformer im Detail zu bauen, als zu wissen, wie man die fertigen Modelle gut und sicher nutzt."),
  S("So lernst du weiter",
    "Direkt davor im Plan: neuronale Netze, Gewichte, Attention. Direkt danach: Pretraining vs Fine-Tuning und die Anwendung (LLM, Prompting, RAG). Der bebilderte deutsche Text 'Der Transformer illustriert' unten ist der beste Einstieg zum Nachschauen."),
 ],
}

# ===========================================================================
AI_DEEP["Agentic AI"] = {
 "web": [
   ("Fraunhofer IESE: Agentic AI & Multi-Agenten-Systeme", "https://www.iese.fraunhofer.de/blog/agentic-ai-multi-agenten-systeme/"),
   ("IHK Regensburg: KI-Agenten & Nutzen fuer Unternehmen", "https://www.ihk.de/regensburg/fachthemen/digitalisierung/kuenstliche-intelligenz/ki-agenten-und-ihr-nutzen-fuer-unternehmen-6706606"),
   ("BDO: Vom Assistenten zum Akteur - KI-Agenten", "https://www.bdo.de/de-de/insights/aktuelles/advisory-service/vom-assistenten-zum-akteur-wie-ki-agenten-unternehmen-in-die-aera-der-agentic-ai-fuehren"),
   ("IBM: What is Agentic AI?", "https://www.ibm.com/think/topics/agentic-ai"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Es gibt einen berühmten Merksatz: 'Ein Chatbot antwortet - ein Agent handelt.' Agentic AI beschreibt KI-Systeme, die nicht nur auf Fragen reagieren, sondern ein Ziel verfolgen: Sie planen selbst die nötigen Schritte, nutzen Werkzeuge, prüfen ihr Ergebnis und korrigieren sich.",
    "Ein KI-Agent verbindet dazu ein Sprachmodell (das 'Gehirn') mit Werkzeugen (Tools, z.B. eine Kunden-API), einem Gedächtnis (Memory) und einem Ziel. So wird aus einem reinen Textgenerator ein digitaler 'Mitarbeiter', der Aufgaben erledigt."),
  S("Wie es funktioniert (der Denk-Handel-Kreislauf)",
    "Ein Agent arbeitet in einer Schleife (Loop): 1. Denken - was ist mein Ziel, was der nächste Schritt? 2. Handeln - ein Werkzeug benutzen (z.B. Kundendaten holen, einen Termin buchen). 3. Beobachten - was kam heraus? 4. Erneut denken - bin ich fertig oder brauche ich einen weiteren Schritt?",
    "Diese Schleife wiederholt sich, bis das Ziel erreicht ist. Damit sie nicht endlos läuft oder Unsinn macht, setzt man Grenzen: ein Schritt-Limit (Loop Engineering) und feste Regeln (Guardrails).",
    "Man unterscheidet Single-Agent-Systeme (ein Agent macht alles) und Multi-Agent-Systeme (mehrere Agenten mit Rollen arbeiten zusammen, wie ein Team) - Letzteres beschreibt Fraunhofer als das Modell für komplexere Aufgaben."),
  S("Wie man es einsetzt (Praxis im Unternehmen)",
    "Laut den Fachquellen (IHK, BDO, IBM) automatisieren Agenten heute ganze Routineabläufe: Kundenauskünfte, Berichtserstellung, Dokumentenbearbeitung. Sie greifen auf Wissensdatenbanken zu und lösen bis zu 80 % der Standardtickets eigenständig.",
    "In der Bank denkbar: Ein Agent nimmt eine Beschwerde auf, sucht die Kundenhistorie, prüft die Regeln, bereitet eine Lösung vor und legt sie einem Mitarbeiter zur Freigabe vor. Oder: ein Agent, der bei einem Kartenverlust eigenständig sperrt, Ersatz bestellt und den Kunden informiert - kritische Schritte immer mit menschlicher Freigabe.",
    "Wichtig ist die Kontrolle: Human-in-the-loop (Mensch bestätigt kritische Schritte) oder Human-on-the-loop (Mensch überwacht und kann eingreifen). Gerade in Banken ist das Pflicht."),
  S("Konkretes Beispiel",
    "Ein Kunde schreibt: 'Ich habe eine Abbuchung, die ich nicht kenne.' Ein Agent könnte: die Transaktion heraussuchen, prüfen, ob sie als verdächtig markiert ist, dem Kunden Details zeigen, eine vorläufige Kartensperre vorbereiten und einen Reklamationsvorgang anlegen - und dann einen Menschen fragen: 'Sperre bestätigen?' So erledigt der Agent die Fleißarbeit, der Mensch entscheidet das Heikle."),
  S("Vorteile",
    "Erledigt mehrstufige Aufgaben selbstständig, nicht nur einzelne Antworten.",
    "Automatisiert Routine über mehrere Systeme hinweg.",
    "Rund um die Uhr, entlastet Mitarbeiter für Komplexes.",
    "Gartner erwartet, dass bis 2028 ein Drittel der Unternehmenssoftware Agentic AI enthält - der Trend ist groß."),
  S("Grenzen, Risiken & Datenschutz",
    "Nicht alles ist heute zuverlässig: Agenten können Fehler machen, sich verrennen oder in Schleifen hängen. Ehrliche Einordnung: 'Beyond the Hype' - klein und kontrolliert starten.",
    "Excessive Agency: Ein Agent mit zu vielen Rechten kann bei einem Fehler großen Schaden anrichten. Nur nötige Werkzeuge freigeben (Least Privilege).",
    "Sicherheit: Agenten sind angreifbar (Prompt Injection). Und alle Aktionen sollten protokolliert werden (Audit Logging).",
    "In der Bank: kritische Aktionen immer mit menschlicher Freigabe und klaren Guardrails."),
  S("Typische Fehler",
    "Einem Agenten zu früh zu viel Verantwortung/Rechte geben.",
    "Keine Grenzen (Schritt-Limit, Guardrails) setzen.",
    "Keine Nachvollziehbarkeit (kein Tracing/Logging) - dann versteht niemand, was schiefging.",
    "Ohne Pilot direkt groß ausrollen."),
  S("Best Practices / Checkliste",
    "Klein anfangen: eine klar begrenzte Aufgabe, viel Kontrolle.",
    "Human-in-the-loop für kritische Schritte.",
    "Nur nötige Tools freigeben, Guardrails setzen.",
    "Jeden Schritt aufzeichnen (Observability/Tracing) und auswerten.",
    "Erfolg messen (Evaluation), dann vorsichtig ausweiten."),
  S("So lernst du weiter",
    "Im Plan gehören dazu: KI-Agenten-Grundlagen, Single-/Multi-Agent, Agent Memory/Planning/Tools, Guardrails, Human-in-the-loop und AgentOps. Die Fraunhofer- und IHK-Texte unten sind ein guter, seriöser Einstieg auf Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Embeddings"] = {
 "web": [
   ("ki-trainingszentrum: Embeddings einfach erklaert", "https://ki-trainingszentrum.com/embeddings-einfach-erklaert-die-grundlage-moderner-ki-suche/"),
   ("Data Basecamp: Vector Database, Embeddings & RAG", "https://databasecamp.de/daten/vector-database"),
   ("ki.engineering: Embeddings - KI-Vektoren verstehen", "https://ki.engineering/glossar/embeddings/"),
   ("Conciso: RAG und Embeddings einfach erklaert", "https://conciso.de/rag-und-embeddings-die-helfer-von-ki-systemen/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Embedding verwandelt Text (oder Bilder, Ton) in eine lange Liste von Zahlen - einen Vektor. Dieser Vektor ist wie ein 'Bedeutungs-Fingerabdruck': Texte mit ähnlicher Bedeutung bekommen ähnliche Zahlen.",
    "Das ist der Trick, mit dem ein Computer plötzlich 'Bedeutung' vergleichen kann, obwohl er eigentlich nur rechnet. Statt Buchstaben zu vergleichen, vergleicht er Zahlen - und ähnliche Zahlen heißt ähnliche Bedeutung."),
  S("Wie es funktioniert",
    "Ein spezielles KI-Modell (Embedding-Modell) liest einen Text und gibt einen Vektor zurück - typischerweise mehrere hundert bis tausend Zahlen lang.",
    "Jede Zahl steht für einen winzigen Bedeutungs-Aspekt. Man kann sich das wie Koordinaten in einem riesigen 'Bedeutungs-Raum' vorstellen: 'Katze' und 'Hund' liegen nah beieinander (beides Haustiere), 'Katze' und 'Kontoauszug' weit auseinander.",
    "Wie ähnlich zwei Texte sind, misst man über den Abstand ihrer Vektoren. Kleiner Abstand = ähnliche Bedeutung. Ein bekanntes frühes Beispiel ist Word2Vec, das Wörter aus ihrem Kontext heraus in Vektoren umwandelt."),
  S("Wie man es einsetzt (Praxis)",
    "Embeddings sind die Grundlage jeder modernen semantischen Suche und jedes RAG-Systems. Man wandelt alle eigenen Dokumente einmal in Embeddings um und speichert sie in einer Vector Database.",
    "Kommt eine Frage, wird auch sie in ein Embedding umgewandelt, und das System findet die Dokumente mit dem geringsten Abstand - also der ähnlichsten Bedeutung.",
    "In der Bank heißt das: Ein Kunde fragt 'Karte weg', und das System findet den Artikel 'Karte verloren oder gestohlen', obwohl kein einziges Wort exakt übereinstimmt. Auch Empfehlungssysteme und das Gruppieren ähnlicher Kunden nutzen Embeddings."),
  S("Konkretes Beispiel",
    "Die Sätze 'Ich möchte mein Konto kündigen' und 'Wie löse ich mein Girokonto auf?' enthalten kaum gleiche Wörter, meinen aber dasselbe. Ihre Embeddings liegen sehr nah beieinander - deshalb findet der Bot für beide denselben richtigen Wissens-Artikel."),
  S("Grenzen & typische Fehler",
    "Embeddings kennen keine Aktualität: Ein einmal berechneter Vektor ändert sich nicht, wenn sich der Inhalt ändert - man muss neu einbetten, wenn Dokumente sich ändern.",
    "Verschiedene Embedding-Modelle sind nicht kompatibel: Frage und Dokumente müssen mit demselben Modell eingebettet werden.",
    "Für exakte Dinge (Kontonummern, genaue Beträge) ist reine Embedding-Suche schwach - dafür kombiniert man sie mit klassischer Wortsuche (Hybrid Search).",
    "Datenschutz: Auch Embeddings können Rückschlüsse auf den Originaltext zulassen - sie sind kein Ersatz für Anonymisierung."),
  S("So lernst du weiter",
    "Direkt danach im Plan: Vector Search (wie man in Embeddings sucht), Chunking (wie man Texte vorher zuschneidet) und Semantic/Hybrid Search. Die Data-Basecamp-Quelle unten erklärt das Zusammenspiel mit RAG sehr anschaulich."),
 ],
}

# ===========================================================================
AI_DEEP["Vector Search"] = {
 "web": [
   ("Google Cloud: Was ist eine Vektordatenbank?", "https://cloud.google.com/discover/what-is-a-vector-database"),
   ("it-schulungen.com: Vektordatenbanken im Ueberblick", "https://www.it-schulungen.com/wir-ueber-uns/wissensblog/vektordatenbanken-im-ueberblick-architektur-anbieterbeispiele-und-einsatzszenarien.html"),
   ("Elastic: Was ist eine Vektordatenbank?", "https://www.elastic.co/de/what-is/vector-database"),
   ("IONOS: Vektordatenbank - was ist das?", "https://www.ionos.com/digitalguide/server/know-how/vector-database/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Vector Search (Vektorsuche) ist eine Suche nach Bedeutung statt nach exakten Wörtern. Sie vergleicht die Embedding-Vektoren und findet die inhaltlich ähnlichsten Treffer.",
    "Die klassische Suche fragt: 'Welches Dokument enthält genau dieses Wort?' Die Vektorsuche fragt: 'Welches Dokument meint dasselbe?' - auch bei ganz anderer Wortwahl."),
  S("Wie es funktioniert",
    "Alle Dokumente werden als Vektoren in einer Vector Database gespeichert. Bei einer Frage wird die Frage ebenfalls zu einem Vektor.",
    "Die Datenbank misst den Abstand zwischen dem Frage-Vektor und allen gespeicherten Vektoren und liefert die 'Top-k' nächsten Treffer (z.B. die 5 ähnlichsten Chunks).",
    "Bei Millionen Vektoren wäre ein Vergleich mit jedem einzelnen zu langsam. Deshalb nutzen Vektordatenbanken clevere Verfahren (ANN - Approximate Nearest Neighbor), die fast so genau, aber viel schneller sind."),
  S("Wie man es einsetzt (Praxis)",
    "Vector Search ist der 'Retrieval'-Schritt in RAG: Die gefundenen Top-k Chunks werden dem LLM als Kontext übergeben.",
    "Laut den Fachquellen gibt es zwei Wege: dedizierte Vektordatenbanken (z.B. Pinecone, Weaviate, Milvus, Chroma) oder bestehende Datenbanken mit Vektor-Erweiterung (PostgreSQL + pgvector, MongoDB Atlas, Elasticsearch, Redis). Letzteres vermeidet ein zweites System und reduziert Abhängigkeiten (Lock-in).",
    "In der Bank: Damit durchsucht ein Bot Handbücher und Richtlinien nach Bedeutung; auch Betrugsabwehr und Empfehlungen nutzen Ähnlichkeitssuche."),
  S("Konkretes Beispiel",
    "Frage: 'Was passiert, wenn ich meine PIN dreimal falsch eingebe?' Die Vektorsuche findet den Chunk aus dem Sicherheitsleitfaden über 'Kartensperrung nach fehlerhafter PIN-Eingabe' - selbst wenn dort das Wort 'dreimal' gar nicht vorkommt, sondern 'nach mehreren Fehlversuchen'."),
  S("Grenzen & typische Fehler",
    "Zu viele oder zu wenige Treffer (k) einstellen: zu wenige = wichtige Info fehlt, zu viele = das LLM wird mit Beiwerk zugemüllt.",
    "Rein semantisch reicht nicht bei exakten Begriffen/Nummern - dann Hybrid Search (Wort + Bedeutung) nutzen.",
    "Qualität steht und fällt mit gutem Chunking und gutem Embedding-Modell.",
    "Datenschutz/Region beachten: Wo liegt die Vektordatenbank? In der Bank möglichst EU/On-Prem."),
  S("So lernst du weiter",
    "Davor: Embeddings. Danach: Chunking, RAG-Architektur, Hybrid Search. Der Google-Cloud- und der IONOS-Text unten erklären Vektordatenbanken einsteigerfreundlich."),
 ],
}

# ===========================================================================
AI_DEEP["Chunking"] = {
 "web": [
   ("IBM: Chunking-Strategien fuer RAG (Tutorial)", "https://www.ibm.com/think/tutorials/chunking-strategies-for-rag-with-langchain-watsonx-ai"),
   ("Unstructured: Chunking for RAG - Best Practices", "https://unstructured.io/blog/chunking-for-rag-best-practices"),
   ("Databricks: Ultimate Guide to Chunking Strategies", "https://community.databricks.com/t5/technical-blog/the-ultimate-guide-to-chunking-strategies-for-rag-applications/ba-p/113089"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Chunking heißt, lange Dokumente in kleine, sinnvolle Stücke (Chunks) zu schneiden, bevor man sie in Embeddings umwandelt und speichert.",
    "Warum? Ein ganzes 50-Seiten-Handbuch als ein Stück wäre für die Suche unbrauchbar - man würde nie die genaue Stelle finden. Kleine Häppchen lassen die Suche gezielt die richtige Passage liefern."),
  S("Wie es funktioniert",
    "Man legt eine Chunk-Größe fest (oft in Tokens) und meist einen Overlap (Überlappung), damit an den Schnittstellen kein Zusammenhang verloren geht.",
    "Gängige Strategien laut den Quellen: Fixed-size (feste Größe, einfachster Weg), Recursive (schneidet an natürlichen Grenzen wie Absätzen/Sätzen) und Sliding-Window (überlappende Fenster). Recursive erhält den Sinn oft besser."),
  S("Wie man es einsetzt (Praxis) & Richtwerte",
    "Ein bewährter Startpunkt aus der Praxis: RecursiveCharacterTextSplitter mit ca. 512 Tokens und 50 Tokens Overlap - das funktioniert laut Databricks/IBM für rund 80 % der Fälle. Alternativ ~250 Tokens (~1000 Zeichen) als kleinerer Start.",
    "Faustregel: Chunks groß genug für sinnvollen Zusammenhang, aber klein genug, um genau zu bleiben. Wichtig: An den eigenen Daten und echten Fragen testen (benchmarken), nicht raten.",
    "In der Bank: Ein Preis- und Leistungsverzeichnis schneidet man sinnvollerweise pro Leistung/Abschnitt, nicht mitten im Satz - so liefert die Suche saubere, vollständige Antworten."),
  S("Konkretes Beispiel",
    "Schlechtes Chunking: Ein Chunk endet mitten in 'Die Gebühr beträgt' - der Betrag steht im nächsten Chunk. Die KI findet nur die Hälfte und antwortet unvollständig.",
    "Gutes Chunking: Der ganze Absatz 'Kontoführungsgebühr: 4,90 € pro Monat, entfällt ab 700 € Geldeingang' bleibt zusammen - die Antwort stimmt."),
  S("Grenzen & typische Fehler",
    "Zu große Chunks: Die Suche wird ungenau, das LLM bekommt zu viel Beiwerk (und es kostet mehr Tokens).",
    "Zu kleine Chunks: Der Zusammenhang zerbricht, Antworten werden lückenhaft.",
    "Kein Overlap: An den Schnittkanten geht Information verloren.",
    "Tabellen/Listen stur nach Zeichen schneiden zerstört ihre Bedeutung - hier braucht es strukturbewusstes Chunking."),
  S("So lernst du weiter",
    "Chunking ist der erste Schritt der RAG-Pipeline (davor: Dokumente laden; danach: Embeddings, Vector Search). Die IBM- und Unstructured-Guides unten zeigen konkrete Strategien mit Beispielen."),
 ],
}

# ===========================================================================
AI_DEEP["Halluzinationen"] = {
 "web": [
   ("Fraunhofer IESE: Halluzinationen von GenAI/LLMs", "https://www.iese.fraunhofer.de/blog/halluzinationen-generative-ki-llm/"),
   ("Google Cloud: Was sind KI-Halluzinationen?", "https://cloud.google.com/discover/what-are-ai-hallucinations"),
   ("IBM: Was sind KI-Halluzinationen?", "https://www.ibm.com/think/topics/ai-hallucinations"),
   ("mindsquare: KI-Halluzinationen erkennen & vermeiden", "https://mindsquare.de/fachartikel/kuenstliche-intelligenz/ki-halluzinationen/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Eine Halluzination ist, wenn eine KI etwas Falsches behauptet - aber so überzeugend und flüssig, dass es echt klingt. Die KI 'lügt' nicht absichtlich; sie erzeugt einfach die statistisch plausibelste Wortfolge, auch wenn diese sachlich falsch ist.",
    "Genau das macht Halluzinationen in der Bank gefährlich: Eine falsche Auskunft zu Gebühren, Fristen oder Rechten kann echten Schaden anrichten. Deshalb muss man sie verstehen und aktiv eindämmen."),
  S("Warum es passiert (Ursachen)",
    "Ein LLM sagt immer nur das wahrscheinlichste nächste Wort voraus - es hat kein echtes 'Wissen' und keine Wahrheitsprüfung eingebaut.",
    "Häufige Ursachen laut den Fachquellen: fehlerhafte oder unvollständige Trainingsdaten; veraltete Daten (das Modell kennt eure heutigen Konditionen nicht); fehlendes Spezialwissen; und die Grundfunktion selbst (plausibel statt korrekt).",
    "Besonders oft passiert es bei sehr speziellen Fragen, zu denen das Modell nichts gelernt hat - dann 'füllt' es die Lücke mit erfundenen, aber glaubwürdig klingenden Details."),
  S("Wie man es einsetzt/verhindert (Praxis)",
    "Der wichtigste Gegenmechanismus ist Grounding per RAG: Man gibt dem Modell vor der Antwort echte, geprüfte Dokumente und lässt es NUR daraus antworten. Ein gutes System gibt zu, wenn der Kontext nicht ausreicht, statt zu raten.",
    "Weitere Maßnahmen: Quellen anzeigen (damit man prüfen kann), klare Prompts ('Antworte nur aus dem gegebenen Kontext; wenn unklar, sage das'), Temperatur/Kreativität niedrig halten, und bei heiklen Themen einen Menschen prüfen lassen (Human-in-the-loop).",
    "In der Bank: Für rechts- oder geldrelevante Auskünfte nie ein rohes LLM ohne Quellen einsetzen - immer RAG plus Prüfung."),
  S("Konkretes Beispiel",
    "Frage: 'Bis wann kann ich eine Überweisung zurückrufen?' Ein rohes LLM erfindet vielleicht selbstbewusst 'innerhalb von 24 Stunden'. Mit Grounding sucht das System die echte Hausregel und antwortet korrekt mit Quelle - oder sagt ehrlich, dass es dazu keine Info hat und verbindet an einen Mitarbeiter."),
  S("Grenzen & typische Fehler",
    "Man kann Halluzinationen stark reduzieren, aber nie zu 100 % ausschließen - deshalb bleibt Prüfung wichtig.",
    "Typischer Fehler: dem flüssigen, selbstsicheren Ton der KI vertrauen ('klingt richtig, also ist es richtig').",
    "Ohne Quellenangabe kann niemand die Antwort kontrollieren.",
    "Kein Fallback für 'weiß ich nicht' - dann rät die KI, statt zu übergeben."),
  S("So lernst du weiter",
    "Direkt danach im Plan: Grounding und die ganze RAG-Kette. Der Fraunhofer-IESE-Text unten erklärt Ursachen und Gegenmittel ausführlich und seriös auf Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Grounding"] = {
 "web": [
   ("Fraunhofer IESE: Halluzinationen & Gegenmittel", "https://www.iese.fraunhofer.de/blog/halluzinationen-generative-ki-llm/"),
   ("undetectable.ai: Grounding and Hallucinations in AI", "https://undetectable.ai/blog/grounding-and-hallucinations-in-ai/"),
   ("copilotenschule.de: KI-Halluzinationen vermeiden", "https://copilotenschule.de/wissen/ki-halluzinationen-vermeiden"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Grounding heißt wörtlich 'erden' - die KI-Antwort wird auf den Boden echter, geprüfter Fakten gestellt. Statt frei aus dem Gedächtnis zu reden, stützt sich die KI auf konkrete Quellen, die man ihr mitgibt.",
    "Grounding ist das wichtigste Gegenmittel gegen Halluzinationen und die Voraussetzung für vertrauenswürdige KI in einer Bank."),
  S("Wie es funktioniert",
    "Der Ablauf: 1. Die Frage kommt rein. 2. Das System sucht in glaubwürdigen Quellen (eure Dokumente, eine Datenbank, eine Live-Suche) die passenden Fakten. 3. Diese Fakten werden dem LLM zusammen mit der Frage übergeben. 4. Das LLM formuliert die Antwort aus diesen Fakten - idealerweise mit Quellenangabe.",
    "Technisch ist Retrieval Augmented Generation (RAG) die häufigste Form von Grounding. Ein gut 'geerdetes' System sagt außerdem ehrlich, wenn die Quellen nicht ausreichen, statt etwas zu erfinden."),
  S("Wie man es einsetzt (Praxis)",
    "Man verbindet das LLM mit einer verlässlichen Wissensquelle: interne Knowledge Base, Produktdatenbank, geprüfte Handbücher. Im Genesys-Teil ist genau das die Knowledge Base, die man mit dem Bot Flow verbindet.",
    "Wichtig: Nur geprüfte, aktuelle Quellen anbinden - Grounding auf schlechte Quellen erdet auf falschen Fakten.",
    "In der Bank sorgt Grounding dafür, dass Auskünfte zu Konto, Karte und Kredit aus den offiziellen Unterlagen kommen und mit Quelle belegbar sind - wichtig für Kundenvertrauen und Aufsicht."),
  S("Konkretes Beispiel",
    "Ohne Grounding: 'Ihr Tageslimit beträgt vermutlich 1.000 €' (geraten). Mit Grounding: Das System liest das hinterlegte Limit des Kunden aus dem System und antwortet: 'Ihr aktuelles Tageslimit beträgt 1.500 € (Quelle: Kontoeinstellungen).'"),
  S("Grenzen & typische Fehler",
    "Grounding ist nur so gut wie die Quelle: veraltete oder falsche Dokumente führen zu falschen, aber 'belegten' Antworten.",
    "Findet die Suche die falsche Stelle, wird selbstbewusst falsch geantwortet - deshalb regelmäßig evaluieren.",
    "Typischer Fehler: Grounding einbauen, aber keine Quelle anzeigen - dann bleibt die Prüfbarkeit auf der Strecke.",
    "Kein Plan für 'nichts Passendes gefunden' - der Bot sollte dann übergeben statt zu raten."),
  S("So lernst du weiter",
    "Grounding und Halluzinationen gehören zusammen; danach folgt die komplette RAG-Kette (Embeddings, Vector Search, Chunking, Evaluation). Die Fraunhofer-Quelle unten ordnet beides gut ein."),
 ],
}

# ===========================================================================
AI_DEEP["Token und Kosten"] = {
 "web": [
   ("Anthropic: Pricing & Tokens", "https://docs.anthropic.com/en/docs/about-claude/pricing"),
   ("OpenAI: Tokenizer & wie Tokens zaehlen", "https://platform.openai.com/tokenizer"),
   ("Alexander Thamm: LLM-Grundlagen (Tokens)", "https://www.alexanderthamm.com/de/blog/large-language-models-eine-einfuehrung/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "KI-Sprachmodelle rechnen nicht in Wörtern, sondern in Tokens - kleinen Textbausteinen. Ein Token ist grob 3-4 Zeichen; ein längeres Wort kann aus mehreren Tokens bestehen. Faustregel: 100 Tokens ≈ 75 englische Wörter (Deutsch oft etwas mehr Tokens).",
    "Wichtig fürs Geld: Fast alle Anbieter rechnen pro Token ab - für den Text, den du hineingibst (Input), UND für den Text, den die KI erzeugt (Output)."),
  S("Wie es funktioniert",
    "Vor der Verarbeitung zerlegt ein 'Tokenizer' den Text in Tokens. Das Modell verarbeitet und erzeugt Tokens; am Ende werden sie wieder zu lesbarem Text.",
    "Jedes Modell hat ein Kontextfenster (Context Window) - die maximale Zahl an Tokens für Eingabe + Ausgabe zusammen. Ist der Text länger, muss man kürzen oder aufteilen.",
    "Kosten = (Input-Tokens × Input-Preis) + (Output-Tokens × Output-Preis). Output ist oft teurer als Input."),
  S("Wie man es einsetzt (Praxis: Kosten steuern)",
    "Kurz und gezielt prompten: unnötig langer Kontext kostet bei JEDEM Aufruf mit.",
    "Das richtige Modell wählen: für einfache Aufgaben ein kleines/günstiges Modell (SLM), nur für Schwieriges ein großes.",
    "Bei RAG nur die wirklich relevanten Chunks mitgeben, nicht ganze Dokumente.",
    "Caching nutzen (wiederkehrende Kontexte), Antwortlänge begrenzen, und die Kosten laufend überwachen (siehe AI Cost Monitoring).",
    "In der Bank: Kosten pro Gespräch grob kalkulieren und Budgets/Alarme setzen, damit ein Bot nicht unbemerkt teuer wird."),
  S("Konkretes Beispiel",
    "Ein Bot, der bei jeder Frage das komplette 20-Seiten-Handbuch mitschickt, verbraucht pro Anfrage zehntausende Tokens - unnötig teuer. Mit RAG schickt er nur die 2-3 passenden Chunks (ein paar hundert Tokens) und liefert dieselbe Antwort für einen Bruchteil der Kosten."),
  S("Grenzen & typische Fehler",
    "Deutsch und Fachbegriffe/Zahlen erzeugen oft mehr Tokens als erwartet - lieber real messen (Tokenizer-Tools).",
    "Typischer Fehler: das teuerste Modell für alles nehmen.",
    "Zu langer Kontext 'für alle Fälle' - bläht Kosten und kann die Qualität sogar senken.",
    "Kosten nicht überwachen und am Monatsende überrascht werden."),
  S("So lernst du weiter",
    "Passt zu: LLM-Grundlagen, RAG (spart Tokens) und AI Cost Monitoring. Die Anthropic-Preisseite und der OpenAI-Tokenizer unten zeigen konkret, wie Tokens gezählt und abgerechnet werden."),
 ],
}

# ===========================================================================
AI_DEEP["Semantic Search"] = {
 "web": [
   ("Elastic: Was ist semantische Suche?", "https://www.elastic.co/de/what-is/semantic-search"),
   ("Google Cloud: Vektordatenbank & semantische Suche", "https://cloud.google.com/discover/what-is-a-vector-database"),
   ("Data Basecamp: semantische Suche & RAG", "https://databasecamp.de/daten/vector-database"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Semantic Search (semantische Suche) ist eine Suche, die die Bedeutung versteht. Man muss nicht das exakte Wort treffen - die Suche findet, was gemeint ist.",
    "Die klassische Suche vergleicht Buchstaben ('kommt das Wort vor?'). Die semantische Suche vergleicht Bedeutung (über Embeddings) - deshalb findet sie 'Karte weg' auch beim Artikel 'Karte verloren'."),
  S("Wie es funktioniert",
    "Sie baut auf Embeddings und Vector Search auf: Dokumente und Frage werden zu Vektoren, und die Suche liefert die bedeutungsähnlichsten Treffer.",
    "Dadurch versteht sie Synonyme, Umschreibungen und Tippfehler viel besser als die reine Wortsuche."),
  S("Wie man es einsetzt (Praxis)",
    "Semantische Suche steckt im Retrieval-Schritt jedes RAG-Systems, im Genesys Knowledge-Portal und in jeder guten Wissenssuche für Kunden und Mitarbeiter.",
    "In der Praxis kombiniert man sie oft mit der klassischen Wortsuche zu Hybrid Search: semantisch für Formulierungen, Wortsuche für exakte Begriffe, Produktnamen und Nummern.",
    "In der Bank: Kunden und Agenten finden Antworten, ohne die 'richtigen' Fachwörter zu kennen - das senkt Frust und entlastet die Hotline."),
  S("Konkretes Beispiel",
    "Ein Kunde sucht 'Geld ins Ausland schicken'. Die semantische Suche findet den Artikel 'Auslandsüberweisung / SEPA & SWIFT', obwohl der Kunde keinen dieser Fachbegriffe verwendet hat."),
  S("Grenzen & typische Fehler",
    "Bei exakten Codes, IBANs oder Produktnummern ist reine Semantik schwächer - dann Hybrid Search nutzen.",
    "Qualität hängt vom Embedding-Modell und von gutem Chunking ab.",
    "Sprache beachten: Für deutsche Inhalte ein Modell wählen, das Deutsch gut kann.",
    "Ohne Prüfung/Feedback bleiben schlechte Treffer unentdeckt."),
  S("So lernst du weiter",
    "Direkt verwandt: Embeddings, Vector Search und Hybrid Search. Der Elastic-Text unten erklärt semantische Suche einsteigerfreundlich auf Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Small Language Models"] = {
 "web": [
   ("ComputerWeekly: Small Language Model (SLM)", "https://www.computerweekly.com/de/definition/Small-Language-Model-SLM"),
   ("Exxeta: SLM in Enterprise-Unternehmen (SLM vs LLM)", "https://exxeta.com/blog/small-language-models-enterprise-use-cases-slm-vs-llm"),
   ("bigdata-insider: Was ist ein SLM?", "https://www.bigdata-insider.de/was-ist-ein-small-language-model-slm-a-b4d354ab30465f7da451a05617e060c3/"),
   ("Alexander Thamm: Small Language Models", "https://www.alexanderthamm.com/de/blog/small-language-models/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Small Language Model (SLM) ist ein kleines Sprachmodell. Es kann weniger als ein großes LLM, ist dafür aber günstiger, schneller und kann auf schwacher Hardware laufen - teils sogar auf einer normalen CPU oder direkt auf dem Gerät.",
    "Die Idee: Nicht jede Aufgabe braucht das größte, teuerste Modell. Für klar umrissene Aufgaben reicht oft ein kleines, spezialisiertes Modell völlig aus - und ist in der Praxis sogar die bessere Wahl."),
  S("Wie es funktioniert",
    "SLMs sind nach demselben Prinzip gebaut wie LLMs (Transformer), haben aber viel weniger Parameter. Dadurch brauchen sie weniger Rechenleistung und Speicher.",
    "Oft entstehen sie, indem man ein großes Modell verkleinert (Quantization) oder ein kleines Modell gezielt für eine Aufgabe feintunt. So bleibt viel Können bei deutlich kleinerer Größe."),
  S("Wie man es einsetzt (Praxis & Vorteile)",
    "Die Fachquellen nennen als Hauptvorteile: Kosten- und Energieeffizienz, schnelle Antwortzeiten, Betrieb auf schwacher/lokaler Hardware, einfaches Fine-Tuning und - besonders wichtig für Banken - Datenschutz, weil das Modell lokal oder in der privaten Cloud laufen kann und Daten im Haus bleiben.",
    "Typische Einsätze: Chatbots für klar umrissene Themen, Klassifizieren/Vorsortieren von Anfragen, Zusammenfassen, Assistenten auf Mobilgeräten oder 'am Rand' (Edge).",
    "In der Bank: Ein SLM kann on-premise sensible Aufgaben übernehmen (z.B. E-Mails kategorisieren), ohne dass Daten das Haus verlassen - oft in Kombination mit RAG für das Fachwissen."),
  S("Konkretes Beispiel",
    "Für 'Sortiere eingehende E-Mails nach Abteilung' braucht man kein Riesen-LLM. Ein kleines, lokal betriebenes SLM erledigt das schnell, günstig und datenschutzkonform - der teure Cloud-Aufruf entfällt."),
  S("Grenzen & typische Fehler",
    "SLMs sind schwächer bei sehr komplexen, offenen Aufgaben und breitem Weltwissen - dafür bleibt das LLM besser.",
    "Typischer Fehler: aus Prinzip immer das größte Modell nehmen (teuer) - oder umgekehrt ein zu kleines Modell für eine zu komplexe Aufgabe.",
    "SLMs profitieren stark von gutem Fine-Tuning/RAG; roh sind sie manchmal enttäuschend.",
    "Modellwahl an der Aufgabe ausrichten, nicht am Hype."),
  S("So lernst du weiter",
    "Passt eng zu: LLM (der große Bruder), Quantization, Fine-Tuning, Local/Private AI und Ollama. Der Exxeta-Text unten vergleicht SLM vs LLM praxisnah für Unternehmen."),
 ],
}

# ===========================================================================
AI_DEEP["Multimodalitaet"] = {
 "web": [
   ("ComputerWeekly: Multimodale KI", "https://www.computerweekly.com/de/definition/Multimodale-kuenstliche-Intelligenz-multimodale-KI"),
   ("mindsquare: Multimodale KI", "https://mindsquare.de/knowhow/multimodale-ki/"),
   ("Alexander Thamm: Large Multimodal Models", "https://www.alexanderthamm.com/de/blog/large-multimodal-models-kompakt-erklaert/"),
   ("awantego: Was ist Multimodale KI?", "https://www.awantego.com/was-ist-multimodale-ki/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Eine Modalität ist eine Art von Information: Text, Bild, Ton, Video. Multimodale KI kann mehrere davon gleichzeitig verstehen und verknüpfen - nicht nur Text lesen, sondern auch ein Foto ansehen oder Sprache hören.",
    "Man kann so einer KI z.B. ein Foto eines Kontoauszugs zeigen und dazu eine Frage stellen - sie versteht Bild und Text zusammen."),
  S("Wie es funktioniert",
    "Laut den Fachquellen hat ein multimodales System für jede Modalität ein spezialisiertes Modul (z.B. Computer Vision für Bilder, Sprachverarbeitung für Text). Die Ergebnisse werden dann zu einer gemeinsamen Repräsentation verschmolzen (multimodale Fusion).",
    "Dadurch entstehen Erkenntnisse, die man bei getrennter Analyse übersehen würde: Ein Hundebild plus Hundegeräusch wird sicherer korrekt erkannt als jedes für sich. (Beispiel aus der Forschung: Metas ImageBind verbindet sechs Modalitäten.)"),
  S("Wie man es einsetzt (Praxis)",
    "Sehr nützlich für Dokumente: Ausweise, Rechnungen, Formulare, Screenshots - die KI 'sieht' das Dokument und zieht die Infos heraus (verbunden mit OCR und Document Processing).",
    "Weitere Einsätze: Barrierefreiheit (automatische Bildbeschreibungen), Sprachassistenten (Ton + Text), Qualitäts-/Betrugsprüfung anhand von Bildern.",
    "In der Bank: Ein Kunde fotografiert ein Schreiben und fragt 'Was muss ich tun?' - die KI liest das Bild und erklärt die nächsten Schritte. Bei sensiblen Dokumenten gelten strenge Datenschutzregeln (wo läuft das Modell, was wird gespeichert)."),
  S("Konkretes Beispiel",
    "Ein Kunde lädt das Foto einer unbekannten Kartenabbuchung hoch. Die multimodale KI erkennt Händlername und Betrag im Bild, gleicht sie mit den Transaktionen ab und erklärt, worum es sich handelt - oder startet eine Reklamation."),
  S("Grenzen, Risiken & typische Fehler",
    "Bildverstehen kann irren (schlechte Fotos, Handschrift) - Ergebnisse bei wichtigen Dingen prüfen.",
    "Datenschutz ist heikel: Bilder von Ausweisen/Dokumenten sind hochsensibel (DSGVO, Datenklassifizierung).",
    "Multimodale Modelle sind größer/teurer - nicht für jede Aufgabe nötig.",
    "Typischer Fehler: sich blind auf die Bilddeutung verlassen ohne Kontrolle."),
  S("So lernst du weiter",
    "Verwandt: AI OCR, AI Document Processing, Computer Vision (CNN) und Speech-to-Text. Der ComputerWeekly- und mindsquare-Text unten erklären multimodale KI kompakt auf Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Reasoning"] = {
 "web": [
   ("IBM: What is AI reasoning?", "https://www.ibm.com/think/topics/ai-reasoning"),
   ("Anthropic: Extended thinking (Reasoning)", "https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking"),
   ("Alexander Thamm: LLM-Grundlagen", "https://www.alexanderthamm.com/de/blog/large-language-models-eine-einfuehrung/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Reasoning heißt 'Schlussfolgern'. Neuere KI-Modelle können sich vor der Antwort Zeit nehmen und in Zwischenschritten 'nachdenken', statt sofort das erstbeste Wort auszugeben. Dadurch lösen sie schwierige, mehrstufige Aufgaben deutlich besser.",
    "Man kann es mit einem Menschen vergleichen: Bei einer kniffligen Rechnung rechnet man Schritt für Schritt auf einem Zettel, statt das Ergebnis zu raten."),
  S("Wie es funktioniert",
    "Reasoning-Modelle erzeugen intern eine Kette von Gedankenschritten (Chain-of-Thought), bevor sie die finale Antwort geben. Diese Zwischenschritte helfen ihnen, Fehler zu vermeiden und komplexe Zusammenhänge zu ordnen.",
    "Das kostet mehr Rechenzeit und mehr Tokens (die Denk-Schritte zählen mit), bringt aber bei logischen, mathematischen oder planenden Aufgaben klar bessere Ergebnisse."),
  S("Wie man es einsetzt (Praxis)",
    "Nutze Reasoning gezielt für Aufgaben, die mehrere Schritte oder Logik brauchen: Regeln prüfen, aus Bedingungen eine Entscheidung ableiten, Pläne erstellen, komplexe Anfragen zerlegen.",
    "Für einfache Fragen (Standard-FAQ) ist ein normales, schnelles Modell günstiger - Reasoning lohnt sich vor allem beim Schwierigen. Auch KI-Agenten stützen sich stark auf Reasoning, um ihre Handlungen zu planen und zu prüfen.",
    "In der Bank: z.B. um aus mehreren Bedingungen (Einkommen, Laufzeit, Sicherheiten) eine strukturierte Einschätzung vorzubereiten - die Letztentscheidung bleibt beim Menschen."),
  S("Konkretes Beispiel",
    "Frage: 'Kunde will 3 Daueraufträge auf ein neues Konto umziehen, einer überschneidet sich mit einer Lastschrift - was ist zu tun?' Ein Reasoning-Modell geht die Fälle einzeln durch, erkennt den Konflikt und schlägt eine geordnete Reihenfolge vor, statt oberflächlich zu antworten."),
  S("Grenzen & typische Fehler",
    "Mehr Denken = mehr Kosten und längere Antwortzeit - nicht für jede Kleinigkeit sinnvoll.",
    "Reasoning verhindert Halluzinationen nicht automatisch: Für Fakten braucht es weiterhin Grounding/RAG.",
    "Die internen Denkschritte sind kein Beweis - sie können auch plausibel-falsch sein.",
    "Typischer Fehler: Reasoning-Modelle für simple Aufgaben einsetzen und unnötig zahlen."),
  S("So lernst du weiter",
    "Passt zu: Prompting (Chain-of-Thought), Advanced Prompting und Agent Reasoning/Planning. Der IBM- und Anthropic-Text unten erklären das Prinzip genauer."),
 ],
}

# ===========================================================================
AI_DEEP["Advanced Prompting"] = {
 "web": [
   ("Prompt Engineering Guide (DE): Techniken", "https://www.promptingguide.ai/de/techniques"),
   ("Anthropic: Prompt Engineering Overview", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview"),
   ("IBM: Guide to Prompt Engineering", "https://www.ibm.com/think/prompt-engineering"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Advanced Prompting sind fortgeschrittene Techniken, um mehr und Zuverlässigeres aus einer KI herauszuholen - über den einfachen 'Stell eine klare Frage'-Ansatz hinaus.",
    "Man braucht dafür immer noch nicht zu programmieren; es sind clevere Arten, die Anweisung zu strukturieren."),
  S("Die wichtigsten Techniken",
    "Few-shot: Gib 1-3 Beispiele für gute Frage-Antwort-Paare mit. Die KI ahmt das Muster nach - stark bei einheitlichem Format.",
    "Chain-of-Thought: Bitte die KI, 'Schritt für Schritt' zu denken. Hilft bei Logik- und Rechenaufgaben.",
    "Rollen & Systemprompt: Lege Rolle, Regeln und Grenzen fest ('Du bist Bankberater, gib keine Rechtsberatung').",
    "Struktur & Format erzwingen: Verlange eine bestimmte Ausgabe (z.B. Stichpunkte, JSON, feste Felder).",
    "Selbstprüfung: Lass die KI ihre eigene Antwort gegen die Vorgaben prüfen ('Prüfe, ob alle Regeln eingehalten sind')."),
  S("Wie man es einsetzt (Praxis)",
    "Der bewährte Weg (laut den Guides): einfach starten und schrittweise verfeinern - Beispiele ergänzen, Format vorgeben, testen. Iteration ist der Kern.",
    "In produktiven Bank-Bots kombiniert man diese Techniken: ein fester Systemprompt (Rolle + Sicherheitsregeln), Few-shot-Beispiele für den Ton, klare Formatvorgaben und die Regel 'nur aus dem gegebenen Kontext antworten' (für RAG).",
    "Weil solche Prompts wichtig sind, werden sie versioniert und vor dem Live-Gang getestet (Prompt Versioning, AI Testing)."),
  S("Konkretes Beispiel",
    "Few-shot für einheitliche Zusammenfassungen: Man gibt zwei Beispiel-Gespräche mit Muster-Zusammenfassung vor. Danach erzeugt die KI alle weiteren Zusammenfassungen im exakt gleichen, gewünschten Format - ohne dass man es jedes Mal neu erklären muss."),
  S("Grenzen & typische Fehler",
    "Mehr Beispiele/Kontext = mehr Tokens = höhere Kosten; nur so viel wie nötig.",
    "Zu viele Regeln auf einmal können sich widersprechen - klar und geordnet halten.",
    "Sicherheit: Nutzereingaben strikt vom Systemprompt trennen, sonst droht Prompt Injection.",
    "Techniken nicht testen: Was bei einem Modell gut wirkt, kann bei einem anderen anders wirken - immer prüfen."),
  S("So lernst du weiter",
    "Baut auf Prompting und Prompt Engineering auf, führt zu Context Engineering und (bei Sicherheit) zu Prompt Injection. Der deutschsprachige Prompt Engineering Guide unten ist die beste kostenlose Vertiefung."),
 ],
}

# ===========================================================================
AI_DEEP["Context Engineering"] = {
 "web": [
   ("Prompt Engineering Guide: Context Engineering", "https://www.promptingguide.ai/guides/context-engineering-guide"),
   ("Abstracta: Context Engineering vs Prompt Engineering", "https://abstracta.us/blog/ai/context-engineering-vs-prompt-engineering/"),
   ("Anthropic: Prompt Engineering Overview", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Context Engineering heißt: dafür sorgen, dass die richtigen Zusatz-Informationen im richtigen Moment im 'Blickfeld' der KI landen (im Kontextfenster). Es geht nicht nur darum, WIE man fragt (das ist Prompt Engineering), sondern WELCHES Wissen man mitgibt.",
    "Ein guter Merksatz aus der Praxis: 'Prompt Engineering ist, was du im Kontextfenster machst - Context Engineering entscheidet, was das Fenster füllt.'"),
  S("Wie es funktioniert",
    "Context Engineering baut die 'Informations-Umgebung' der KI: Welche Dokumente, welche Kundendaten, welche Regeln, welcher Gesprächsverlauf werden mitgeschickt - und in welcher Reihenfolge, wie gekürzt und wie aktuell.",
    "Es ist damit näher an Systemdesign als an Textformulierung. Bei RAG ist Context Engineering die Kunst, genau die relevanten Chunks (nicht zu viel, nicht zu wenig) beizusteuern."),
  S("Wie man es einsetzt (Praxis)",
    "Nur relevantes Wissen mitgeben (zu viel Kontext verwirrt die KI und kostet Tokens).",
    "Frische, geprüfte Quellen bevorzugen; Widersprüchliches vermeiden.",
    "Kundendaten und Regeln gezielt einspeisen (z.B. das echte Kontolimit, die geltende Hausregel).",
    "Bei langen Gesprächen den Verlauf sinnvoll zusammenfassen, statt alles mitzuschleppen.",
    "In der Bank entscheidet gutes Context Engineering, ob der Bot korrekt UND datensparsam antwortet - man gibt nur die nötigen Daten, nicht die ganze Kundenakte."),
  S("Konkretes Beispiel",
    "Statt dem Modell die komplette 30-seitige Kontohistorie zu schicken, liefert gutes Context Engineering nur: aktuelles Limit, letzte 3 relevanten Transaktionen und die passende Hausregel. Ergebnis: präzisere Antwort, weniger Kosten, weniger Datenschutz-Risiko."),
  S("Grenzen & typische Fehler",
    "'Mehr Kontext = besser' ist ein Irrtum: zu viel Kontext senkt Qualität und erhöht Kosten (und Risiko).",
    "Veralteter oder widersprüchlicher Kontext führt zu falschen Antworten.",
    "Zu viele sensible Daten mitzugeben verletzt die Datenminimierung (DSGVO).",
    "Typischer Fehler: alles 'für alle Fälle' reinpacken."),
  S("So lernst du weiter",
    "Baut auf Prompting/Advanced Prompting auf und ist das Bindeglied zu RAG und Agenten (Agent Memory). Der Context-Engineering-Guide unten vertieft das Thema gut."),
 ],
}

# ===========================================================================
AI_DEEP["RAG Architektur"] = {
 "web": [
   ("Fraunhofer IESE: RAG - Chat mit eigenen Daten", "https://www.iese.fraunhofer.de/blog/retrieval-augmented-generation-rag/"),
   ("virtido: RAG Leitfaden 2026", "https://virtido.com/de/blog/was-ist-rag-retrieval-augmented-generation-leitfaden"),
   ("LangChain (GitHub)", "https://github.com/langchain-ai/langchain"),
   ("LlamaIndex (GitHub)", "https://github.com/run-llama/llama_index"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Die RAG-Architektur ist der komplette Bauplan eines Wissens-Bots: Sie beschreibt, wie eure Dokumente zu durchsuchbarem Wissen werden und wie daraus am Ende eine belegte Antwort entsteht.",
    "Man teilt sie in zwei Phasen: die Vorbereitung (einmalig, offline) und die Beantwortung (bei jeder Frage, live)."),
  S("Phase 1: Vorbereitung (Ingestion)",
    "1. Laden: Dokumente aus Quellen einsammeln (PDFs, Wiki, Datenbank).",
    "2. Chunking: in sinnvolle Stücke schneiden.",
    "3. Embeddings: jedes Stück in einen Vektor umwandeln.",
    "4. Speichern: die Vektoren in einer Vector Database ablegen (Index).",
    "Diese Phase läuft im Hintergrund und wird wiederholt, wenn sich Dokumente ändern."),
  S("Phase 2: Beantwortung (Retrieval + Generation)",
    "5. Frage einbetten: die Nutzerfrage wird zum Vektor.",
    "6. Retrieval: die ähnlichsten Chunks werden gesucht (Vector/Hybrid Search).",
    "7. Prompt bauen: Frage + gefundene Chunks + Regeln ('nur daraus antworten').",
    "8. Generation: das LLM formuliert die Antwort, idealerweise mit Quellenangabe.",
    "Optional gibt es Bausteine wie Re-Ranking (Treffer neu sortieren) oder Guardrails."),
  S("Wie man es einsetzt (Praxis)",
    "Man muss das nicht selbst programmieren: Frameworks wie LangChain und LlamaIndex liefern fertige Bausteine für jeden Schritt. In Genesys übernimmt die Knowledge-Funktion vieles davon im Hintergrund.",
    "Wichtig ist, jeden Schritt einzeln gut zu machen - die schwächste Stelle bestimmt die Qualität (schlechtes Chunking verdirbt auch das beste LLM).",
    "In der Bank achtet man zusätzlich auf: EU-/On-Prem-Betrieb, Zugriffsrechte (wer darf welches Wissen sehen) und Protokollierung (Audit)."),
  S("Konkretes Beispiel",
    "Ein neues Preisverzeichnis erscheint: Phase 1 läuft automatisch (laden, chunken, einbetten, speichern). Ab sofort liefert Phase 2 bei jeder Preisfrage die aktuelle Antwort - ohne dass das Modell neu trainiert werden musste."),
  S("Grenzen & typische Fehler",
    "Nur ein Schritt schlecht (z.B. Chunking) - und die ganze Kette liefert schlechte Antworten.",
    "Kein Re-Ranking/Filter bei vielen Treffern - das LLM bekommt Unpassendes.",
    "Keine Rechte-Trennung: der Bot zeigt Wissen, das der Nutzer nicht sehen darf.",
    "Kein Monitoring - Qualität sinkt unbemerkt (siehe RAG Monitoring/Evaluation)."),
  S("So lernst du weiter",
    "Setzt alle Einzelteile zusammen: Embeddings, Vector Search, Chunking, Hybrid Search - und führt zu RAG Evaluation und RAG Monitoring. Die Fraunhofer- und virtido-Leitfäden unten zeigen die Architektur im Zusammenhang."),
 ],
}

# ===========================================================================
AI_DEEP["RAG Evaluation"] = {
 "web": [
   ("codecentric: RAG Evaluation (Praxis)", "https://www.codecentric.de/wissens-hub/blog/genai-fuer-full-stack-entwicklerinnen-rag-evaluation-mit-typescript-teil-3"),
   ("IT Sonix: RAG-Systeme im Praxis-Test", "https://www.itsonix.eu/de/blog/25092025-rag-systeme-im-praxis-test-von-ersten-erfolgen-zu-nachhaltiger-qualitaet"),
   ("Ragas (GitHub) - RAG-Evaluation-Framework", "https://github.com/explodinggradients/ragas"),
   ("Deepchecks: RAG Evaluation Metrics", "https://deepchecks.com/rag-evaluation-metrics-answer-relevancy-faithfulness-accuracy/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "RAG Evaluation heißt: systematisch messen, ob euer Wissens-Bot gute Antworten gibt. Nicht 'gefühlt gut', sondern mit klaren Kennzahlen und Testfragen.",
    "Man prüft dabei zwei Dinge getrennt: Hat die Suche das richtige Wissen gefunden (Retrieval)? Und hat die KI daraus eine korrekte, belegte Antwort gemacht (Generation)?"),
  S("Die wichtigsten Metriken",
    "Faithfulness (Treue): Bleibt die Antwort wirklich beim gefundenen Kontext oder erfindet sie dazu? Zentrale Metrik gegen Halluzinationen.",
    "Answer Relevancy: Passt die Antwort zur Frage?",
    "Context Recall/Precision: Wurde das relevante Wissen gefunden - und ohne zu viel Unpassendes?",
    "Retrieval-Kennzahlen wie Hit Rate und Mean Reciprocal Rank zeigen, ob und an welcher Stelle die richtige Quelle gefunden wurde."),
  S("Wie man es einsetzt (Praxis)",
    "Man legt ein Test-Set mit echten Fragen und den erwarteten (richtigen) Antworten/Quellen an. Damit misst man automatisch bei jeder Änderung, ob der Bot besser oder schlechter wird.",
    "Ein beliebtes, kostenloses Framework ist Ragas (Faithfulness, Answer Relevancy, Context Recall). Verbreitet ist auch 'LLM-as-a-Judge': Ein starkes LLM bewertet die Antworten nach festen Kriterien - günstiger als reine Handarbeit.",
    "In der Bank ist das Pflicht: Man muss nachweisen können, dass Auskünfte korrekt und belegt sind - für Qualität und Aufsicht."),
  S("Konkretes Beispiel",
    "Nach einer Änderung am Chunking steigt die Antwortqualität im Test scheinbar. Die Evaluation zeigt aber: Faithfulness ist gesunken - die KI erfindet jetzt mehr. So erkennt man das Problem VOR dem Live-Gang, nicht erst beim Kunden."),
  S("Grenzen & typische Fehler",
    "Kein Test-Set: Man 'fühlt' Qualität, statt sie zu messen - der häufigste Fehler.",
    "Nur die Endantwort prüfen: Dann weiß man nicht, ob Suche oder Formulierung schuld ist (getrennt messen!).",
    "Einmal evaluieren und nie wieder: Qualität driftet mit neuen Daten/Fragen.",
    "'LLM-as-a-Judge' blind vertrauen - auch der Judge kann irren; stichprobenhaft von Menschen prüfen lassen."),
  S("So lernst du weiter",
    "Gehört zu RAG Architektur und führt zu RAG Monitoring (dasselbe im Live-Betrieb). Die codecentric- und IT-Sonix-Texte unten zeigen Evaluation in der Praxis; Ragas ist das Werkzeug zum Selbermachen."),
 ],
}

# ===========================================================================
AI_DEEP["Hybrid Search"] = {
 "web": [
   ("Elastic: Hybrid Search", "https://www.elastic.co/de/what-is/hybrid-search"),
   ("Google Cloud: Vektordatenbank & Suche", "https://cloud.google.com/discover/what-is-a-vector-database"),
   ("Data Basecamp: Vector Database & Suche", "https://databasecamp.de/daten/vector-database"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Hybrid Search kombiniert zwei Suchen: die klassische Wortsuche (Keyword) und die Bedeutungssuche (semantisch/Vector). Zusammen sind sie treffsicherer als jede für sich.",
    "Die Idee: Die Wortsuche ist stark bei exakten Begriffen, Namen und Nummern; die semantische Suche ist stark bei Formulierungen und Synonymen. Hybrid nimmt das Beste aus beiden."),
  S("Wie es funktioniert",
    "Das System führt beide Suchen parallel aus und mischt die Ergebnisse zu einer gemeinsamen Rangliste (oft mit einem Verfahren wie Reciprocal Rank Fusion).",
    "So landen sowohl exakt passende Treffer (z.B. eine bestimmte Produktbezeichnung) als auch bedeutungsähnliche Treffer (andere Wortwahl) weit oben."),
  S("Wie man es einsetzt (Praxis)",
    "Hybrid Search ist in vielen Suchsystemen (z.B. Elasticsearch/OpenSearch) direkt eingebaut und in RAG oft die beste Standardwahl.",
    "Besonders wertvoll in Bereichen mit vielen exakten Begriffen und Codes - genau wie in Banken (IBANs, Produktnamen, Paragraphen, Vertragsnummern) neben umgangssprachlichen Kundenfragen.",
    "Man kann die Gewichtung einstellen: mehr Gewicht auf exakt (bei Codes) oder auf semantisch (bei freien Fragen)."),
  S("Konkretes Beispiel",
    "Ein Kunde fragt 'Gebühren beim Tarif Giro Plus'. Die semantische Suche versteht 'Gebühren', die Wortsuche trifft exakt den Produktnamen 'Giro Plus'. Hybrid liefert genau den richtigen Abschnitt - reine Semantik hätte den exakten Tarifnamen evtl. verwässert."),
  S("Grenzen & typische Fehler",
    "Die Gewichtung muss zur Domäne passen - falsch eingestellt verschlechtert Hybrid die Treffer.",
    "Etwas mehr Aufwand als eine einzelne Suche (zwei Indizes/Verfahren).",
    "Ersetzt kein gutes Chunking/Embedding - baut darauf auf.",
    "An echten Fragen testen (benchmarken), statt die Gewichte zu raten."),
  S("So lernst du weiter",
    "Direkt verwandt: Semantic Search, Vector Search, Embeddings - und Teil der RAG Architektur. Der Elastic-Text unten erklärt Hybrid Search einsteigerfreundlich auf Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["RAG Monitoring"] = {
 "web": [
   ("Langfuse (GitHub) - LLM/RAG Observability", "https://github.com/langfuse/langfuse"),
   ("IT Sonix: RAG-Systeme - nachhaltige Qualität", "https://www.itsonix.eu/de/blog/25092025-rag-systeme-im-praxis-test-von-ersten-erfolgen-zu-nachhaltiger-qualitaet"),
   ("Fraunhofer IESE: RAG in der Praxis", "https://www.iese.fraunhofer.de/blog/retrieval-augmented-generation-rag/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "RAG Monitoring heißt: den Wissens-Bot im laufenden Betrieb überwachen. RAG Evaluation prüft VOR dem Live-Gang mit Testfragen; Monitoring beobachtet DANACH, was echte Nutzer erleben.",
    "Ein Bot ist nie 'fertig': Nutzer stellen neue Fragen, Dokumente veralten, die Qualität kann leise abrutschen. Monitoring macht das sichtbar, bevor Kunden sich beschweren."),
  S("Was man überwacht",
    "Qualität: Wie oft findet die Suche nichts Passendes? Wie oft bewerten Nutzer die Antwort schlecht (Daumen runter)?",
    "Nutzung: Welche Fragen kommen am häufigsten? Wo bricht der Bot ab, wo wird an Menschen übergeben?",
    "Technik & Kosten: Antwortzeit, Fehler, Token-Verbrauch/Kosten.",
    "Sicherheit: verdächtige Eingaben (mögliche Prompt Injection)."),
  S("Wie man es einsetzt (Praxis)",
    "Man baut Feedback direkt ein (Daumen hoch/runter, 'War das hilfreich?') und protokolliert anonymisiert, welche Fragen zu 'nichts gefunden' führen - das sind die Wissenslücken, die man schließt.",
    "Werkzeuge wie Langfuse zeichnen jede Anfrage mit gefundenen Chunks, Antwort und Bewertung auf (Tracing/Observability). So sieht man genau, WO es hakt (Suche oder Formulierung).",
    "In der Bank kommt Audit-Logging dazu: Wer hat wann welche Auskunft bekommen - wichtig für Aufsicht und Nachvollziehbarkeit. Dabei Datenschutz beachten (PII sparsam, sicher speichern)."),
  S("Konkretes Beispiel",
    "Das Monitoring zeigt: Seit Montag häufen sich Fragen zu einem neuen Tagesgeld-Angebot, und der Bot findet nichts. Ursache: Der Artikel fehlt noch. Man pflegt ihn nach - und die 'nichts gefunden'-Rate für dieses Thema fällt sofort."),
  S("Grenzen & typische Fehler",
    "Kein Feedback-Knopf: Man erfährt nie, was Nutzer wirklich schlecht fanden.",
    "Nur Technik überwachen (läuft/schnell), aber nicht die Antwortqualität.",
    "Logs mit sensiblen Daten unsicher speichern - Datenschutzproblem.",
    "Daten sammeln, aber nie auswerten und nachbessern."),
  S("So lernst du weiter",
    "Bildet mit RAG Evaluation ein Paar (vorher/nachher) und verwandt mit AI Model Monitoring und Observability. Langfuse (unten) ist ein verbreitetes, offenes Werkzeug dafür."),
 ],
}

# ===========================================================================
AI_DEEP["Knowledge Graphs"] = {
 "web": [
   ("IBM: What is a Knowledge Graph?", "https://www.ibm.com/think/topics/knowledge-graph"),
   ("plusmeta: Knowledge Graphen - smarte Verbindung von Daten", "https://www.plusmeta.de/blog/knowledge-graphen/"),
   ("SAP News: Knowledge Graphs - vernetztes Wissen", "https://news.sap.com/germany/2023/05/knowledge-graphs-vernetztes-wissen/"),
   ("Neo4j (GitHub) - Graphdatenbank", "https://github.com/neo4j/neo4j"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein Knowledge Graph (Wissensgraph) ist ein Netz aus Fakten und ihren Verbindungen. Er speichert nicht nur Dinge, sondern auch, wie sie zusammenhängen: 'Kunde -besitzt-> Konto -gehört zu-> Filiale'.",
    "Man stellt sich Punkte (Knoten/Entitäten: Kunde, Konto, Karte) und Linien dazwischen (Kanten/Beziehungen: besitzt, gehört zu) vor. Anders als eine normale Tabelle 'versteht' der Graph diese Beziehungen."),
  S("Wie es funktioniert",
    "Entitäten sind die Knoten, Beziehungen die Kanten. Beides wird in einer Graphdatenbank (z.B. Neo4j) gespeichert und lässt sich als Netz darstellen.",
    "Dadurch kann man Fragen beantworten, die über mehrere Ecken gehen: 'Welche Kunden mit Karte X hatten auch Kontakt zu Händler Y?' - das ist in einem Graphen viel natürlicher als in getrennten Tabellen."),
  S("Wie man es einsetzt (Praxis)",
    "Laut den Fachquellen sind typische Einsätze: Wissensmanagement (internes Wissen vernetzen), intelligente Assistenten/Chatbots (bessere Antworten durch verknüpftes Wissen), Empfehlungssysteme und Betrugserkennung.",
    "In der KI-Welt kombiniert man Knowledge Graphs zunehmend mit RAG ('GraphRAG'): Statt nur ähnliche Textstücke zu finden, nutzt man auch die Beziehungen - das macht Antworten präziser bei vernetzten Fragen.",
    "In der Bank stark bei Betrug: Ein Graph zeigt verdächtige Ringe (mehrere Konten, dasselbe Gerät, gleiche Adresse), die in einzelnen Tabellen unsichtbar bleiben. Auch für Geldwäsche-Prüfung (AML) genutzt."),
  S("Konkretes Beispiel",
    "Betrugsring-Erkennung: Fünf scheinbar fremde Konten hängen im Graphen über dasselbe Gerät und dieselbe Telefonnummer zusammen. Der Graph macht diese verborgene Verbindung sichtbar - und der Betrugsring fliegt auf."),
  S("Grenzen & typische Fehler",
    "Aufbau und Pflege sind aufwendig: Man muss festlegen, welche Entitäten und Beziehungen es gibt (Ontologie).",
    "Schlechte/veraltete Daten führen zu falschen Verbindungen.",
    "Nicht für jedes Problem nötig - bei einfachem Text-Wissen reicht oft normales RAG.",
    "Datenschutz: Ein Graph verknüpft Personendaten stark - das ist sensibel (DSGVO)."),
  S("So lernst du weiter",
    "Verwandt mit RAG (GraphRAG), Semantic Search und AI Fraud Detection. Der IBM- und plusmeta-Text unten erklären Knowledge Graphs anschaulich; Neo4j ist die bekannteste Graphdatenbank zum Ausprobieren."),
 ],
}

# ===========================================================================
AI_DEEP["Supervised Learning"] = {
 "web": [
   ("datasolut Wiki: Supervised Learning", "https://datasolut.com/wiki/supervised-learning/"),
   ("mindsquare: Supervised & Unsupervised Learning", "https://mindsquare.de/fachartikel/kuenstliche-intelligenz/supervised-und-unsupervised-learning-mit-diesen-beiden-methoden-funktioniert-machine-learning/"),
   ("datenverstehen.de: Supervised vs Unsupervised", "https://datenverstehen.de/ml-algorithmen-unsupervised-supervised-learning/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Supervised Learning (überwachtes Lernen) ist Lernen mit Lösung: Jedes Beispiel im Trainingsdatensatz hat die richtige Antwort (Zielvariable/Label) schon dabei. Das Modell lernt, aus den Eingaben genau diese Antwort vorherzusagen.",
    "Es ist die häufigste ML-Art im Geschäftsalltag - wie ein Schüler, der mit Aufgabe UND Musterlösung übt."),
  S("Wie es funktioniert",
    "Man zeigt dem Modell viele Paare aus Eingabe (Features) und richtiger Antwort (Label). Das Modell rät, vergleicht mit der Lösung und korrigiert sich - tausendfach.",
    "Danach kann es die Antwort auch für neue, ungesehene Fälle geben. Zwei Grundformen: Klassifikation (Kategorie vorhersagen, z.B. Betrug ja/nein) und Regression (Zahl vorhersagen, z.B. erwarteter Umsatz)."),
  S("Wie man es einsetzt (Praxis in der Bank)",
    "Überall dort, wo man aus der Vergangenheit gelabelte Fälle hat: Kreditbewilligung (Bonität aus alten Fällen), Betrugserkennung (Transaktion Betrug/kein Betrug), E-Mails der richtigen Abteilung zuordnen, Kündigungswahrscheinlichkeit schätzen.",
    "Wichtig: Die Qualität der Labels entscheidet alles. Falsch gelabelte Trainingsdaten bringen dem Modell Falsches bei.",
    "Bei Kredit ist Vorsicht geboten: laut EU AI Act Hochrisiko - erklärbar, fair und mit menschlicher Letztentscheidung."),
  S("Konkretes Beispiel",
    "Kredit-Scoring: Man nimmt 100.000 alte Kredite, jeweils mit dem Ausgang 'zurückgezahlt' oder 'ausgefallen' (das Label). Das Modell lernt die Muster und schätzt bei einem neuen Antrag die Ausfallwahrscheinlichkeit. Ein Mensch entscheidet final."),
  S("Grenzen & typische Fehler",
    "Braucht viele, saubere, korrekt gelabelte Daten - Labeln ist oft teuer.",
    "Bias: Waren die alten Entscheidungen unfair, lernt das Modell die Unfairness mit.",
    "Mit Trainingsdaten testen (statt separater Testdaten) täuscht gute Ergebnisse vor.",
    "Nur auf Accuracy schauen - bei seltenen Fällen irreführend (Precision/Recall nutzen)."),
  S("So lernst du weiter",
    "Gegenstück: Unsupervised Learning. Verwandt: Features & Labels, Klassifikation vs Regression, Metriken. Die datasolut- und mindsquare-Texte unten vertiefen es auf Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Unsupervised Learning"] = {
 "web": [
   ("datasolut Wiki: Unsupervised Learning", "https://datasolut.com/wiki/unsupervised-learning/"),
   ("datenverstehen.de: Supervised vs Unsupervised", "https://datenverstehen.de/ml-algorithmen-unsupervised-supervised-learning/"),
   ("tecislava: Supervised, Unsupervised, Reinforcement", "https://www.tecislava.com/blog/supervised-unsupervised-reinforcement"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Unsupervised Learning (unüberwachtes Lernen) ist Lernen ohne Lösung: Die Daten haben keine vorgegebene richtige Antwort (kein Label). Das Modell erkundet die Daten selbst und findet Muster oder Gruppen.",
    "Man setzt es ein, wenn man die Antwort noch gar nicht kennt und erst verstehen will, was in den Daten steckt."),
  S("Wie es funktioniert",
    "Das Modell bekommt nur Eingaben und sucht Struktur. Die wichtigste Form ist Clustering: ähnliche Datenpunkte werden zu Gruppen zusammengefasst (z.B. mit k-Means).",
    "Weitere Formen: Dimensionsreduktion (viele Merkmale auf wenige wichtige eindampfen) und Anomalie-Erkennung (Ausreißer finden, die aus dem Muster fallen)."),
  S("Wie man es einsetzt (Praxis in der Bank)",
    "Kundensegmentierung: Kunden automatisch in Typen einteilen ('junge Sparer', 'aktive Anleger'), ohne die Gruppen vorzugeben - Basis für gezieltes Marketing.",
    "Anomalie-Erkennung: ungewöhnliche Transaktionen auffällig machen - nützlich bei Betrug, gerade wenn man kein Label 'Betrug' hat.",
    "Datenverständnis: Bevor man ein Supervised-Modell baut, hilft Unsupervised, die Daten überhaupt erst zu durchschauen."),
  S("Konkretes Beispiel",
    "Ein Clustering über das Zahlungsverhalten findet von selbst eine kleine Gruppe mit sehr untypischem Muster (viele kleine Auslandszahlungen nachts). Diese Gruppe schaut man sich dann gezielt auf Betrug/Geldwäsche an."),
  S("Grenzen & typische Fehler",
    "Ergebnisse sind schwerer zu bewerten: Es gibt keine 'richtige' Antwort zum Vergleichen.",
    "Die gefundenen Gruppen muss ein Mensch interpretieren - sie sind nicht automatisch sinnvoll.",
    "Man muss oft die Anzahl der Gruppen vorgeben (z.B. bei k-Means) - falsch gewählt, schlechte Cluster.",
    "Nicht mit Supervised verwechseln: Ohne Label kann man nichts Konkretes 'vorhersagen'."),
  S("So lernst du weiter",
    "Gegenstück: Supervised Learning. Verwandt: AI Fraud Detection (Anomalien), Recommendation Systems, Kundensegmentierung. Die datasolut-Quelle unten erklärt Clustering & Co. auf Deutsch."),
 ],
}

# ===========================================================================
AI_DEEP["Overfitting & Underfitting"] = {
 "web": [
   ("mindsquare: Overfitting und Underfitting", "https://mindsquare.de/knowhow/overfitting-und-underfitting-im-machine-learning/"),
   ("StudySmarter: Overfitting und Underfitting", "https://www.studysmarter.de/studium/informatik-studium/kuenstliche-intelligenz-studium/overfitting-und-underfitting/"),
   ("artemoppermann: Overfitting/Underfitting in Deep Learning", "https://artemoppermann.com/de/overfitting-und-underfitting-in-deep-learning/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Overfitting (Überanpassung) heißt: Das Modell lernt die Trainingsbeispiele quasi auswendig, statt das allgemeine Muster zu verstehen - und versagt bei neuen Daten. Underfitting (Unteranpassung) heißt: Das Modell ist zu simpel und erkennt das Muster gar nicht erst.",
    "Ziel ist die goldene Mitte: ein Modell, das gut verallgemeinert - also auch bei echten, neuen Fällen gut liegt."),
  S("Wie man es erkennt",
    "Overfitting: sehr guter Wert auf Trainingsdaten, aber schlechter auf Testdaten. Klassisches Warnzeichen: 99 % im Training, 60 % im Test.",
    "Underfitting: schlechte Werte auf BEIDEN - Training UND Test. Das Modell ist zu einfach.",
    "Deshalb prüft man immer getrennt mit Testdaten, die das Modell nie gesehen hat."),
  S("Wie man es vermeidet (Praxis)",
    "Gegen Overfitting (laut den Fachquellen): mehr/vielfältigere Daten, einfacheres Modell, Cross-Validation, Regularisierung (L1/L2) und - in neuronalen Netzen - Dropout.",
    "Gegen Underfitting: komplexeres Modell, mehr aussagekräftige Features, länger trainieren, bessere Architektur.",
    "In der Bank ist Overfitting besonders tückisch: Ein Betrugsmodell, das die alten Fälle auswendig kann, erkennt neue Betrugsmaschen nicht - genau die aber zählen."),
  S("Konkretes Beispiel",
    "Ein Kredit-Modell trifft die Trainingsfälle zu 99 % - im Test aber nur 62 %. Es hat die alten Kunden 'auswendig gelernt'. Man vereinfacht das Modell und holt mehr Daten; danach: 84 % im Training, 82 % im Test - viel gesünder, weil es verallgemeinert."),
  S("Grenzen & typische Fehler",
    "Nur den Trainingswert ansehen und sich freuen - der klassische Anfängerfehler.",
    "Kein sauberer Test-Split (dann merkt man Overfitting nicht).",
    "Modell immer komplexer machen 'für mehr Genauigkeit' - führt oft direkt ins Overfitting.",
    "Zu wenige Daten für ein zu großes Modell."),
  S("So lernst du weiter",
    "Direkt verwandt: Trainings-/Test-Daten, Cross-Validation, Metriken und (im Deep Learning) Dropout. Die mindsquare- und StudySmarter-Texte unten erklären beides mit Bildern."),
 ],
}

# ===========================================================================
AI_DEEP["Modell-Metriken: Accuracy, Precision, Recall, F1"] = {
 "web": [
   ("ki.engineering: Präzision & Recall", "https://ki.engineering/glossar/praezision-recall/"),
   ("ki.engineering: F1-Score erklärt", "https://ki.engineering/glossar/f1-score-harmonisches-mittel-aus-praezision-und-recall/"),
   ("artemoppermann: Accuracy, Precision, Recall, F1", "https://artemoppermann.com/de/accuracy-precision-recall-f1-score-und-specificity/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Metriken sind Zahlen, die messen, wie gut ein Modell ist. Die bekannteste, Accuracy (Genauigkeit), reicht oft nicht - besonders bei seltenen Ereignissen wie Betrug. Dann braucht man Precision, Recall und F1.",
    "Kurz: Accuracy = Anteil insgesamt richtig. Precision = wie viele der Alarme stimmten. Recall = wie viele der echten Fälle wurden gefunden. F1 = fairer Mix aus beiden."),
  S("Warum Accuracy täuscht (das Betrugs-Beispiel)",
    "Nur 0,1-0,5 % aller Kartenzahlungen sind betrügerisch. Ein Modell, das IMMER 'kein Betrug' sagt, hat 99,5-99,9 % Accuracy - und ist völlig nutzlos, weil es keinen einzigen Betrug findet.",
    "Genau deshalb schaut man bei seltenen, wichtigen Fällen nicht auf Accuracy, sondern auf Precision und Recall."),
  S("Precision, Recall und F1 verstehen",
    "Precision (Präzision): Von allen als 'Betrug' markierten Fällen - wie viele waren wirklich Betrug? Hoch = wenige Fehlalarme.",
    "Recall (Trefferquote): Von allen echten Betrugsfällen - wie viele hat das Modell erwischt? Hoch = wenig übersehen.",
    "Es gibt einen Zielkonflikt: Mehr Recall (alles melden) senkt oft die Precision (mehr Fehlalarme) - und umgekehrt.",
    "F1 = harmonisches Mittel aus beiden: 2 × (Precision × Recall) / (Precision + Recall). Gut, wenn man beides ausbalancieren will."),
  S("Wie man es einsetzt (Praxis)",
    "Man wählt die Metrik nach dem Schaden des jeweiligen Fehlers: Ist ein übersehener Betrug schlimmer als ein Fehlalarm? Dann Recall priorisieren (lieber ein paar Kunden mit falschem Alarm nerven als großen Betrug verpassen).",
    "Sind Fehlalarme sehr teuer/störend (z.B. gesperrte Karten im Urlaub)? Dann Precision höher gewichten.",
    "In der Bank stimmt man diese Schwelle bewusst mit den Fachbereichen ab - es ist eine Geschäfts-, nicht nur eine Technik-Entscheidung."),
  S("Konkretes Beispiel",
    "Betrugsmodell A: Precision 90 %, Recall 30 % - meldet selten, aber wenn, dann meist richtig (übersieht aber 70 % der Betrüge). Modell B: Precision 40 %, Recall 85 % - fängt fast alles, aber mit vielen Fehlalarmen. Welches besser ist, hängt davon ab, was teurer ist - übersehener Betrug oder Fehlalarm."),
  S("Grenzen & typische Fehler",
    "Sich von hoher Accuracy blenden lassen (der häufigste Fehler bei seltenen Ereignissen).",
    "Nur eine Metrik betrachten - immer im Zusammenhang lesen.",
    "Die Schwelle rein technisch setzen, ohne die Fachbereiche und Kosten einzubeziehen.",
    "Confusion Matrix ignorieren - sie zeigt, welche Art Fehler passiert."),
  S("So lernst du weiter",
    "Direkt verwandt: Confusion Matrix, Klassifikation, RAG Evaluation (nutzt Precision/Recall beim Retrieval). Die ki.engineering-Texte unten erklären die Metriken einsteigerfreundlich."),
 ],
}

# ===========================================================================
AI_DEEP["Neuronales Netz: Aufbau"] = {
 "web": [
   ("IBM: Was sind neuronale Netze?", "https://www.ibm.com/de-de/think/topics/neural-networks"),
   ("3Blue1Brown: Neural Networks (visuell, engl.)", "https://www.3blue1brown.com/topics/neural-networks"),
   ("Alexander Thamm: Deep Learning / Neuronale Netze", "https://www.alexanderthamm.com/de/blog/large-language-models-eine-einfuehrung/"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Ein neuronales Netz ist der Grundbaustein von Deep Learning - lose dem Gehirn nachempfunden. Es besteht aus vielen kleinen Recheneinheiten (Neuronen), die in Schichten (Layers) angeordnet sind. Daten fließen vorne rein und ein Ergebnis kommt hinten raus.",
    "Man muss es nicht als Biologie verstehen: Es ist im Kern eine Kette aus vielen kleinen Rechenschritten, die zusammen erstaunlich Komplexes lernen können."),
  S("Der Aufbau (Schichten)",
    "Input Layer: nimmt die Eingabedaten auf (z.B. die Pixel eines Bildes oder die Merkmale eines Kunden).",
    "Hidden Layers: die 'Denk-Schichten' dazwischen. Jede verarbeitet die Info ein Stück weiter und abstrakter. 'Deep' heißt: viele solcher Schichten.",
    "Output Layer: gibt das Ergebnis aus (z.B. 'Katze zu 97 %' oder 'Betrug zu 88 %').",
    "Die Neuronen sind über Gewichte verbunden - Zahlen, die sagen, wie wichtig eine Verbindung ist. Eine Aktivierungsfunktion entscheidet, ob ein Neuron 'feuert'."),
  S("Wie es lernt (ganz kurz)",
    "Das 'Wissen' des Netzes steckt in den Gewichten. Beim Training rät das Netz, vergleicht mit der richtigen Antwort (Loss), und passt die Gewichte ein winziges Stück an (über Backpropagation und Gradient Descent) - millionenfach.",
    "So werden aus anfangs zufälligen Zahlen nach und nach Gewichte, die gute Vorhersagen liefern."),
  S("Wie man es einsetzt (Praxis)",
    "Neuronale Netze sind stark bei komplexen Daten: Bilder (CNN), Sprache/Text (Transformer), Ton. In der Bank z.B. für Dokumentenerkennung, Sprachbots und anspruchsvolle Betrugsmuster.",
    "Für einfache, tabellarische Daten (Zeilen/Spalten) sind klassische ML-Modelle (z.B. Random Forest) oft gleich gut oder besser - und leichter erklärbar. Man wählt das Werkzeug nach dem Problem.",
    "Man baut Netze nicht von Hand, sondern mit Frameworks wie PyTorch/TensorFlow, die die Mathematik automatisch erledigen."),
  S("Konkretes Beispiel",
    "Gesichtserkennung im Ausweis-Check: Die erste Schicht erkennt Kanten, spätere Schichten Augen/Nase, die letzte 'Gesicht ja/nein bzw. passt zum Foto'. Jede Schicht baut auf der vorherigen auf."),
  S("Grenzen & typische Fehler",
    "Brauchen viele Daten und Rechenleistung (GPUs) - teurer als klassische ML.",
    "Sind eine 'Blackbox': schwer zu erklären, warum sie so entscheiden (Problem bei Aufsicht - siehe Explainability).",
    "Neigen zu Overfitting, wenn Daten knapp sind (Gegenmittel: Dropout, mehr Daten).",
    "Nicht für jedes Problem nötig - bei einfachen Tabellen oft Overkill."),
  S("So lernst du weiter",
    "Direkt danach im Plan: Gewichte & Aktivierungsfunktion, Loss & Training, Backpropagation, dann CNN/RNN und Transformer. Die IBM-Seite und 3Blue1Brown (unten) erklären den Aufbau sehr anschaulich."),
 ],
}

# ===========================================================================
AI_DEEP["Attention Mechanism"] = {
 "web": [
   ("Der Transformer illustriert (deutsch)", "https://www.michaelkipp.de/deeplearning/Transformer-illustriert.html"),
   ("Wikipedia (DE): Transformer (Maschinelles Lernen)", "https://de.wikipedia.org/wiki/Transformer_(Maschinelles_Lernen)"),
   ("Attention Is All You Need (Original-Paper)", "https://arxiv.org/abs/1706.03762"),
 ],
 "lang": [
  S("Einfach gesagt",
    "Attention ('Aufmerksamkeit') ist der Kern-Trick, der moderne Sprach-KI so gut macht. Sie lässt das Modell für jedes Wort entscheiden: Auf welche anderen Wörter im Satz muss ich achten, um dich richtig zu verstehen?",
    "Statt jedes Wort isoliert zu betrachten, verbindet Attention die Wörter, die zusammengehören - auch wenn sie weit auseinanderstehen."),
  S("Wie es funktioniert (einfach)",
    "Für jedes Wort berechnet das Modell, wie stark es auf jedes andere Wort 'schauen' soll (ein Gewicht). Wichtige Bezüge bekommen viel Aufmerksamkeit, unwichtige wenig.",
    "So löst Attention die klassische Frage 'Wer/was ist gemeint?': Sie verknüpft z.B. ein 'sie' oder 'das' mit dem richtigen Bezugswort.",
    "Attention ist der Baustein, aus dem der Transformer besteht - und damit die Grundlage aller großen Sprachmodelle."),
  S("Wie man es einsetzt (Praxis)",
    "Als Anwender baust du Attention nicht selbst - sie steckt fertig in jedem LLM. Aber sie zu verstehen erklärt, WARUM LLMs Zusammenhänge im Text so gut erfassen.",
    "Praktische Folge: Weil das Modell den ganzen Kontext gewichtet, ist es sehr wichtig, WELCHEN Kontext du mitgibst (siehe Context Engineering) - relevante Infos bekommen zu Recht Aufmerksamkeit, Müll lenkt ab.",
    "Attention steckt heute auch in Bild- und Multimodal-Modellen."),
  S("Konkretes Beispiel",
    "Satz: 'Anna gab Lisa ihr Buch, weil sie es liebte.' Attention hilft dem Modell, 'sie' und 'ihr' den richtigen Personen zuzuordnen und 'es' auf 'Buch' zu beziehen - genau das, woran ältere Modelle oft scheiterten."),
  S("Grenzen & Einordnung",
    "Attention über sehr lange Texte ist rechenintensiv (Kosten steigen stark mit der Länge) - ein Grund für Token-Limits.",
    "Attention erklärt nicht automatisch, dass eine Antwort WAHR ist - sie ordnet nur Zusammenhänge; Halluzinationen bleiben möglich.",
    "Für den Einsatz zählt weniger die Mathematik als das Prinzip: relevanter Kontext bekommt Aufmerksamkeit."),
  S("So lernst du weiter",
    "Gehört untrennbar zum Transformer (davor) und erklärt LLM-Verhalten. Der bebilderte deutsche Text 'Der Transformer illustriert' unten macht Attention besonders anschaulich."),
 ],
}
