# -*- coding: utf-8 -*-
"""
Baut die Lerndaten (curriculum.js) fuer die Lern-App.
Sprache: sehr einfaches Deutsch. IT-Begriffe bleiben in Originalsprache (Englisch).
Reihenfolge: didaktisch sortiert - was man zuerst koennen muss, kommt zuerst.
"""
import json, os, datetime

# ---------------------------------------------------------------------------
# Hilfsfunktion: ein Thema anlegen
# t   = Titel
# was = "Was ist das?" in sehr einfachem Deutsch
# pts = Unterpunkte (Liste)
# yt  = YouTube-Suchbegriff
# src = offizielle Quelle (Titel, URL)
# gh  = GitHub-Bibliotheken [(Titel, URL)]
# art = Artikel/Studien [(Titel, URL)]
# ---------------------------------------------------------------------------
def T(t, was, pts, yt, src=None, gh=None, art=None):
    return {"t": t, "was": was, "pts": pts, "yt": yt,
            "src": src, "gh": gh or [], "art": art or []}

MODULES = []
def M(title, emoji, ziel, topics):
    MODULES.append({"title": title, "emoji": emoji, "ziel": ziel, "topics": topics})

# Kurzlinks (offizielle Quellen)
G_HELP   = "https://help.mypurecloud.com/"
G_DEV    = "https://developer.genesys.cloud/"
G_BEYOND = "https://beyond.genesys.com/explore"
G_RES    = "https://www.genesys.com/resources"
G_KNOW   = "https://help.mypurecloud.com/articles/about-genesys-knowledge/"
EU_ACT   = "https://artificialintelligenceact.eu/de/"
DSGVO    = "https://dsgvo-gesetz.de/"
BAFIN    = "https://www.bafin.de/DE/Aufsicht/FinTech/KuenstlicheIntelligenz/kuenstliche_intelligenz_node.html"
OWASP    = "https://genai.owasp.org/llm-top-10/"

# ===========================================================================
# MODUL 1 - Fundament: Bank & Contact Center
# ===========================================================================
M("Fundament: Bank & Contact Center", "🏦",
  "Verstehen, wie ein Bank-Callcenter arbeitet und warum Regeln wichtig sind.",
[
 T("Bank Contact Center Grundmodell",
   "Ein Contact Center ist die Telefon- und Chat-Zentrale einer Bank. Hier landen Anrufe, Chats und E-Mails von Kunden, und Mitarbeiter (Agents) helfen weiter.",
   ["Kanaele: Telefon (Voice), Chat, E-Mail, Messaging",
    "Agent = Mitarbeiter, der Kunden hilft",
    "Ziel: Kunde schnell und richtig zum passenden Agent bringen",
    "Bank-Besonderheit: sehr strenge Sicherheits- und Datenschutz-Regeln"],
   "Contact Center Grundlagen einfach erklaert", ("Genesys: Was ist ein Contact Center", "https://www.genesys.com/de/definitionen/was-ist-ein-contact-center")),
 T("Bankprozesse und Risikodenken",
   "Banken denken immer an Risiko: Was kann schiefgehen? Jeder Prozess hat Regeln, damit kein Geld verloren geht und kein Betrug passiert.",
   ["Prozess = fester Ablauf mit Schritten (z.B. Kredit beantragen)",
    "Risiko = Gefahr eines Schadens (Geld, Vertrauen, Recht)",
    "Compliance = Einhaltung von Gesetzen und Regeln",
    "Vier-Augen-Prinzip: wichtige Dinge pruefen zwei Personen"],
   "Risikomanagement Bank einfach erklaert",
   ("BaFin: Aufsicht & Risiko", "https://www.bafin.de/"),
   art=[("BaFin: KI in der Finanzwirtschaft", BAFIN)]),
 T("Routing-Grundlagen",
   "Routing bedeutet 'Wegfindung'. Das System entscheidet, welcher Anruf zu welchem Agent geht - so wie eine Post die Briefe sortiert.",
   ["Routing = Verteilen von Anrufen/Chats an den richtigen Ort",
    "Regeln entscheiden: wer, wann, wohin",
    "Ziel: kurze Wartezeit und passender Ansprechpartner",
    "ACD (Automatic Call Distribution) = automatische Verteilung"],
   "Contact Center Routing explained", (G_HELP + "articles/about-routing/", None)),
 T("Queues und Skills",
   "Eine Queue ist eine Warteschlange, wie an der Kasse. Skills sind Faehigkeiten eines Agents, z.B. 'spricht Tuerkisch' oder 'kennt Kredite'.",
   ["Queue = Warteschlange fuer wartende Kunden",
    "Skill = Faehigkeit/Kenntnis eines Agents",
    "Skill-based Routing: Kunde geht zum Agent mit dem passenden Skill",
    "Beispiel: Kreditfrage -> Queue 'Kredit' -> Agent mit Skill 'Kredit'"],
   "Genesys queues and skills explained", (G_HELP + "articles/about-queues/", None)),
 T("DNIS und ANI",
   "ANI ist die Nummer des Anrufers (wer ruft an). DNIS ist die gewaehlte Nummer (welche Nummer wurde angerufen). Beides hilft beim Sortieren.",
   ["ANI = Automatic Number Identification = Rufnummer des Kunden",
    "DNIS = Dialed Number Identification Service = angewaehlte Nummer",
    "Nutzen: an DNIS erkennt man, welcher Service gemeint ist",
    "Nutzen: an ANI kann man den Kunden evtl. schon erkennen"],
   "DNIS vs ANI explained", (G_HELP + "articles/", None)),
 T("Participant Data / KVPs",
   "Participant Data sind Zusatz-Infos, die an einem Gespraech 'kleben'. KVP heisst Key-Value-Pair: ein Name und ein Wert, z.B. Kundennummer = 12345.",
   ["KVP = Key-Value-Pair (Schluessel = Wert)",
    "Beispiel: sprache = deutsch, kundentyp = premium",
    "Wird im Flow gesetzt und weitergegeben",
    "Hilft dem Agent, den Kunden sofort zu verstehen"],
   "Genesys participant data attributes", (G_DEV + "routing/", None)),
])

# ===========================================================================
# MODUL 2 - Technische Grundlagen (Voraussetzung)
# ===========================================================================
M("Technische Grundlagen", "🔧",
  "Die drei Basis-Technologien verstehen, die ueberall gebraucht werden: JSON, REST API, OAuth.",
[
 T("JSON Grundlagen",
   "JSON ist eine einfache Art, Daten aufzuschreiben, die Computer und Menschen lesen koennen. Es sieht aus wie eine Liste mit Name und Wert.",
   ['Aufbau: {"name": "Anna", "alter": 30}',
    "Datentypen: Text, Zahl, wahr/falsch, Liste, Objekt",
    "Wird zum Austausch von Daten zwischen Programmen benutzt",
    "Klammern {} = Objekt, eckige [] = Liste"],
   "JSON einfach erklaert fuer Anfaenger",
   ("MDN: JSON Einfuehrung", "https://developer.mozilla.org/de/docs/Learn/JavaScript/Objects/JSON")),
 T("REST API Grundlagen",
   "Eine API ist eine 'Steckdose' fuer Programme: darueber fragt ein Programm ein anderes um Daten. REST ist die haeufigste Art, das ueber das Internet zu tun.",
   ["API = Schnittstelle zwischen Programmen",
    "Endpoint = eine Adresse (URL), die man aufruft",
    "Methoden: GET (holen), POST (senden), PUT (aendern), DELETE (loeschen)",
    "Antwort kommt meist als JSON zurueck"],
   "REST API einfach erklaert deutsch",
   ("MDN: Einfuehrung Web-APIs", "https://developer.mozilla.org/de/docs/Learn/JavaScript/Client-side_web_APIs/Introduction")),
 T("OAuth Grundlagen",
   "OAuth ist ein sicherer Weg, damit ein Programm im Namen von jemandem zugreifen darf - ohne das Passwort zu kennen. Wie ein Hotel-Schluesselkarte statt Generalschluessel.",
   ["Token = Zugangsschluessel auf Zeit",
    "Client ID / Client Secret = Ausweis der App",
    "Grant Types: z.B. Client Credentials, Authorization Code",
    "Genesys nutzt OAuth fuer alle API-Zugriffe"],
   "OAuth 2.0 einfach erklaert deutsch",
   ("Genesys Dev: OAuth", G_DEV + "authorization/oauth"),
   gh=[("oauth.net Uebersicht", "https://oauth.net/2/")]),
])

# ===========================================================================
# MODUL 3 - Genesys Cloud Plattform
# ===========================================================================
M("Genesys Cloud Plattform", "☁️",
  "Die Genesys Cloud kennenlernen: Aufbau, Organisation, Rechte, Auswertungen.",
[
 T("Genesys Cloud Plattformueberblick",
   "Genesys Cloud ist ein Programm im Internet (Cloud) fuer Contact Center. Man braucht nur einen Browser. Es kann Telefon, Chat, Bots und Auswertungen.",
   ["Cloud = laeuft im Internet, keine eigene Server-Hardware noetig",
    "All-in-one: Voice, Digital, WEM, Reporting, AI",
    "Wird staendig automatisch aktualisiert",
    "Zugriff ueber Browser oder App"],
   "Genesys Cloud overview beginner", ("Genesys Cloud Produktseite", "https://www.genesys.com/de/genesys-cloud")),
 T("Genesys Cloud Organisation",
   "Die Organisation (Org) ist der eigene, abgetrennte Bereich einer Firma in Genesys Cloud. Alles, was die Firma anlegt, liegt in ihrer Org.",
   ["Org = der Firmen-Container",
    "Region = wo die Daten liegen (z.B. Frankfurt)",
    "Jede Org hat eigene Nutzer, Queues, Flows",
    "Wichtig fuer Datenschutz: EU-Daten in EU-Region"],
   "Genesys Cloud organization setup", (G_HELP + "articles/about-organizations/", None)),
 T("Genesys Cloud Divisions",
   "Divisions sind Unter-Bereiche innerhalb der Org, wie Abteilungen. So kann man trennen, wer welche Dinge sehen darf.",
   ["Division = logische Abteilung/Trennung",
    "Beispiel: Division 'Privatkunden', Division 'Firmenkunden'",
    "Objekte (Queues, Flows) gehoeren zu einer Division",
    "Zusammen mit Rollen steuert das die Sichtbarkeit"],
   "Genesys Cloud divisions explained", (G_HELP + "articles/about-divisions/", None)),
 T("Genesys Cloud Rollen und Berechtigungen",
   "Eine Rolle ist ein Buendel von Rechten. So bekommt jeder nur das, was er braucht. Ein Agent darf anderes als ein Admin.",
   ["Rolle = Sammlung von Berechtigungen (Permissions)",
    "Least Privilege: nur so viele Rechte wie noetig",
    "Rolle + Division = wer darf was, und wo",
    "Beispiele: Admin, Supervisor, Agent"],
   "Genesys Cloud roles permissions", (G_HELP + "articles/about-roles-permissions/", None)),
 T("Genesys Cloud Queues",
   "In Genesys Cloud legt man Queues (Warteschlangen) selbst an und stellt ein, wie Anrufe verteilt werden und wie lange man wartet.",
   ["Queue anlegen und Mitglieder (Agents) zuweisen",
    "Einstellungen: Wartemusik, Timeout, Ueberlauf",
    "Routing-Methode auswaehlen (z.B. Standard, Bullseye)",
    "Mit Skills kombinierbar"],
   "Genesys Cloud create queue tutorial", (G_HELP + "articles/create-queues/", None)),
 T("Genesys Cloud Skills",
   "Skills legt man an und weist sie Agents zu. Im Flow verlangt man dann einen Skill, damit nur passende Agents das Gespraech bekommen.",
   ["Skill anlegen (z.B. 'Kredit', 'Tuerkisch')",
    "Agents Skills zuweisen, evtl. mit Stufe (Proficiency)",
    "Language Skills fuer Sprachen",
    "ACD nutzt Skills fuer die Verteilung"],
   "Genesys Cloud skills routing", (G_HELP + "articles/about-acd-skills-and-languages/", None)),
 T("Genesys Cloud Analytics",
   "Analytics zeigt in Zahlen und Grafiken, was im Contact Center passiert: wie viele Anrufe, wie lange Wartezeit, wie zufrieden die Kunden.",
   ["Dashboards = Uebersichtsbildschirme",
    "Metriken: z.B. Service Level, AHT (Bearbeitungszeit)",
    "Views = fertige Auswertungsansichten",
    "Grundlage fuer Verbesserungen und Reporting"],
   "Genesys Cloud analytics overview", (G_HELP + "articles/about-analytics/", None)),
])

# ===========================================================================
# MODUL 4 - Genesys Architect & Flows
# ===========================================================================
M("Genesys Architect & Flows", "🧭",
  "Den Genesys Architect bedienen und die wichtigsten Flows (Ablaeufe) bauen.",
[
 T("Genesys Cloud Architect",
   "Architect ist das Bau-Werkzeug fuer Ablaeufe (Flows). Man klickt Bausteine zusammen, statt zu programmieren - wie ein Flussdiagramm.",
   ["Flow = der Weg, den ein Anruf/Chat nimmt",
    "Bausteine (Actions) per Drag-and-drop",
    "Kein Programmieren noetig (Low-Code)",
    "Verschiedene Flow-Typen: Inbound, In-Queue, Bot ..."],
   "Genesys Architect tutorial beginner", (G_HELP + "articles/about-architect/", None),
   gh=[("Genesys Cloud CLI (Automatisierung)", "https://github.com/MyPureCloud/platform-client-sdk-cli")]),
 T("Inbound Call Flow",
   "Der Inbound Call Flow steuert einen eingehenden Anruf: Begruessung, Menue, Abfragen und dann Weiterleitung an die richtige Queue.",
   ["Inbound = eingehend (Kunde ruft an)",
    "Typische Schritte: Ansage, Menue, Pruefung, Transfer",
    "Oeffnungszeiten pruefen (In-hours/Out-of-hours)",
    "Ziel: schnell zum richtigen Agent"],
   "Genesys inbound call flow tutorial", (G_HELP + "articles/create-inbound-call-flow/", None)),
 T("Inbound Message Flow",
   "Wie der Call Flow, aber fuer Text: Chat, WhatsApp, SMS. Statt Ansagen gibt es Textnachrichten.",
   ["Message Flow = fuer digitale Text-Kanaele",
    "Kanaele: Webchat, WhatsApp, SMS, Facebook",
    "Kann Bot einbinden, bevor ein Mensch uebernimmt",
    "Antworten als Text statt Sprache"],
   "Genesys inbound message flow", (G_HELP + "articles/about-message-flows/", None)),
 T("In-Queue Flow",
   "Der In-Queue Flow laeuft, waehrend der Kunde in der Warteschlange wartet: Wartemusik, Ansagen wie 'Sie sind Nummer 3', Rueckruf anbieten.",
   ["Laeuft nur waehrend des Wartens",
    "Wartemusik und Ansagen",
    "Estimated Wait Time / Position ansagen",
    "Callback (Rueckruf) anbieten statt warten"],
   "Genesys in-queue flow tutorial", (G_HELP + "articles/about-in-queue-flows/", None)),
 T("Transfer to ACD",
   "Transfer to ACD ist der Baustein, der den Kunden aus dem Flow in eine Queue uebergibt, damit ein Agent uebernimmt.",
   ["ACD = Automatic Call Distribution",
    "Uebergibt an Queue mit passenden Skills",
    "Setzt oft vorher Priority und Skills",
    "Danach wartet der Kunde in der Queue (In-Queue Flow)"],
   "Genesys transfer to ACD action", (G_HELP + "articles/", None)),
 T("Agent Scripts",
   "Ein Script ist eine Bildschirm-Anleitung fuer den Agent: welche Fragen er stellen soll und welche Kundendaten er sieht - wie ein Spickzettel.",
   ["Script = gefuehrte Maske fuer den Agent",
    "Zeigt Kundendaten und naechste Schritte",
    "Kann Buttons und Data Actions enthalten",
    "Sorgt fuer einheitliche Qualitaet"],
   "Genesys Cloud agent scripts tutorial", (G_HELP + "articles/about-scripting/", None)),
 T("Data Actions",
   "Data Actions holen live Daten aus anderen Systemen (z.B. dem Bank-System) in den Flow oder das Script - z.B. Kontostand oder Kundenname.",
   ["Data Action = Aufruf einer fremden API aus Genesys",
    "Braucht eine Integration (Verbindung)",
    "Input (was schicke ich) und Output (was kommt zurueck)",
    "Beispiel: Kundennummer rein, Name/Status raus"],
   "Genesys Cloud data actions tutorial", (G_DEV + "platform/integrations/", None),
   gh=[("Genesys Cloud Data Actions Beispiele", "https://github.com/GenesysCloudBlueprints")]),
 T("Genesys Cloud APIs",
   "Ueber die Genesys Cloud API kann man fast alles automatisieren: Nutzer anlegen, Daten auslesen, Flows steuern - von aussen per Programm.",
   ["Ueber 1000 Endpoints (REST API)",
    "Zugriff mit OAuth-Token",
    "SDKs fuer viele Sprachen (Python, JavaScript ...)",
    "Rate Limits beachten (nicht zu viele Aufrufe)"],
   "Genesys Cloud API tutorial", (G_DEV, None),
   gh=[("Platform Client SDK", "https://github.com/MyPureCloud"),
       ("Python SDK", "https://github.com/MyPureCloud/platform-client-sdk-python")]),
])

# ===========================================================================
# MODUL 5 - Genesys AI Bausteine
# ===========================================================================
M("Genesys AI Bausteine", "🤖",
  "Die KI-Funktionen von Genesys kennenlernen, die Agents und Kunden helfen.",
[
 T("Genesys AI Studio",
   "AI Studio ist der Ort in Genesys, wo man die KI-Funktionen (Bots, Knowledge, Agent Assist) einrichtet und trainiert.",
   ["Zentraler Ort fuer Genesys AI",
    "Bots bauen und trainieren",
    "Knowledge und Intents verwalten",
    "Basis fuer die GC-AI-DB Zertifizierung"],
   "Genesys AI Studio overview", (G_HELP + "articles/", None)),
 T("Genesys Agent Assist",
   "Agent Assist ist ein Helfer, der dem Agent waehrend des Gespraechs live Vorschlaege und passende Wissens-Artikel einblendet.",
   ["Live-Hilfe fuer den Agent",
    "Schlaegt Knowledge-Artikel vor",
    "Hoert mit (Voice/Chat) und reagiert",
    "Verkuerzt Bearbeitungszeit, weniger Fehler"],
   "Genesys Agent Assist demo", (G_HELP + "articles/about-agent-assist/", None)),
 T("Genesys Agent Copilot",
   "Agent Copilot ist die neuere, KI-gestuetzte Version von Agent Assist: sie versteht das Gespraech und gibt konkrete naechste Schritte und Antworten.",
   ["KI-Assistent fuer Agents (GenAI)",
    "Schlaegt Antworten und Wissen in Echtzeit vor",
    "Fasst Kundenanliegen zusammen",
    "Baut auf Knowledge Base auf"],
   "Genesys Agent Copilot overview", (G_HELP + "articles/", None)),
 T("Genesys Conversation Summary",
   "Nach dem Gespraech schreibt die KI automatisch eine kurze Zusammenfassung, damit der Agent nicht alles selbst tippen muss (After-Call Work).",
   ["Automatische Zusammenfassung des Gespraechs",
    "Spart Nachbearbeitungszeit (ACW)",
    "Einheitliche, kurze Notizen",
    "Kann Grund, Loesung, naechste Schritte erfassen"],
   "Genesys conversation summarization", (G_HELP + "articles/", None)),
 T("Genesys Virtual Agent",
   "Ein Virtual Agent ist ein Bot, der wie ein Agent mit Kunden spricht und einfache Anliegen selbst loest, ohne Menschen.",
   ["Virtual Agent = automatischer Gespraechspartner (Bot)",
    "Loest Standardfragen rund um die Uhr",
    "Uebergibt an Menschen, wenn noetig",
    "Kann Voice und Digital sein"],
   "Genesys virtual agent explained", (G_HELP + "articles/", None)),
])

# ===========================================================================
# MODUL 6 - Bot Flows & NLU
# ===========================================================================
M("Bot Flows & NLU", "💬",
  "Bots bauen und der KI beibringen, Sprache zu verstehen (NLU).",
[
 T("Genesys Digital Bot Flow",
   "Ein Digital Bot Flow ist der Chatbot-Ablauf fuer Text-Kanaele. Man baut ihn im Architect: Fragen, Antworten, Verzweigungen.",
   ["Fuer Chat/Messaging (Text)",
    "Bausteine: Ask, Communicate, Decision",
    "Kann Knowledge und Intents nutzen",
    "Uebergabe an Agent moeglich"],
   "Genesys digital bot flow tutorial", (G_HELP + "articles/about-digital-bot-flows/", None)),
 T("Genesys Voice Bot Flow",
   "Wie der Digital Bot, aber am Telefon: der Bot spricht (Text-to-Speech) und versteht Gesprochenes (Speech-to-Text).",
   ["Fuer Voice (Telefon)",
    "Spracherkennung (STT) und Sprachausgabe (TTS)",
    "Umgang mit Verstehfehlern wichtig",
    "Barge-in: Kunde kann den Bot unterbrechen"],
   "Genesys voice bot flow tutorial", (G_HELP + "articles/about-voice-bot-flows/", None)),
 T("Genesys Bot Flow Actions",
   "Actions sind die Bausteine im Bot: eine Frage stellen, etwas sagen, entscheiden, Daten holen. Man reiht sie zum Ablauf.",
   ["Ask for Intent / Ask for Slot",
    "Communicate (etwas sagen)",
    "Decision / Switch (verzweigen)",
    "Call Data Action (Daten holen)"],
   "Genesys bot flow actions", (G_HELP + "articles/", None)),
 T("Genesys Bot Flow Variablen",
   "Variablen sind Merkzettel im Bot. Sie speichern Werte waehrend des Gespraechs, z.B. die genannte Kontonummer.",
   ["Variable = Speicherplatz mit Namen",
    "Typen: String, Integer, Boolean, ...",
    "Scope: Flow-Variable vs Slot",
    "Werden in Bedingungen und Antworten genutzt"],
   "Genesys bot flow variables", (G_HELP + "articles/", None)),
 T("Genesys NLU Grundlagen",
   "NLU heisst Natural Language Understanding - die Faehigkeit der KI, gesprochene/geschriebene Sprache zu verstehen und den Wunsch zu erkennen.",
   ["NLU = Sprache verstehen (Absicht erkennen)",
    "Bestandteile: Intents, Utterances, Slots",
    "Wird mit Beispielen trainiert",
    "Basis fuer jeden guten Bot"],
   "NLU natural language understanding erklaert", (G_HELP + "articles/about-natural-language-understanding/", None)),
 T("Intents",
   "Ein Intent ist die Absicht des Kunden, z.B. 'Karte sperren' oder 'Kontostand'. Der Bot erkennt den Intent und reagiert passend.",
   ["Intent = Ziel/Wunsch des Kunden",
    "Ein Bot hat viele Intents",
    "Jeder Intent hat viele Beispielsaetze (Utterances)",
    "Guter Schnitt: nicht zu breit, nicht zu eng"],
   "Chatbot intents explained", (G_HELP + "articles/about-intents/", None)),
 T("Utterances",
   "Utterances sind Beispielsaetze, wie Kunden etwas sagen koennten. Je mehr echte Beispiele, desto besser erkennt der Bot den Intent.",
   ["Utterance = Beispielsatz fuer einen Intent",
    "Viele Varianten sammeln (auch Umgangssprache)",
    "15-30+ Beispiele pro Intent als Start",
    "Echte Kundensaetze sind am besten"],
   "chatbot training utterances", (G_HELP + "articles/", None)),
 T("Slots",
   "Ein Slot ist eine Information, die der Bot aus dem Satz herausfischt, z.B. aus 'Ich will 100 Euro' den Betrag 100.",
   ["Slot = herausgezogene Info aus dem Satz",
    "Beispiel: Betrag, Datum, Kontonummer",
    "Bot fragt nach, wenn Slot fehlt",
    "Wird in Variablen gespeichert"],
   "chatbot slots entities explained", (G_HELP + "articles/about-slots/", None)),
 T("Slot Types",
   "Der Slot Type sagt, welche Art von Wert erwartet wird: Zahl, Datum, Waehrung oder eine eigene Liste (z.B. Kontoarten).",
   ["Built-in Types: Number, Date, Currency ...",
    "Custom Slot Type: eigene Werte-Liste",
    "Hilft dem Bot beim richtigen Erkennen",
    "Beispiel: Kontoart = [Giro, Spar, Depot]"],
   "chatbot slot types", (G_HELP + "articles/about-slot-types/", None)),
 T("Confidence Score",
   "Der Confidence Score ist eine Sicherheits-Zahl (0 bis 1): wie sicher ist sich der Bot, den Intent richtig erkannt zu haben.",
   ["0 bis 1 (bzw. 0-100%)",
    "Hoch = sehr sicher, niedrig = unsicher",
    "Schwelle (Threshold) festlegen",
    "Unter der Schwelle -> Nachfragen statt raten"],
   "NLU confidence score explained", (G_HELP + "articles/", None)),
 T("No Match",
   "No Match passiert, wenn der Bot nichts Passendes versteht. Dann sollte er hoeflich nachfragen statt falsch zu antworten.",
   ["No Match = kein Intent erkannt",
    "Reaktion: freundlich nachfragen",
    "Nach mehreren Versuchen: an Agent uebergeben",
    "Gute No-Match-Texte verhindern Frust"],
   "chatbot no match handling", (G_HELP + "articles/", None)),
 T("No Input",
   "No Input passiert, wenn der Kunde gar nichts sagt/schreibt. Der Bot sollte erinnern und dann weiterleiten.",
   ["No Input = keine Antwort vom Kunden",
    "Reaktion: erneut fragen ('Sind Sie noch da?')",
    "Timeout einstellen",
    "Nach X Versuchen: Uebergabe oder Abschluss"],
   "voice bot no input timeout", (G_HELP + "articles/", None)),
 T("Intent Design fuer Banken",
   "Beim Bank-Bot muss man die Intents klug schneiden: typische Bank-Anliegen sauber trennen und sensible Themen sicher behandeln.",
   ["Typische Intents: Karte sperren, Kontostand, Ueberweisung",
    "Sensible Themen klar trennen (Betrug, Sperrung)",
    "Nicht zu viele aehnliche Intents (Verwechslung)",
    "Immer sicheren Weg zum Menschen anbieten"],
   "banking chatbot intent design", (G_HELP + "articles/", None)),
 T("Intent Miner",
   "Der Intent Miner schaut in echte Gespraeche und schlaegt automatisch vor, welche Intents Kunden brauchen - man muss nicht raten.",
   ["Analysiert echte Transkripte",
    "Schlaegt neue Intents/Utterances vor",
    "Spart Zeit beim Bot-Aufbau",
    "Basiert auf echten Kundenanliegen"],
   "Genesys intent miner", (G_HELP + "articles/about-intent-miner/", None)),
 T("Bot Learning",
   "Bot Learning heisst: der Bot wird mit Daten trainiert und mit der Zeit besser, wenn man aus Fehlern nachbessert.",
   ["Training = dem Bot Beispiele geben",
    "Nach dem Live-Gang weiter verbessern",
    "Fehler ansehen und Utterances ergaenzen",
    "Regelmaessig neu trainieren"],
   "chatbot training and learning", (G_HELP + "articles/", None)),
 T("Bot Optimization",
   "Optimization heisst, den Bot mit Zahlen zu verbessern: wo bricht der Kunde ab, wo versteht der Bot schlecht?",
   ["Kennzahlen ansehen (Containment, Erfolgsquote)",
    "Schwachstellen finden (viele No Matches)",
    "Utterances/Intents anpassen",
    "Immer wieder wiederholen (Kreislauf)"],
   "chatbot optimization metrics", (G_HELP + "articles/", None)),
 T("Bot QA Testing",
   "QA Testing heisst, den Bot vor und nach dem Live-Gang systematisch zu pruefen: Versteht er alles? Macht er keine Fehler?",
   ["Testfaelle schreiben (typische Saetze)",
    "Erkennung und Antworten pruefen",
    "Grenzfaelle testen (Tippfehler, Slang)",
    "Vor jedem Release testen"],
   "chatbot QA testing", (G_HELP + "articles/", None)),
])

# ===========================================================================
# MODUL 7 - Knowledge
# ===========================================================================
M("Knowledge (Wissen)", "📚",
  "Wissens-Artikel bauen und dem Bot Wissen geben - das Herz der GC-AI-DB.",
[
 T("Knowledge Workbench",
   "Die Knowledge Workbench ist das Werkzeug, um Wissens-Artikel zu erstellen und zu pflegen, die Bot und Agent nutzen.",
   ["Ort zum Erstellen/Bearbeiten von Wissen",
    "Artikel, Kategorien, Labels verwalten",
    "Wird von Bot und Agent Assist genutzt",
    "Wichtig fuer die GC-AI-DB Pruefung"],
   "Genesys knowledge workbench tutorial", (G_KNOW, None)),
 T("Knowledge Base Design",
   "Eine Knowledge Base (Wissensdatenbank) muss gut geplant sein: klare Struktur, verstaendliche Artikel, damit die KI gute Antworten findet.",
   ["Knowledge Base = Sammlung von Wissens-Artikeln",
    "Struktur vorher planen",
    "Kurze, klare Artikel schreiben",
    "Eine Frage - eine Antwort"],
   "knowledge base best practices", (G_KNOW, None)),
 T("Knowledge Articles",
   "Ein Article ist ein einzelner Wissens-Eintrag: eine Frage und die Antwort. Der Bot sucht darin die passende Antwort.",
   ["Article = Frage + Antwort",
    "Alternative Fragen (Phrasings) hinzufuegen",
    "Kurz und eindeutig halten",
    "Regelmaessig aktuell halten"],
   "Genesys knowledge article create", (G_HELP + "articles/create-knowledge-article/", None)),
 T("Knowledge Categories",
   "Categories sind Ordner fuer Artikel, damit das Wissen sortiert ist, z.B. 'Karten', 'Konto', 'Kredit'.",
   ["Category = Ordner/Thema",
    "Ordnung schafft Uebersicht",
    "Kann Unterkategorien haben",
    "Hilft Suche und Pflege"],
   "Genesys knowledge categories", (G_KNOW, None)),
 T("Knowledge Labels",
   "Labels sind Etiketten, die man Artikeln anheftet, um sie zusaetzlich zu filtern oder gezielt anzuzeigen.",
   ["Label = Etikett/Stichwort",
    "Filtern und Steuern der Anzeige",
    "Ein Artikel kann mehrere Labels haben",
    "Nuetzlich fuer Ziel-Gruppen/Kanaele"],
   "Genesys knowledge labels", (G_KNOW, None)),
 T("Knowledge Portal",
   "Das Knowledge Portal ist eine Self-Service-Webseite, auf der Kunden selbst im Wissen suchen koennen - ohne Anruf.",
   ["Portal = Selbstbedienungs-Wissensseite",
    "Kunden finden Antworten allein",
    "Entlastet das Contact Center",
    "Nutzt dieselben Artikel wie der Bot"],
   "Genesys knowledge portal", (G_HELP + "articles/", None)),
 T("Knowledge Optimizer",
   "Der Knowledge Optimizer zeigt, welche Artikel fehlen oder schlecht laufen, und schlaegt Verbesserungen vor.",
   ["Findet Wissensluecken",
    "Zeigt haeufige unbeantwortete Fragen",
    "Schlaegt neue/bessere Artikel vor",
    "Datengetriebene Pflege"],
   "Genesys knowledge optimizer", (G_HELP + "articles/", None)),
 T("Knowledge mit Bot Flow verbinden",
   "Damit der Bot Wissen nutzen kann, verknuepft man die Knowledge Base im Bot Flow. Dann beantwortet der Bot Fragen aus dem Wissen.",
   ["Knowledge Base im Bot Flow auswaehlen",
    "Knowledge-Action einbauen",
    "Bot sucht Antwort im Wissen",
    "Fallback, wenn nichts gefunden wird"],
   "Genesys connect knowledge to bot flow", (G_HELP + "articles/", None)),
 T("Custom Knowledge Handling",
   "Manchmal reicht Standard nicht: man steuert selbst, wie der Bot mit Wissen umgeht, z.B. mehrere Treffer anzeigen oder gezielt filtern.",
   ["Eigene Logik im Flow einbauen",
    "Mehrere Treffer verarbeiten",
    "Nach Label/Kategorie filtern",
    "Antwortformat anpassen"],
   "Genesys custom knowledge handling", (G_HELP + "articles/", None)),
])

# ===========================================================================
# MODUL 8 - Zertifizierung
# ===========================================================================
M("GC-AI-DB Zertifizierung", "🎓",
  "Die offizielle Genesys-Zertifizierung fuer AI, Digital Bots & Knowledge.",
[
 T("GC-AI-DB Zertifizierung",
   "GC-AI-DB steht fuer 'Genesys Cloud: AI - Digital Bots & Knowledge Certification'. Ein offizieller Nachweis, dass man Genesys-Bots und Knowledge beherrscht.",
   ["Deckt ab: Bot Flows, NLU, Knowledge, Agent Assist",
    "Vorbereitung ueber Genesys Beyond (Kurse)",
    "Praxis im eigenen/Test-Org ueben",
    "Pruefung online, danach Zertifikat/Badge"],
   "Genesys GC-AI-DB certification",
   ("Genesys Beyond Lernplattform", G_BEYOND),
   art=[("Genesys Zertifizierungen Uebersicht", "https://www.genesys.com/de/customer-success/genesys-university")]),
])

# ===========================================================================
# MODUL 9 - GenAI Grundlagen
# ===========================================================================
M("GenAI Grundlagen", "🧠",
  "Die Basis moderner KI verstehen: was LLMs sind und wie man mit ihnen redet.",
[
 T("GenAI Grundlagen",
   "GenAI (Generative KI) ist KI, die Neues erzeugt: Texte, Bilder, Code. Sie hat aus riesigen Datenmengen 'gelernt', Muster fortzusetzen.",
   ["Generative KI = erzeugt neue Inhalte",
    "Beispiele: ChatGPT, Claude, Bilder-KI",
    "Lernt aus sehr vielen Beispieldaten",
    "Rechnet Wahrscheinlichkeiten, denkt nicht wie Mensch"],
   "Generative KI einfach erklaert deutsch",
   ("Fraunhofer: Generative KI", "https://www.iis.fraunhofer.de/de/ff/ki.html"),
   art=[("Bitkom: KI-Grundlagen", "https://www.bitkom.org/Themen/Technologien-Software/Kuenstliche-Intelligenz")]),
 T("Large Language Models",
   "Ein LLM (Large Language Model) ist ein sehr grosses KI-Sprachmodell. Es sagt immer das naechste Wort voraus und kann so ganze Texte schreiben.",
   ["LLM = grosses Sprachmodell",
    "Sagt das jeweils naechste Wort (Token) voraus",
    "Beispiele: GPT, Claude, Gemini, Llama",
    "Sehr faehig, aber kann sich irren"],
   "Large Language Model einfach erklaert",
   ("Anthropic: Was ist ein LLM", "https://www.anthropic.com/learn")),
 T("Small Language Models",
   "Ein SLM (Small Language Model) ist ein kleines Sprachmodell. Es ist guenstiger, schneller und kann auch lokal laufen - dafuer weniger maechtig.",
   ["SLM = kleines Sprachmodell",
    "Guenstiger und schneller",
    "Kann auf eigenem Rechner laufen (privat)",
    "Gut fuer klare, enge Aufgaben"],
   "Small Language Models explained"),
 T("Multimodalitaet",
   "Multimodal heisst, die KI versteht mehr als nur Text - auch Bilder, Ton oder Video. Man kann ihr z.B. ein Foto zeigen.",
   ["Modalitaet = Art der Info (Text, Bild, Ton)",
    "Multimodal = mehrere Arten gleichzeitig",
    "Beispiel: Bild hochladen und Fragen stellen",
    "Nuetzlich fuer Dokumente, Screenshots"],
   "multimodal AI erklaert deutsch"),
 T("Reasoning",
   "Reasoning heisst 'Schlussfolgern'. Neuere Modelle denken in Schritten, bevor sie antworten - so loesen sie schwierigere Aufgaben besser.",
   ["Reasoning = schrittweises Nachdenken",
    "Bessere Ergebnisse bei schweren Aufgaben",
    "Braucht mehr Zeit und Rechenleistung",
    "Beispiel: Rechenaufgabe Schritt fuer Schritt"],
   "AI reasoning models erklaert"),
 T("Prompting",
   "Ein Prompt ist die Anweisung, die man der KI gibt. Je klarer der Prompt, desto besser die Antwort - wie eine gute Frage an einen Experten.",
   ["Prompt = deine Anweisung/Frage an die KI",
    "Klar sagen, was man will",
    "Beispiele und Kontext helfen",
    "Format vorgeben (z.B. 'als Liste')"],
   "Prompting fuer Anfaenger deutsch",
   ("Anthropic Prompt-Guide", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview")),
 T("Advanced Prompting",
   "Fortgeschrittene Prompt-Techniken holen mehr aus der KI heraus, z.B. Beispiele geben (Few-shot) oder Schritt-fuer-Schritt denken lassen.",
   ["Few-shot: Beispiele mitgeben",
    "Chain-of-Thought: 'denke Schritt fuer Schritt'",
    "Rolle geben ('Du bist Bank-Experte')",
    "Klare Ausgabe-Regeln setzen"],
   "advanced prompting techniques",
   ("Anthropic Prompt-Engineering", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview")),
 T("Prompt Engineering",
   "Prompt Engineering ist das Handwerk, Prompts systematisch zu bauen und zu testen, damit die KI zuverlaessig gute Ergebnisse liefert.",
   ["Prompts planen, testen, verbessern",
    "Wiederholbar und dokumentiert",
    "Wichtig fuer Bots im Echtbetrieb",
    "Kleiner Wortwechsel kann viel aendern"],
   "Prompt Engineering deutsch",
   ("Anthropic: Prompt Engineering", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview"),
   gh=[("Anthropic Prompt-Beispiele (Cookbook)", "https://github.com/anthropics/anthropic-cookbook")]),
 T("Context Engineering",
   "Context Engineering heisst, der KI die richtigen Zusatz-Infos mitzugeben (z.B. Kundendaten, Regeln), damit sie passend antwortet.",
   ["Kontext = Zusatz-Infos fuer die KI",
    "Richtige Daten zur richtigen Zeit geben",
    "Zu viel Kontext verwirrt und kostet",
    "Grundlage fuer RAG (siehe spaeter)"],
   "context engineering LLM"),
 T("Token und Kosten",
   "KI rechnet in Tokens (Wort-Teile). Je mehr Text rein und raus geht, desto mehr Tokens - und danach richten sich die Kosten.",
   ["Token = kleines Text-Stueck (ca. 4 Zeichen)",
    "Input + Output = Tokens = Kosten",
    "Laengere Prompts kosten mehr",
    "Kurz und gezielt spart Geld"],
   "was sind tokens LLM erklaert",
   ("Anthropic: Token & Pricing", "https://docs.anthropic.com/en/docs/about-claude/pricing")),
 T("Halluzinationen",
   "Eine Halluzination ist, wenn die KI etwas Falsches sehr ueberzeugend behauptet. Sie 'erfindet' dann Fakten. Deshalb muss man wichtige Antworten pruefen.",
   ["Halluzination = ueberzeugend erfundene Falschinfo",
    "Passiert, weil KI Wahrscheinlichkeiten raet",
    "Gefahr in Banken: falsche Auskunft",
    "Gegenmittel: Grounding/RAG und Pruefung"],
   "AI Halluzinationen erklaert deutsch",
   art=[("Fraunhofer: Vertrauenswuerdige KI", "https://www.iis.fraunhofer.de/de/ff/ki.html")]),
 T("Grounding",
   "Grounding heisst 'auf den Boden der Fakten stellen': man gibt der KI echte Quellen, damit sie daraus antwortet und weniger erfindet.",
   ["Grounding = Antwort auf echte Quellen stuetzen",
    "Reduziert Halluzinationen",
    "Basis fuer RAG",
    "Wichtig fuer verlaessliche Bank-Antworten"],
   "grounding LLM explained"),
])

# ===========================================================================
# MODUL 10 - RAG & Suche
# ===========================================================================
M("RAG & Suche", "🔎",
  "Der KI aktuelles, eigenes Wissen geben - die wichtigste Technik fuer Firmen-Bots.",
[
 T("Retrieval Augmented Generation",
   "RAG heisst: erst passendes Wissen suchen, dann die KI daraus antworten lassen. So nutzt der Bot euer eigenes, aktuelles Wissen statt zu raten.",
   ["RAG = Suchen + Antworten kombinieren",
    "1. Frage -> passende Dokumente finden",
    "2. Diese Dokumente der KI geben",
    "3. KI antwortet nur daraus (weniger Halluzination)"],
   "RAG Retrieval Augmented Generation erklaert deutsch",
   gh=[("LlamaIndex (RAG Framework)", "https://github.com/run-llama/llama_index"),
       ("LangChain", "https://github.com/langchain-ai/langchain")]),
 T("Embeddings",
   "Ein Embedding verwandelt Text in Zahlen (einen 'Fingerabdruck'). Aehnliche Bedeutungen bekommen aehnliche Zahlen - so kann man nach Sinn suchen.",
   ["Embedding = Text als Zahlenreihe (Vektor)",
    "Aehnlicher Sinn = aehnliche Zahlen",
    "Grundlage fuer semantische Suche",
    "Wird einmal berechnet und gespeichert"],
   "was sind embeddings erklaert"),
 T("Vector Search",
   "Vector Search sucht nicht nach genauen Woertern, sondern nach Bedeutung - ueber die Embedding-Zahlen findet sie die aehnlichsten Texte.",
   ["Sucht nach Bedeutung, nicht nach Wortgleichheit",
    "Vergleicht Embedding-Vektoren",
    "Findet auch bei anderer Wortwahl",
    "Braucht eine Vector Database"],
   "vector search erklaert deutsch",
   gh=[("FAISS (Vektorsuche)", "https://github.com/facebookresearch/faiss"),
       ("Chroma Vector DB", "https://github.com/chroma-core/chroma")]),
 T("Chunking",
   "Chunking heisst, lange Dokumente in kleine Haeppchen (Chunks) zu schneiden, damit die Suche gezielt die richtige Stelle findet.",
   ["Chunk = kleines Text-Stueck",
    "Grosse Texte in Stuecke teilen",
    "Zu gross = ungenau, zu klein = Zusammenhang fehlt",
    "Oft mit Overlap (Ueberlappung)"],
   "chunking RAG erklaert"),
 T("RAG Architektur",
   "Die RAG-Architektur ist der komplette Bauplan: Dokumente vorbereiten, in Embeddings umwandeln, speichern, suchen und die KI antworten lassen.",
   ["Ingestion: Dokumente laden + chunken + embedden",
    "Storage: in Vector DB speichern",
    "Retrieval: passende Chunks finden",
    "Generation: KI antwortet mit den Chunks"],
   "RAG architecture explained",
   gh=[("LangChain", "https://github.com/langchain-ai/langchain")]),
 T("RAG Evaluation",
   "RAG Evaluation prueft, ob der Bot gute, korrekte Antworten gibt: Findet er das richtige Wissen? Stimmt die Antwort?",
   ["Retrieval pruefen: richtiges Dokument gefunden?",
    "Antwort pruefen: korrekt und belegt?",
    "Metriken: Faithfulness, Relevanz",
    "Mit Testfragen regelmaessig messen"],
   "RAG evaluation metrics",
   gh=[("Ragas (RAG Evaluation)", "https://github.com/explodinggradients/ragas")]),
 T("RAG Monitoring",
   "RAG Monitoring heisst, den Bot im laufenden Betrieb zu ueberwachen: Wo findet er nichts? Wo sind Antworten schlecht?",
   ["Live-Ueberwachung der Antwortqualitaet",
    "Fehlende Treffer erkennen",
    "Nutzer-Feedback sammeln (Daumen hoch/runter)",
    "Wissensluecken schliessen"],
   "RAG monitoring production"),
 T("Knowledge Graphs",
   "Ein Knowledge Graph ist ein Netz aus Fakten und ihren Verbindungen, z.B. 'Kunde - hat - Konto - gehoert zu - Filiale'. Gut fuer verknuepftes Wissen.",
   ["Netz aus Dingen (Nodes) und Beziehungen (Edges)",
    "Beispiel: Kunde -besitzt-> Karte",
    "Gut fuer Zusammenhaenge und Regeln",
    "Kann RAG praeziser machen (GraphRAG)"],
   "Knowledge Graph einfach erklaert",
   gh=[("Neo4j (Graph-Datenbank)", "https://github.com/neo4j/neo4j")]),
 T("Semantic Search",
   "Semantic Search ist die Suche nach Bedeutung. Man muss nicht das exakte Wort treffen - die Suche versteht, was gemeint ist.",
   ["Suche nach Sinn statt Wortgleichheit",
    "Nutzt Embeddings",
    "Findet 'Karte verloren' auch bei 'Karte weg'",
    "Grundlage guter Bot-Suche"],
   "semantic search erklaert deutsch"),
 T("Hybrid Search",
   "Hybrid Search kombiniert zwei Suchen: die klassische Wortsuche (Keyword) und die Bedeutungssuche (semantisch). Zusammen sind sie am treffsichersten.",
   ["Keyword-Suche + semantische Suche",
    "Keyword ist gut bei exakten Begriffen/Nummern",
    "Semantisch ist gut bei anderer Wortwahl",
    "Kombination liefert beste Treffer"],
   "hybrid search RAG explained"),
])

# ===========================================================================
# MODUL 11 - Tools & MCP
# ===========================================================================
M("Tools & MCP", "🛠️",
  "Wie KI mit anderen Systemen arbeitet - Werkzeuge nutzen und der MCP-Standard.",
[
 T("Tool Calling",
   "Tool Calling heisst, die KI darf Werkzeuge benutzen, z.B. eine Suche starten oder eine API aufrufen. So kann sie handeln, nicht nur reden.",
   ["Tool = Werkzeug/Funktion, die die KI aufrufen darf",
    "Beispiel: Kontostand aus dem Bank-System holen",
    "KI entscheidet, wann sie ein Tool nutzt",
    "Basis fuer handelnde KI-Agenten"],
   "LLM tool calling explained",
   ("Anthropic: Tool Use", "https://docs.anthropic.com/en/docs/build-with-claude/tool-use")),
 T("Function Calling",
   "Function Calling ist fast dasselbe wie Tool Calling: die KI ruft eine vorbereitete Funktion mit den richtigen Werten auf.",
   ["KI fuellt Funktions-Parameter aus",
    "Man beschreibt die Funktion vorher genau",
    "KI gibt strukturierte Werte (JSON) zurueck",
    "Verbindet KI mit echten Programmen"],
   "function calling LLM erklaert"),
 T("Model Context Protocol",
   "MCP (Model Context Protocol) ist ein offener Standard, wie KI-Modelle mit Werkzeugen und Datenquellen verbunden werden - wie ein USB-Stecker fuer KI.",
   ["MCP = einheitlicher Standard fuer KI-Anbindungen",
    "Trennt KI (Client) von Werkzeugen (Server)",
    "Einmal bauen, ueberall nutzen",
    "Von Anthropic gestartet, offen fuer alle"],
   "Model Context Protocol MCP erklaert deutsch",
   ("MCP Doku", "https://modelcontextprotocol.io/"),
   gh=[("MCP Server Sammlung", "https://github.com/modelcontextprotocol/servers"),
       ("MCP Spezifikation", "https://github.com/modelcontextprotocol")]),
 T("MCP Server",
   "Ein MCP Server stellt Werkzeuge oder Daten bereit, die die KI nutzen kann - z.B. Zugriff auf eine Datenbank oder ein Ticketsystem.",
   ["Server = bietet Tools/Daten an",
    "Beispiel: Server fuer das CRM",
    "Viele fertige Server verfuegbar",
    "Man kann eigene Server bauen"],
   "MCP server tutorial",
   gh=[("MCP Server (offiziell)", "https://github.com/modelcontextprotocol/servers")]),
 T("MCP Client",
   "Ein MCP Client ist die Seite der KI-App, die sich mit MCP Servern verbindet und deren Werkzeuge nutzt.",
   ["Client = die KI-App, die Tools nutzt",
    "Verbindet sich mit einem oder mehreren Servern",
    "Beispiel: Claude Desktop, IDEs",
    "Spricht das MCP-Protokoll"],
   "MCP client explained"),
 T("MCP Tools",
   "MCP Tools sind die einzelnen Faehigkeiten, die ein Server anbietet, z.B. 'suche_kunde' oder 'erstelle_ticket'.",
   ["Tool = einzelne Faehigkeit des Servers",
    "Klarer Name + Beschreibung + Parameter",
    "KI waehlt das passende Tool",
    "Gute Beschreibungen sind wichtig"],
   "MCP tools examples"),
 T("MCP Security",
   "Bei MCP muss man auf Sicherheit achten: Welche Tools duerfen was? Wer darf zugreifen? Gerade in Banken sehr wichtig.",
   ["Nur noetige Tools freigeben (Least Privilege)",
    "Zugriffe absichern (Auth)",
    "Gefahr: schadhafte Server/Tools",
    "Aktionen protokollieren (Audit)"],
   "MCP security best practices",
   gh=[("MCP Doku: Security", "https://modelcontextprotocol.io/")]),
])

# ===========================================================================
# MODUL 12 - Agentic AI
# ===========================================================================
M("Agentic AI (KI-Agenten)", "🕹️",
  "KI, die selbststaendig Aufgaben plant und erledigt - Grundlagen bis Betrieb.",
[
 T("Agentic AI",
   "Agentic AI ist KI, die nicht nur antwortet, sondern selbst Schritte plant und Werkzeuge nutzt, um ein Ziel zu erreichen.",
   ["Agent = handelnde KI mit Ziel",
    "Plant, nutzt Tools, prueft Ergebnis",
    "Kann mehrere Schritte allein gehen",
    "Braucht Grenzen (Guardrails)"],
   "Agentic AI erklaert deutsch",
   ("Anthropic: Building Agents", "https://www.anthropic.com/engineering/building-effective-agents")),
 T("KI-Agenten Grundlagen",
   "Ein KI-Agent verbindet ein Sprachmodell mit Werkzeugen und Gedaechtnis, damit es Aufgaben erledigen kann - wie ein digitaler Mitarbeiter.",
   ["Bestandteile: Modell + Tools + Memory + Ziel",
    "Loop: denken -> handeln -> beobachten",
    "Beispiel: Anliegen erfassen und im System buchen",
    "Immer mit Kontrolle einsetzen"],
   "AI agents basics erklaert"),
 T("Single-Agent-Systeme",
   "Ein Single-Agent-System hat genau einen Agenten, der alles erledigt. Einfach zu bauen und gut fuer klare Aufgaben.",
   ["Ein Agent macht alles",
    "Einfach und uebersichtlich",
    "Gut fuer klar umrissene Aufgaben",
    "Kann an Grenzen stossen bei Komplexem"],
   "single agent system LLM"),
 T("Multi-Agent-Systeme",
   "Bei Multi-Agent-Systemen arbeiten mehrere Agenten zusammen, jeder mit einer Rolle - wie ein Team mit Spezialisten.",
   ["Mehrere Agenten mit Rollen",
    "Beispiel: einer sucht, einer prueft, einer schreibt",
    "Koennen sich absprechen",
    "Maechtig, aber komplexer zu steuern"],
   "multi agent systems explained",
   gh=[("CrewAI", "https://github.com/crewAIInc/crewAI"),
       ("AutoGen", "https://github.com/microsoft/autogen")]),
 T("Agent Runtime",
   "Die Agent Runtime ist die Umgebung, in der ein Agent laeuft - sie fuehrt die Schritte aus, ruft Tools auf und haelt alles am Laufen.",
   ["Runtime = Laufzeitumgebung des Agenten",
    "Fuehrt den Denk-Handel-Loop aus",
    "Verwaltet Tools und Zustand",
    "Sorgt fuer stabilen Betrieb"],
   "agent runtime explained"),
 T("Agent State",
   "Der Agent State ist der aktuelle Zustand: was hat der Agent bisher getan, was weiss er gerade, wo steht er in der Aufgabe.",
   ["State = aktueller Stand der Aufgabe",
    "Speichert Zwischenergebnisse",
    "Wichtig fuer mehrstufige Aufgaben",
    "Muss sauber verwaltet werden"],
   "agent state management"),
 T("Agent Memory",
   "Agent Memory ist das Gedaechtnis: kurzfristig (aktuelles Gespraech) und langfristig (frueheres Wissen ueber den Kunden).",
   ["Short-term: aktuelles Gespraech",
    "Long-term: dauerhaftes Wissen",
    "Hilft, sich an Kunden zu erinnern",
    "Datenschutz beachten (was darf gespeichert werden)"],
   "agent memory LLM explained"),
 T("Agent Planning",
   "Planning heisst, dass der Agent einen Plan macht: er zerlegt ein Ziel in Schritte und arbeitet sie ab.",
   ["Ziel in Teilschritte zerlegen",
    "Reihenfolge festlegen",
    "Plan bei Bedarf anpassen",
    "Verhindert planloses Handeln"],
   "AI agent planning explained"),
 T("Agent Reasoning",
   "Reasoning beim Agenten heisst, dass er ueberlegt, warum er etwas tut und ob das Ergebnis passt, bevor er weitermacht.",
   ["Nachdenken vor dem Handeln",
    "Ergebnisse pruefen und bewerten",
    "Fehler erkennen und korrigieren",
    "Macht Agenten zuverlaessiger"],
   "agent reasoning explained"),
 T("Agent Tools",
   "Agent Tools sind die Werkzeuge, die der Agent nutzen darf: Suche, APIs, Datenbanken. Ohne Tools kann er nur reden.",
   ["Tools = Faehigkeiten des Agenten",
    "Beispiel: Kunden-API, Wissenssuche",
    "Klare Beschreibungen noetig",
    "Nur noetige Tools freigeben"],
   "agent tools explained"),
 T("Agent Workflows",
   "Ein Agent Workflow ist ein festgelegter Ablauf mit KI-Schritten. Anders als ein 'freier' Agent folgt er einer klaren Struktur.",
   ["Workflow = fester Ablauf mit KI-Schritten",
    "Vorhersehbarer als freie Agenten",
    "Gut fuer Standard-Prozesse",
    "Mischung aus Regeln und KI"],
   "agentic workflows explained",
   gh=[("LangGraph", "https://github.com/langchain-ai/langgraph")]),
 T("Loop Engineering",
   "Loop Engineering heisst, den Denk-Handel-Kreislauf des Agenten gut zu bauen: wann wiederholen, wann stoppen, wie Fehler abfangen.",
   ["Loop = wiederholter Denk-Handel-Kreislauf",
    "Abbruchbedingungen festlegen",
    "Endlosschleifen verhindern",
    "Schritt-Limit setzen"],
   "agent loop engineering"),
 T("AgentOps",
   "AgentOps ist der Betrieb von KI-Agenten: sie ueberwachen, verbessern und sicher am Laufen halten - wie DevOps, aber fuer Agenten.",
   ["Betrieb und Pflege von Agenten",
    "Ueberwachen, messen, verbessern",
    "Versionen und Aenderungen steuern",
    "Wichtig fuer Produktion"],
   "AgentOps explained"),
 T("Agent Observability",
   "Observability heisst 'Beobachtbarkeit': man kann sehen, was der Agent tut und warum - wichtig, um Fehler zu finden.",
   ["Einblick in das Verhalten des Agenten",
    "Logs, Metriken, Traces",
    "Fehler schneller finden",
    "Basis fuer Vertrauen"],
   "agent observability LLM",
   gh=[("Langfuse (LLM Observability)", "https://github.com/langfuse/langfuse")]),
 T("Agent Tracing",
   "Tracing zeichnet jeden Schritt des Agenten auf: welche Gedanken, welche Tools, welche Ergebnisse - wie ein Fahrtenschreiber.",
   ["Trace = Schritt-fuer-Schritt-Aufzeichnung",
    "Zeigt Tool-Aufrufe und Zwischenschritte",
    "Hilft beim Debugging",
    "Wichtig fuer Nachvollziehbarkeit"],
   "LLM tracing explained",
   gh=[("Langfuse", "https://github.com/langfuse/langfuse")]),
 T("Agent Debugging",
   "Debugging heisst Fehlersuche: wenn der Agent etwas falsch macht, findet man mit Traces und Logs die Ursache und behebt sie.",
   ["Fehler im Agenten finden und beheben",
    "Traces und Logs auswerten",
    "Prompt oder Tools anpassen",
    "Testfaelle nachstellen"],
   "debugging AI agents"),
 T("Agent Evaluation",
   "Agent Evaluation prueft mit Testfaellen, ob der Agent gute, sichere Ergebnisse liefert - bevor und waehrend er live ist.",
   ["Mit Testfaellen bewerten",
    "Erfolg, Korrektheit, Sicherheit messen",
    "Vor Release und laufend",
    "Vergleich verschiedener Versionen"],
   "agent evaluation methods"),
 T("Agent Guardrails",
   "Guardrails sind Leitplanken: Regeln, die verhindern, dass der Agent Verbotenes tut - z.B. keine Kontodaten preisgeben.",
   ["Leitplanken = feste Regeln/Grenzen",
    "Verbotene Aktionen blockieren",
    "Sensible Themen absichern",
    "In Banken unverzichtbar"],
   "AI agent guardrails explained",
   gh=[("NeMo Guardrails", "https://github.com/NVIDIA/NeMo-Guardrails"),
       ("Guardrails AI", "https://github.com/guardrails-ai/guardrails")]),
 T("Agent Mesh",
   "Ein Agent Mesh ist ein Netz aus vielen Agenten und Diensten, die zusammenarbeiten - eine Art Infrastruktur fuer viele Agenten.",
   ["Netzwerk vieler Agenten/Dienste",
    "Agenten finden und nutzen sich gegenseitig",
    "Fuer grosse Landschaften",
    "Braucht klare Regeln und Sicherheit"],
   "agent mesh architecture"),
 T("Agent-to-Agent Communication",
   "Damit Agenten zusammenarbeiten, muessen sie miteinander reden koennen - nach klaren Regeln, wer was fragt und antwortet.",
   ["Agenten tauschen Nachrichten aus",
    "Klare Rollen und Formate",
    "Beispiel: Such-Agent liefert an Antwort-Agent",
    "Standardisierung hilft (A2A)"],
   "agent to agent communication"),
 T("A2A Protocol",
   "A2A (Agent-to-Agent) ist ein Standard, wie verschiedene Agenten - auch von verschiedenen Anbietern - sicher miteinander sprechen.",
   ["A2A = Standard fuer Agenten-Kommunikation",
    "Anbieter-uebergreifend",
    "Ergaenzt MCP (Tools) um Agenten-Austausch",
    "Noch jung, aber wichtig fuer die Zukunft"],
   "A2A protocol agents explained",
   gh=[("A2A Projekt", "https://github.com/google/A2A")]),
 T("Human-in-the-loop",
   "Human-in-the-loop heisst, ein Mensch muss bei wichtigen Schritten zustimmen, bevor der Agent handelt - z.B. vor einer Ueberweisung.",
   ["Mensch bestaetigt kritische Schritte",
    "Agent wartet auf Freigabe",
    "Hoehere Sicherheit",
    "Pflicht bei riskanten Bank-Aktionen"],
   "human in the loop AI explained"),
 T("Human-on-the-loop",
   "Human-on-the-loop heisst, der Agent handelt selbst, aber ein Mensch schaut zu und kann jederzeit eingreifen oder stoppen.",
   ["Mensch ueberwacht, greift bei Bedarf ein",
    "Agent arbeitet selbststaendig",
    "Schneller als Human-in-the-loop",
    "Braucht gute Ueberwachung (Monitoring)"],
   "human on the loop AI"),
])

# ===========================================================================
# MODUL 13 - Sicherheit, Governance, Recht
# ===========================================================================
M("Sicherheit, Governance & Recht", "🛡️",
  "KI sicher, rechtlich sauber und verantwortungsvoll betreiben - Pflicht in Banken.",
[
 T("Guardrails",
   "Guardrails (Leitplanken) sind Regeln, die die KI davon abhalten, gefaehrliche oder verbotene Dinge zu tun oder zu sagen.",
   ["Regeln/Grenzen fuer KI-Verhalten",
    "Filtern verbotene Themen/Antworten",
    "Schuetzen Kunde und Bank",
    "Technisch und organisatorisch"],
   "AI guardrails explained deutsch",
   gh=[("Guardrails AI", "https://github.com/guardrails-ai/guardrails")]),
 T("AI Safety",
   "AI Safety heisst, KI so zu bauen und zu betreiben, dass sie Menschen nicht schadet und keine gefaehrlichen Fehler macht.",
   ["Sicherheit fuer Mensch und Betrieb",
    "Fehler und Missbrauch verhindern",
    "Grenzen klar definieren",
    "Testen, bevor es live geht"],
   "AI safety Grundlagen deutsch",
   art=[("Fraunhofer: Vertrauenswuerdige KI", "https://www.iis.fraunhofer.de/de/ff/ki.html")]),
 T("AI Governance",
   "AI Governance ist der Rahmen aus Regeln und Verantwortlichkeiten: Wer entscheidet ueber KI, wer haftet, welche Regeln gelten in der Firma.",
   ["Regeln und Zustaendigkeiten fuer KI",
    "Wer darf was, wer haftet",
    "Richtlinien und Freigaben",
    "Basis fuer sicheren KI-Einsatz"],
   "AI Governance erklaert deutsch",
   art=[("Bitkom: KI-Governance", "https://www.bitkom.org/Themen/Technologien-Software/Kuenstliche-Intelligenz")]),
 T("AI Risk Management",
   "AI Risk Management heisst, Gefahren durch KI zu erkennen, zu bewerten und zu verringern - z.B. Fehlberatung oder Datenpannen.",
   ["Risiken finden und bewerten",
    "Gegenmassnahmen festlegen",
    "Regelmaessig ueberpruefen",
    "Bank-Pflicht (Aufsicht/BaFin)"],
   "AI risk management framework",
   art=[("BaFin: KI in der Finanzwirtschaft", BAFIN),
        ("NIST AI Risk Management Framework", "https://www.nist.gov/itl/ai-risk-management-framework")]),
 T("AI Compliance",
   "AI Compliance heisst, dass der KI-Einsatz alle Gesetze und Regeln einhaelt - z.B. Datenschutz, Aufsichtsrecht, EU AI Act.",
   ["Einhaltung aller Regeln/Gesetze",
    "Betrifft Datenschutz, Aufsicht, EU AI Act",
    "Dokumentation und Nachweise",
    "Regelmaessige Audits"],
   "AI compliance banking",
   art=[("EU AI Act (offiziell, DE)", EU_ACT)]),
 T("EU AI Act",
   "Der EU AI Act ist das KI-Gesetz der EU. Es teilt KI in Risiko-Klassen ein und macht Vorgaben - je hoeher das Risiko, desto strenger.",
   ["EU-weites KI-Gesetz",
    "Risiko-Klassen: minimal bis verboten",
    "Hochrisiko braucht strenge Nachweise",
    "Banken oft im Hochrisiko-Bereich"],
   "EU AI Act einfach erklaert deutsch",
   ("EU AI Act (offiziell)", EU_ACT),
   art=[("EU-Kommission: KI-Gesetz", "https://digital-strategy.ec.europa.eu/de/policies/regulatory-framework-ai")]),
 T("DSGVO fuer KI-Systeme",
   "Die DSGVO ist das EU-Datenschutzgesetz. Bei KI heisst das: personenbezogene Daten nur mit Grund nutzen, sparsam und geschuetzt.",
   ["DSGVO = EU-Datenschutz-Grundverordnung",
    "Rechtsgrundlage noetig fuer Datennutzung",
    "Betroffenenrechte (Auskunft, Loeschung)",
    "Besonders sensibel bei Bankdaten"],
   "DSGVO KI einfach erklaert",
   ("DSGVO Gesetzestext (DE)", DSGVO),
   art=[("Datenschutzkonferenz: KI-Hinweise", "https://www.datenschutzkonferenz-online.de/")]),
 T("Datenschutz und Datenminimierung",
   "Datenminimierung heisst: nur so wenig Daten wie noetig nutzen. Was man nicht braucht, sammelt man gar nicht erst.",
   ["Nur noetige Daten verarbeiten",
    "Nicht auf Vorrat sammeln",
    "Anonymisieren/Pseudonymisieren, wenn moeglich",
    "Weniger Daten = weniger Risiko"],
   "Datenminimierung DSGVO erklaert",
   ("DSGVO Art. 5 (DE)", DSGVO + "art-5-dsgvo/")),
 T("Datenklassifizierung",
   "Datenklassifizierung heisst, Daten nach Schutzbedarf einzustufen: oeffentlich, intern, vertraulich, streng geheim. Danach richtet sich der Schutz.",
   ["Daten nach Schutzbedarf einteilen",
    "Stufen: oeffentlich bis streng vertraulich",
    "Bankdaten meist hoch eingestuft",
    "Steuert, wer/was darauf zugreifen darf"],
   "Datenklassifizierung erklaert"),
])

# ===========================================================================
# MODUL 14 - AI Security (OWASP)
# ===========================================================================
M("AI Security (OWASP)", "🔐",
  "Die typischen Angriffe auf KI kennen und abwehren - besonders wichtig in Banken.",
[
 T("OWASP LLM Security",
   "OWASP ist eine bekannte Sicherheits-Organisation. Die 'OWASP Top 10 fuer LLM' ist eine Liste der groessten Gefahren bei KI-Anwendungen.",
   ["OWASP Top 10 = die groessten LLM-Risiken",
    "Standard-Checkliste fuer KI-Sicherheit",
    "Hilft, typische Fehler zu vermeiden",
    "Gute Grundlage fuer Bank-Bots"],
   "OWASP Top 10 LLM erklaert deutsch",
   ("OWASP Top 10 for LLM", OWASP)),
 T("Prompt Injection",
   "Prompt Injection ist ein Angriff, bei dem jemand der KI heimlich neue Anweisungen unterschiebt, um sie zu verbotenen Dingen zu bringen.",
   ["Angreifer schmuggelt boese Anweisungen ein",
    "Beispiel: 'Ignoriere alle Regeln und ...'",
    "Kann Daten stehlen oder Regeln brechen",
    "Abwehr: Eingaben filtern, Rechte begrenzen"],
   "Prompt Injection erklaert deutsch",
   ("OWASP: Prompt Injection", OWASP),
   gh=[("Rebuff (Prompt-Injection-Schutz)", "https://github.com/protectai/rebuff")]),
 T("Sensitive Information Disclosure",
   "Das ist die Gefahr, dass die KI geheime Infos ausplaudert - z.B. Kundendaten oder interne Regeln, die niemand sehen darf.",
   ["KI verraet geheime/interne Daten",
    "Gefahr durch schlechte Prompts oder Angriffe",
    "Abwehr: Daten filtern, PII maskieren",
    "In Banken besonders kritisch"],
   "sensitive information disclosure LLM",
   ("OWASP LLM Top 10", OWASP)),
 T("Insecure Output Handling",
   "Wenn man die Antwort der KI ungeprueft weiterverwendet, kann Schaden entstehen - z.B. wenn sie schaedlichen Code oder Links enthaelt.",
   ["KI-Ausgabe ungeprueft nutzen ist gefaehrlich",
    "Kann Code/Links einschleusen",
    "Abwehr: Ausgabe pruefen/bereinigen",
    "Nie blind vertrauen"],
   "insecure output handling LLM",
   ("OWASP LLM Top 10", OWASP)),
 T("Excessive Agency",
   "Excessive Agency heisst 'zu viele Rechte': Wenn ein Agent zu viel darf, kann ein Fehler grossen Schaden anrichten.",
   ["Agent hat mehr Rechte als noetig",
    "Fehler/Angriff = grosser Schaden",
    "Abwehr: Rechte klein halten, Freigaben",
    "Human-in-the-loop bei kritischen Aktionen"],
   "excessive agency LLM explained",
   ("OWASP LLM Top 10", OWASP)),
 T("Model Denial of Service",
   "Beim Model DoS ueberlastet ein Angreifer die KI mit vielen/riesigen Anfragen, bis sie langsam oder teuer wird oder ausfaellt.",
   ["Ueberlastung durch viele/grosse Anfragen",
    "Folge: langsam, teuer, Ausfall",
    "Abwehr: Rate Limits, Groessen-Limits",
    "Kosten ueberwachen"],
   "model denial of service LLM",
   ("OWASP LLM Top 10", OWASP)),
 T("AI Red Teaming",
   "Red Teaming heisst, absichtlich wie ein Angreifer zu denken und die KI anzugreifen, um Schwachstellen zu finden, bevor es echte Angreifer tun.",
   ["Angreifer-Sicht einnehmen",
    "KI gezielt zu Fehlern verleiten",
    "Schwachstellen vor Live-Gang finden",
    "Regelmaessig wiederholen"],
   "AI red teaming explained",
   gh=[("Garak (LLM Vulnerability Scanner)", "https://github.com/NVIDIA/garak")]),
 T("AI Penetration Testing",
   "Pentesting ist ein gezielter, erlaubter Test-Angriff auf das KI-System, um Sicherheitsluecken zu finden und zu melden.",
   ["Erlaubter Test-Angriff",
    "Sucht Luecken systematisch",
    "Bericht mit Massnahmen",
    "Wichtig vor Bank-Einsatz"],
   "AI penetration testing"),
 T("AI Audit Logging",
   "Audit Logging heisst, alle wichtigen KI-Aktionen luekenlos aufzuzeichnen, damit man spaeter nachvollziehen kann, was passiert ist.",
   ["Wer/was/wann wird protokolliert",
    "Nachvollziehbarkeit fuer Pruefungen",
    "Wichtig fuer Aufsicht und Fehlersuche",
    "Logs sicher aufbewahren"],
   "AI audit logging"),
 T("AI Incident Management",
   "Incident Management heisst, auf KI-Zwischenfaelle vorbereitet zu sein: Was tun, wenn die KI Mist baut? Wer wird informiert, wie stoppt man sie?",
   ["Plan fuer KI-Zwischenfaelle",
    "Melden, eindaemmen, beheben",
    "Notaus (Kill Switch) bereit",
    "Aus Vorfaellen lernen"],
   "AI incident response plan"),
 T("AI Change Management",
   "Change Management heisst, Aenderungen an KI (neues Modell, neuer Prompt) geordnet einzufuehren: pruefen, freigeben, dokumentieren.",
   ["Aenderungen geordnet einfuehren",
    "Testen und freigeben vor Live",
    "Zurueckrollen (Rollback) moeglich",
    "Alles dokumentieren"],
   "AI change management"),
])

# ===========================================================================
# MODUL 15 - AI Ops, Qualitaet, Wirtschaftlichkeit
# ===========================================================================
M("AI Ops, Qualitaet & Nutzen", "📈",
  "KI im Betrieb ueberwachen, testen, versionieren und den Nutzen belegen.",
[
 T("AI Model Monitoring",
   "Model Monitoring heisst, die KI im Betrieb staendig zu beobachten: Ist sie noch gut, schnell und korrekt?",
   ["Laufende Ueberwachung der KI",
    "Qualitaet, Tempo, Kosten im Blick",
    "Alarm bei Verschlechterung",
    "Basis fuer schnelles Eingreifen"],
   "AI model monitoring",
   gh=[("Evidently AI (Monitoring)", "https://github.com/evidentlyai/evidently")]),
 T("Model Drift",
   "Model Drift heisst, dass die KI mit der Zeit schlechter wird, weil sich die Welt/Daten aendern - z.B. neue Produkte, neue Fragen.",
   ["KI passt nicht mehr zur neuen Realitaet",
    "Ursache: Daten/Welt aendern sich",
    "Erkennen durch Monitoring",
    "Gegenmittel: neu trainieren/anpassen"],
   "model drift explained deutsch"),
 T("Model Versioning",
   "Model Versioning heisst, jede Version des Modells zu benennen und aufzubewahren, damit man weiss, welche gerade laeuft und zurueck kann.",
   ["Jede Modell-Version benennen (z.B. v1, v2)",
    "Nachvollziehen, was live ist",
    "Zurueckrollen bei Problemen",
    "Wichtig fuer Nachweise"],
   "model versioning explained"),
 T("Prompt Versioning",
   "Prompt Versioning heisst dasselbe fuer Prompts: jede Prompt-Aenderung wird gespeichert, damit man vergleichen und zurueck kann.",
   ["Prompt-Aenderungen versionieren",
    "Vergleichen, welche Version besser ist",
    "Zurueckrollen moeglich",
    "Wie Code verwalten (Git)"],
   "prompt versioning",
   gh=[("Langfuse Prompt Management", "https://github.com/langfuse/langfuse")]),
 T("Knowledge Versioning",
   "Knowledge Versioning heisst, Aenderungen am Wissen (Artikel) nachzuhalten: Wer hat wann was geaendert, und zur alten Version zurueck.",
   ["Wissens-Aenderungen nachhalten",
    "Wer/wann/was geaendert",
    "Alte Version wiederherstellen",
    "Wichtig fuer korrekte Auskuenfte"],
   "knowledge base versioning"),
 T("AI Testing",
   "AI Testing heisst, die KI systematisch mit Testfaellen zu pruefen, bevor sie live geht - wie eine Qualitaetskontrolle.",
   ["Testfaelle vorbereiten",
    "Erwartete vs. echte Antwort vergleichen",
    "Automatisiert wiederholen",
    "Vor jedem Release"],
   "AI testing methods"),
 T("AI Evaluation",
   "AI Evaluation heisst, die Qualitaet der KI mit klaren Massstaeben zu bewerten - z.B. wie oft sie richtig liegt.",
   ["Qualitaet mit Kennzahlen messen",
    "Richtigkeit, Hilfreichheit, Sicherheit",
    "Menschliche und automatische Bewertung",
    "Vergleich von Versionen"],
   "AI evaluation metrics",
   gh=[("DeepEval (LLM Evaluation)", "https://github.com/confident-ai/deepeval")]),
 T("AI Quality Management",
   "Quality Management heisst, dauerhaft fuer gute KI-Qualitaet zu sorgen: messen, verbessern, Standards einhalten - ein Kreislauf.",
   ["Dauerhafter Qualitaets-Kreislauf",
    "Standards festlegen und pruefen",
    "Feedback einarbeiten",
    "Immer wieder verbessern"],
   "AI quality management"),
 T("AI Cost Monitoring",
   "Cost Monitoring heisst, die KI-Kosten im Blick zu behalten: Wie viele Tokens/Anfragen, was kostet das - damit es nicht teuer aus dem Ruder laeuft.",
   ["Kosten laufend ueberwachen",
    "Tokens und Anfragen zaehlen",
    "Budgets und Alarme setzen",
    "Guenstige Modelle wo moeglich"],
   "LLM cost monitoring"),
 T("AI ROI Berechnung",
   "ROI heisst Return on Investment: rechnet aus, ob sich die KI lohnt - was sie kostet gegen das, was sie einspart oder einbringt.",
   ["ROI = Nutzen im Verhaeltnis zu Kosten",
    "Einsparung (z.B. Agenten-Zeit) messen",
    "Kosten (Lizenz, Betrieb) gegenrechnen",
    "Zeigt, ob sich KI lohnt"],
   "AI ROI berechnen erklaert",
   art=[("McKinsey: Wert von GenAI", "https://www.mckinsey.com/de/publikationen"),
        ("BCG: KI Wertschoepfung", "https://www.bcg.com/publications")]),
 T("AI Business Case",
   "Ein Business Case ist die Begruendung, warum sich ein KI-Projekt lohnt: Problem, Loesung, Kosten, Nutzen und Risiken auf einen Blick.",
   ["Begruendung fuer ein KI-Projekt",
    "Problem + Loesung + Kosten + Nutzen",
    "Risiken ehrlich benennen",
    "Grundlage fuer die Entscheidung"],
   "AI business case erstellen",
   art=[("BCG: AI at Scale", "https://www.bcg.com/capabilities/artificial-intelligence")]),
])

# ===========================================================================
# MODUL 16 - Eigenen Bot bauen
# ===========================================================================
M("Eigenen Bot bauen", "🧱",
  "Von der Idee zum fertigen Bot - alle Bausteine eines eigenen KI-Bots.",
[
 T("Kendi Botunu Kurmak (Eigenen Bot aufsetzen)",
   "Hier lernst du Schritt fuer Schritt, einen eigenen Bot zu bauen: von der Idee ueber Technik bis zum Betrieb. Die naechsten Themen sind die Bausteine.",
   ["Ueberblick: was gehoert zu einem Bot",
    "Idee -> Bauen -> Testen -> Betreiben",
    "Bausteine: Frontend, Backend, Wissen, Sicherheit",
    "Klein anfangen, dann erweitern"],
   "eigenen chatbot bauen tutorial deutsch",
   gh=[("Chatbot UI (Open Source)", "https://github.com/mckaywrigley/chatbot-ui")]),
 T("Bot Architektur",
   "Die Bot-Architektur ist der Bauplan: welche Teile es gibt und wie sie zusammenspielen - Frontend, Backend, Wissen, KI-Modell.",
   ["Bauplan aller Bot-Teile",
    "Frontend (Chat) + Backend (Logik)",
    "KI-Modell + Wissensquelle",
    "Sicherheit von Anfang an mitdenken"],
   "chatbot architecture explained"),
 T("Bot Backend",
   "Das Backend ist das 'Gehirn im Hintergrund': es nimmt die Nachricht, ruft die KI und Tools auf und schickt die Antwort zurueck.",
   ["Backend = Server-Logik",
    "Verbindet Chat, KI, Wissen, APIs",
    "Regelt Ablauf und Sicherheit",
    "Meist in Python oder JavaScript"],
   "chatbot backend tutorial",
   gh=[("FastAPI (Python Backend)", "https://github.com/tiangolo/fastapi")]),
 T("Bot Frontend",
   "Das Frontend ist das, was der Kunde sieht: das Chat-Fenster mit Ein- und Ausgabe.",
   ["Frontend = sichtbare Oberflaeche",
    "Chat-Fenster fuer den Nutzer",
    "Web, App oder in Genesys eingebettet",
    "Einfach und klar gestalten"],
   "chatbot frontend tutorial"),
 T("Bot API Integration",
   "API Integration heisst, den Bot mit anderen Systemen zu verbinden (z.B. Bank-System), damit er echte Daten holen und Aktionen ausloesen kann.",
   ["Bot mit fremden Systemen verbinden",
    "Ueber deren APIs",
    "Beispiel: Kontostand, Ticket anlegen",
    "Sicher authentifizieren"],
   "chatbot API integration"),
 T("Bot Datenbank",
   "Die Datenbank speichert, was der Bot behalten muss: Gespraeche, Nutzerdaten, Einstellungen.",
   ["Speicher fuer Bot-Daten",
    "Beispiel: Gespraechsverlauf",
    "SQL oder NoSQL",
    "Datenschutz beachten"],
   "chatbot database design",
   gh=[("PostgreSQL", "https://github.com/postgres/postgres")]),
 T("Bot Knowledge Base",
   "Die Knowledge Base des Bots ist sein Wissen: die Artikel/Dokumente, aus denen er Antworten holt (siehe RAG).",
   ["Wissensquelle des Bots",
    "Artikel/Dokumente pflegen",
    "Wird ueber RAG genutzt",
    "Aktuell halten"],
   "chatbot knowledge base"),
 T("Bot RAG Pipeline",
   "Die RAG Pipeline ist der Wissens-Ablauf im Bot: Dokument laden, chunken, embedden, speichern, suchen, antworten.",
   ["Kompletter Wissens-Ablauf",
    "Laden -> Chunk -> Embedding -> Vector DB",
    "Suchen -> KI antwortet",
    "Herzstueck eines Wissens-Bots"],
   "build RAG pipeline tutorial",
   gh=[("LlamaIndex", "https://github.com/run-llama/llama_index"),
       ("LangChain", "https://github.com/langchain-ai/langchain")]),
 T("Bot Authentication",
   "Authentication heisst, sicherzustellen, wer der Nutzer ist - besonders wichtig, bevor der Bot sensible Bankdaten zeigt.",
   ["Nutzer sicher identifizieren",
    "Login/Verifizierung vor sensiblen Aktionen",
    "Nie ungeschuetzt Kontodaten zeigen",
    "Standards nutzen (OAuth)"],
   "chatbot authentication security"),
 T("Bot Logging",
   "Logging heisst, aufzuschreiben, was der Bot tut, um Fehler zu finden und Vorfaelle nachzuvollziehen (datenschutzkonform).",
   ["Aufzeichnen der Bot-Aktivitaet",
    "Hilft bei Fehlersuche",
    "PII vorsichtig behandeln",
    "Logs sicher speichern"],
   "chatbot logging best practices"),
 T("Bot Monitoring",
   "Monitoring heisst, den Bot im Betrieb zu ueberwachen: laeuft er, ist er schnell, sind die Antworten gut?",
   ["Live-Ueberwachung des Bots",
    "Verfuegbarkeit und Tempo",
    "Antwortqualitaet und Fehler",
    "Alarme bei Problemen"],
   "chatbot monitoring production"),
 T("Bot Deployment",
   "Deployment heisst, den Bot live zu schalten, damit echte Kunden ihn nutzen koennen - kontrolliert und ruecknehmbar.",
   ["Bot live schalten",
    "Erst Test, dann Produktion",
    "Schrittweise ausrollen",
    "Rollback moeglich"],
   "bot deployment tutorial",
   gh=[("Docker", "https://github.com/docker")]),
 T("Bot Hosting",
   "Hosting heisst, wo der Bot laeuft: in der Cloud oder auf eigenen Servern. In Banken oft mit strengen Vorgaben.",
   ["Wo laeuft der Bot (Cloud/On-Prem)",
    "Cloud: schnell, flexibel",
    "On-Prem: mehr Kontrolle",
    "Bank-Vorgaben beachten (Region, Datenschutz)"],
   "bot hosting options"),
 T("Bot Security",
   "Bot Security fasst alle Schutzmassnahmen zusammen: Angriffe abwehren, Daten schuetzen, Rechte begrenzen.",
   ["Gesamter Schutz des Bots",
    "Gegen Prompt Injection & Co.",
    "Daten und Zugriffe absichern",
    "Regelmaessig pruefen"],
   "chatbot security best practices",
   ("OWASP LLM Top 10", OWASP)),
 T("Bot Testing",
   "Bot Testing heisst, den Bot vor und nach Live gruendlich zu pruefen: versteht er richtig, antwortet er korrekt, ist er sicher?",
   ["Systematisch testen",
    "Verstehen, Antworten, Sicherheit",
    "Auch Grenzfaelle",
    "Vor jedem Release"],
   "chatbot testing"),
 T("Bot Training",
   "Bot Training heisst, dem Bot mit Beispielen und Wissen beizubringen, gute Antworten zu geben, und ihn laufend nachzubessern.",
   ["Mit Beispielen/Wissen trainieren",
    "Fehler ansehen und nachbessern",
    "Regelmaessig wiederholen",
    "Echte Gespraeche nutzen"],
   "chatbot training tutorial"),
 T("Bot Fine-Tuning",
   "Fine-Tuning heisst, ein KI-Modell mit eigenen Beispielen nachzuschaerfen, damit es besser zum eigenen Fall passt (nur wenn noetig).",
   ["Modell mit eigenen Daten nachschulen",
    "Fuer speziellen Stil/Fachwissen",
    "Aufwendig - oft reicht RAG",
    "Datenschutz bei Trainingsdaten beachten"],
   "fine-tuning LLM erklaert",
   gh=[("Hugging Face PEFT (LoRA)", "https://github.com/huggingface/peft")]),
 T("Bot Personality",
   "Die Bot Personality ist der 'Charakter' des Bots: freundlich, sachlich, hilfsbereit - passend zur Bank.",
   ["Charakter/Auftreten des Bots",
    "Passend zur Marke der Bank",
    "Konsistent halten",
    "Im Prompt festlegen"],
   "chatbot personality design"),
 T("Bot Tone of Voice",
   "Der Tone of Voice ist der Ton: wie der Bot spricht - hoeflich, klar, nicht zu locker. In Banken eher serioes und einfach.",
   ["Sprachstil des Bots",
    "Hoeflich, klar, verstaendlich",
    "Einheitlich in allen Antworten",
    "Fachbegriffe erklaeren"],
   "chatbot tone of voice"),
 T("Bot Fallback Design",
   "Fallback Design heisst, gut zu planen, was der Bot tut, wenn er nicht weiterweiss: hoeflich nachfragen oder weiterleiten.",
   ["Plan fuer 'weiss nicht weiter'",
    "Freundlich nachfragen",
    "Nach X Versuchen weiterleiten",
    "Nie den Kunden im Stich lassen"],
   "chatbot fallback design"),
 T("Bot Handover Design",
   "Handover heisst Uebergabe an einen Menschen: der Bot reicht das Gespraech samt Verlauf sauber an einen Agent weiter.",
   ["Uebergabe an echten Agent",
    "Gespraechsverlauf mitgeben",
    "Klar ankuendigen ('Ich verbinde Sie')",
    "Nahtlos, ohne Wiederholung"],
   "chatbot human handover"),
 T("Bot Analytics",
   "Bot Analytics zeigt in Zahlen, wie gut der Bot laeuft: Wie viele Anliegen loest er allein, wo bricht es ab?",
   ["Kennzahlen des Bots",
    "Containment (allein geloest)",
    "Abbrueche und No Matches",
    "Grundlage fuer Verbesserung"],
   "chatbot analytics metrics"),
 T("Bot Continuous Improvement",
   "Continuous Improvement heisst staendige Verbesserung: aus echten Gespraechen lernen und den Bot Woche fuer Woche besser machen.",
   ["Staendige Verbesserung (Kreislauf)",
    "Aus echten Daten lernen",
    "Regelmaessig Wissen/Intents pflegen",
    "Nie 'fertig'"],
   "chatbot continuous improvement"),
])

# ===========================================================================
# MODUL 17 - Private / Lokale AI
# ===========================================================================
M("Private & lokale AI", "🏠",
  "KI im eigenen Haus betreiben - fuer maximalen Datenschutz in Banken.",
[
 T("Private AI",
   "Private AI heisst, KI so zu nutzen, dass Daten die eigene Kontrolle nicht verlassen - wichtig bei sensiblen Bankdaten.",
   ["Daten bleiben unter eigener Kontrolle",
    "Kein Abfluss an fremde Anbieter",
    "Fuer sensible Bereiche",
    "Kann Cloud (privat) oder lokal sein"],
   "private AI erklaert deutsch"),
 T("Local AI",
   "Local AI heisst, die KI laeuft auf dem eigenen Rechner/Server statt in einer fremden Cloud. Volle Kontrolle, aber eigene Hardware noetig.",
   ["KI laeuft lokal/im eigenen Haus",
    "Keine Daten nach aussen",
    "Braucht eigene Rechenleistung",
    "Gut fuer Datenschutz"],
   "local AI setup tutorial",
   gh=[("Ollama", "https://github.com/ollama/ollama")]),
 T("On-Prem AI",
   "On-Prem (On-Premises) heisst 'im eigenen Rechenzentrum'. Die Bank betreibt die KI selbst, hinter der eigenen Firewall.",
   ["KI im eigenen Rechenzentrum",
    "Hinter der Firewall der Bank",
    "Volle Kontrolle und Compliance",
    "Mehr Aufwand fuer Betrieb"],
   "on-premise AI deployment"),
 T("Open-Source LLMs",
   "Open-Source LLMs sind frei verfuegbare KI-Modelle, die man selbst herunterladen und betreiben kann - z.B. Llama oder Mistral.",
   ["Frei nutzbare KI-Modelle",
    "Selbst hosten moeglich",
    "Beispiele: Llama, Mistral, Qwen",
    "Gut fuer private/lokale AI"],
   "open source LLM erklaert",
   gh=[("Hugging Face Modelle", "https://github.com/huggingface"),
       ("Ollama", "https://github.com/ollama/ollama")]),
 T("Ollama",
   "Ollama ist ein einfaches Programm, um Open-Source-KI-Modelle mit wenigen Befehlen lokal auf dem eigenen Rechner zu starten.",
   ["Einfaches Tool fuer lokale LLMs",
    "Ein Befehl: Modell laden und chatten",
    "Laeuft auf Mac, Windows, Linux",
    "Gut fuer erste Versuche mit Local AI"],
   "Ollama tutorial deutsch",
   gh=[("Ollama", "https://github.com/ollama/ollama")]),
 T("llama.cpp",
   "llama.cpp ist ein sehr effizientes Programm, um KI-Modelle auch auf normaler Hardware (sogar ohne teure GPU) laufen zu lassen.",
   ["Laesst LLMs effizient laufen",
    "Auch auf CPU/normaler Hardware",
    "Basis vieler lokaler Tools",
    "Sehr beliebt in der Open-Source-Welt"],
   "llama.cpp tutorial",
   gh=[("llama.cpp", "https://github.com/ggerganov/llama.cpp")]),
 T("Hugging Face Models",
   "Hugging Face ist eine grosse Plattform mit tausenden frei verfuegbaren KI-Modellen zum Herunterladen und Ausprobieren.",
   ["Grosse Sammlung freier KI-Modelle",
    "Modelle, Datensaetze, Tools",
    "Zum Herunterladen und Testen",
    "Bekannteste Open-Source-KI-Plattform"],
   "Hugging Face tutorial deutsch",
   gh=[("Transformers (Hugging Face)", "https://github.com/huggingface/transformers")]),
 T("Fine-Tuning",
   "Fine-Tuning heisst, ein fertiges Modell mit eigenen Beispielen nachzuschulen, damit es besser zur eigenen Aufgabe passt.",
   ["Modell mit eigenen Daten nachschulen",
    "Fuer speziellen Stil/Fachwissen",
    "Braucht gute Trainingsdaten",
    "Oft reicht aber RAG"],
   "fine-tuning LLM tutorial",
   gh=[("Hugging Face PEFT", "https://github.com/huggingface/peft")]),
 T("LoRA",
   "LoRA ist eine guenstige Art des Fine-Tunings: man schult nur einen kleinen Zusatz-Teil des Modells, nicht das ganze - spart viel Aufwand.",
   ["LoRA = sparsames Fine-Tuning",
    "Nur kleiner Zusatz wird trainiert",
    "Weniger Rechenleistung noetig",
    "Beliebt fuer eigene Modelle"],
   "LoRA fine-tuning erklaert",
   gh=[("Hugging Face PEFT (LoRA)", "https://github.com/huggingface/peft")]),
 T("Quantization",
   "Quantization heisst, ein Modell zu 'verkleinern', indem man die Zahlen vergroebert. Es wird kleiner und schneller, mit nur wenig Qualitaetsverlust.",
   ["Modell kleiner/schneller machen",
    "Zahlen mit weniger Genauigkeit",
    "Laeuft dann auf schwaecherer Hardware",
    "Wenig Qualitaetsverlust"],
   "quantization LLM erklaert"),
 T("Model Serving",
   "Model Serving heisst, ein KI-Modell so bereitzustellen, dass Programme es ueber eine API abfragen koennen - stabil und schnell.",
   ["Modell als API bereitstellen",
    "Fuer viele Anfragen ausgelegt",
    "Stabil und schnell",
    "Basis fuer den Produktivbetrieb"],
   "model serving explained",
   gh=[("vLLM (schnelles Serving)", "https://github.com/vllm-project/vllm")]),
 T("Inference Server",
   "Ein Inference Server ist der Server, der die KI-Antworten berechnet (Inference = das 'Ausrechnen' einer Antwort).",
   ["Server, der KI-Antworten berechnet",
    "Inference = Antwort erzeugen",
    "Optimiert fuer Tempo/Durchsatz",
    "Beispiele: vLLM, TGI"],
   "inference server explained",
   gh=[("Text Generation Inference", "https://github.com/huggingface/text-generation-inference")]),
 T("GPU Grundlagen",
   "Eine GPU ist ein spezieller Rechen-Chip, der viele Rechnungen gleichzeitig macht. KI braucht GPUs, um schnell zu sein.",
   ["GPU = schneller Parallel-Rechner",
    "KI rechnet damit viel schneller",
    "Teuer, aber wichtig fuer grosse Modelle",
    "VRAM (Speicher) begrenzt die Modellgroesse"],
   "GPU fuer KI einfach erklaert"),
 T("CPU Inference",
   "CPU Inference heisst, die KI auf einem normalen Prozessor (CPU) laufen zu lassen - guenstiger, aber langsamer als mit GPU.",
   ["KI auf normaler CPU laufen lassen",
    "Guenstiger, aber langsamer",
    "Gut fuer kleine Modelle (SLM)",
    "Mit Quantization machbar"],
   "CPU inference LLM"),
])

# ===========================================================================
# MODUL 18 - Orchestration & Cloud-Plattformen
# ===========================================================================
M("AI Orchestration & Plattformen", "🧩",
  "Werkzeuge und Plattformen, mit denen man KI-Anwendungen zusammensetzt.",
[
 T("AI Orchestration",
   "AI Orchestration heisst, mehrere KI-Bausteine und Schritte zu einem sinnvollen Ablauf zu verbinden - wie ein Dirigent, der das Orchester fuehrt.",
   ["Bausteine zu einem Ablauf verbinden",
    "Modell + Tools + Wissen + Logik",
    "Steuert die Reihenfolge",
    "Frameworks helfen dabei"],
   "AI orchestration erklaert",
   gh=[("LangChain", "https://github.com/langchain-ai/langchain")]),
 T("LangChain",
   "LangChain ist ein beliebtes Werkzeug (Framework), um KI-Anwendungen zu bauen: es verbindet Modelle, Wissen und Tools mit fertigen Bausteinen.",
   ["Framework fuer KI-Apps",
    "Fertige Bausteine (Chains)",
    "Verbindet Modelle, RAG, Tools",
    "Sehr grosse Community"],
   "LangChain tutorial deutsch",
   gh=[("LangChain", "https://github.com/langchain-ai/langchain")]),
 T("LangGraph",
   "LangGraph baut auf LangChain auf und ist fuer Agenten mit mehreren Schritten und Schleifen gedacht - als klarer, steuerbarer Ablauf-Graph.",
   ["Fuer mehrstufige Agenten/Workflows",
    "Ablauf als steuerbarer Graph",
    "Gut kontrollierbar",
    "Von den LangChain-Machern"],
   "LangGraph tutorial",
   gh=[("LangGraph", "https://github.com/langchain-ai/langgraph")]),
 T("LlamaIndex",
   "LlamaIndex ist ein Framework, das besonders gut darin ist, eigene Dokumente fuer RAG vorzubereiten und durchsuchbar zu machen.",
   ["Framework speziell fuer RAG",
    "Dokumente laden, chunken, indexieren",
    "Einfache Wissens-Suche",
    "Gut fuer Wissens-Bots"],
   "LlamaIndex tutorial",
   gh=[("LlamaIndex", "https://github.com/run-llama/llama_index")]),
 T("CrewAI",
   "CrewAI ist ein Framework fuer Multi-Agent-Systeme: man gibt mehreren Agenten Rollen (wie ein Team), die zusammen eine Aufgabe loesen.",
   ["Framework fuer mehrere Agenten",
    "Agenten mit Rollen wie ein Team",
    "Aufgaben aufteilen",
    "Einfach zu starten"],
   "CrewAI tutorial",
   gh=[("CrewAI", "https://github.com/crewAIInc/crewAI")]),
 T("AutoGen",
   "AutoGen ist ein Framework von Microsoft, mit dem mehrere Agenten miteinander reden und gemeinsam Aufgaben loesen koennen.",
   ["Microsoft-Framework fuer Agenten",
    "Agenten unterhalten sich",
    "Loesen Aufgaben gemeinsam",
    "Fuer komplexere Faelle"],
   "AutoGen tutorial",
   gh=[("AutoGen", "https://github.com/microsoft/autogen")]),
 T("n8n AI Automation",
   "n8n ist ein Baukasten, um Ablaeufe ohne viel Programmieren zu automatisieren (Low-Code) - auch mit KI-Schritten, per Drag-and-drop.",
   ["Low-Code Automatisierung",
    "Bausteine per Drag-and-drop",
    "Kann KI-Schritte einbauen",
    "Gut fuer schnelle Automationen"],
   "n8n AI automation tutorial deutsch",
   gh=[("n8n", "https://github.com/n8n-io/n8n")]),
 T("Flowise",
   "Flowise ist ein Werkzeug, mit dem man KI-Bots und RAG-Ablaeufe visuell zusammenklickt, ohne zu programmieren.",
   ["Visueller Baukasten fuer KI-Bots",
    "RAG und Agenten per Klick",
    "Baut auf LangChain auf",
    "Gut zum Ausprobieren"],
   "Flowise tutorial",
   gh=[("Flowise", "https://github.com/FlowiseAI/Flowise")]),
 T("Dify",
   "Dify ist eine Plattform, um KI-Apps und Bots zu bauen und zu betreiben - mit Oberflaeche fuer Prompts, Wissen und Betrieb.",
   ["Plattform fuer KI-Apps/Bots",
    "Prompts, RAG, Betrieb an einem Ort",
    "Auch selbst hostbar",
    "Gut fuer Teams"],
   "Dify tutorial",
   gh=[("Dify", "https://github.com/langgenius/dify")]),
 T("Microsoft Copilot Studio",
   "Copilot Studio ist das Microsoft-Werkzeug, um Bots und Copilots zu bauen - besonders praktisch, wenn die Firma Microsoft nutzt.",
   ["Microsofts Bot-/Copilot-Baukasten",
    "Gut in Microsoft-Welt integriert",
    "Wenig Programmieren noetig",
    "Fuer Firmen mit M365"],
   "Copilot Studio tutorial deutsch",
   ("Microsoft Learn: Copilot Studio", "https://learn.microsoft.com/de-de/microsoft-copilot-studio/")),
 T("Azure AI Foundry",
   "Azure AI Foundry ist die KI-Plattform von Microsoft in der Azure-Cloud, um KI-Modelle und -Apps zu bauen und zu betreiben.",
   ["Microsofts KI-Plattform (Azure)",
    "Modelle nutzen und Apps bauen",
    "Fuer groessere Projekte",
    "Enterprise-Funktionen"],
   "Azure AI Foundry overview",
   ("Microsoft Learn: Azure AI", "https://learn.microsoft.com/de-de/azure/ai-foundry/")),
 T("AWS Bedrock",
   "AWS Bedrock ist die KI-Plattform von Amazon: man kann verschiedene KI-Modelle ueber die AWS-Cloud nutzen, ohne sie selbst zu betreiben.",
   ["Amazons KI-Plattform (AWS)",
    "Viele Modelle ueber eine API",
    "Kein eigener Modell-Betrieb noetig",
    "Fuer AWS-Kunden praktisch"],
   "AWS Bedrock tutorial",
   ("AWS: Bedrock", "https://aws.amazon.com/de/bedrock/")),
 T("Google Vertex AI",
   "Vertex AI ist die KI-Plattform von Google in der Google Cloud, um Modelle (z.B. Gemini) zu nutzen und KI-Apps zu bauen.",
   ["Googles KI-Plattform (Google Cloud)",
    "Gemini-Modelle nutzen",
    "Apps bauen und betreiben",
    "Fuer Google-Cloud-Kunden"],
   "Google Vertex AI tutorial",
   ("Google Cloud: Vertex AI", "https://cloud.google.com/vertex-ai?hl=de")),
 T("OpenAI API",
   "Die OpenAI API gibt Zugriff auf die GPT-Modelle. Programme koennen darueber Texte erzeugen, zusammenfassen oder Fragen beantworten lassen.",
   ["Zugriff auf GPT-Modelle per API",
    "Fuer Text, Chat, Tools",
    "Einfach zu starten",
    "Kosten pro Token beachten"],
   "OpenAI API tutorial deutsch",
   ("OpenAI Doku", "https://platform.openai.com/docs")),
 T("Anthropic Claude API",
   "Die Anthropic Claude API gibt Zugriff auf die Claude-Modelle - stark bei langen Texten, Tool Use und sicherem, hilfreichem Verhalten.",
   ["Zugriff auf Claude-Modelle per API",
    "Gut fuer lange Texte und Tools",
    "Fokus auf Sicherheit/Hilfreichheit",
    "Unterstuetzt MCP und Tool Use"],
   "Anthropic Claude API tutorial",
   ("Anthropic Doku", "https://docs.anthropic.com/"),
   gh=[("Anthropic SDK (Python)", "https://github.com/anthropics/anthropic-sdk-python"),
       ("Anthropic Cookbook", "https://github.com/anthropics/anthropic-cookbook")]),
])

# ===========================================================================
# MODUL 19 - AI Anwendungen & Bank-Use-Cases
# ===========================================================================
M("AI Anwendungen & Bank-Use-Cases", "🏛️",
  "Wo KI im Contact Center und in der Bank konkret hilft.",
[
 T("AI App Architektur",
   "Die AI App Architektur ist der Gesamt-Bauplan einer KI-Anwendung: Oberflaeche, Logik, KI-Modell, Wissen und Sicherheit - sauber verbunden.",
   ["Gesamt-Bauplan einer KI-App",
    "Frontend + Backend + Modell + Wissen",
    "Sicherheit und Datenschutz eingebaut",
    "Skalierbar planen"],
   "AI application architecture"),
 T("AI Workflow Automation",
   "Hier automatisiert KI ganze Arbeitsablaeufe: sie erledigt wiederkehrende Schritte selbst und uebergibt nur Ausnahmen an Menschen.",
   ["KI automatisiert Ablaeufe",
    "Wiederkehrende Aufgaben ohne Mensch",
    "Ausnahmen an Menschen",
    "Spart Zeit und Fehler"],
   "AI workflow automation banking",
   gh=[("n8n", "https://github.com/n8n-io/n8n")]),
 T("AI Document Processing",
   "KI liest und versteht Dokumente automatisch - z.B. Vertraege oder Ausweise - und holt die wichtigen Infos heraus.",
   ["Dokumente automatisch verstehen",
    "Wichtige Felder herausziehen",
    "Beispiel: Antrag, Rechnung, Ausweis",
    "Spart manuelles Abtippen"],
   "AI document processing"),
 T("AI OCR",
   "OCR (Optical Character Recognition) macht aus einem Foto/Scan lesbaren Text. KI-OCR erkennt sogar schwierige Vorlagen.",
   ["OCR = Text aus Bild/Scan erkennen",
    "Aus Foto wird lesbarer Text",
    "Beispiel: gescannter Antrag",
    "Basis fuer Dokumenten-Verarbeitung"],
   "OCR einfach erklaert deutsch"),
 T("AI Speech-to-Text",
   "Speech-to-Text (STT) macht aus gesprochener Sprache Text. So kann ein Voice Bot verstehen, was der Kunde sagt.",
   ["STT = Gesprochenes zu Text",
    "Basis fuer Voice Bots",
    "Auch fuer Gespraechs-Auswertung",
    "Qualitaet haengt von Audio ab"],
   "speech to text erklaert deutsch"),
 T("AI Text-to-Speech",
   "Text-to-Speech (TTS) macht aus Text gesprochene Sprache. So kann ein Voice Bot dem Kunden antworten.",
   ["TTS = Text zu Sprache",
    "Bot 'spricht' mit dem Kunden",
    "Natuerliche Stimmen moeglich",
    "Gegenstueck zu STT"],
   "text to speech erklaert deutsch"),
 T("AI Voice Bot",
   "Ein AI Voice Bot ist ein sprechender Bot am Telefon: er versteht (STT), denkt (KI) und antwortet (TTS) - ganz ohne Menschen.",
   ["Sprechender Bot am Telefon",
    "STT + KI + TTS zusammen",
    "Loest einfache Anliegen automatisch",
    "Uebergibt bei Bedarf an Agent"],
   "AI voice bot banking"),
 T("AI Translation",
   "KI-Uebersetzung uebersetzt live zwischen Sprachen. So kann ein Agent auch Kunden helfen, deren Sprache er nicht spricht.",
   ["Automatische Uebersetzung",
    "Live im Chat/Gespraech",
    "Mehr Kunden erreichbar",
    "Qualitaet pruefen bei Rechtsthemen"],
   "AI translation live chat"),
 T("AI Summarization",
   "KI-Zusammenfassung macht aus langem Text kurze Kernaussagen - z.B. eine lange Kunden-Historie in drei Saetzen.",
   ["Lange Texte kurz zusammenfassen",
    "Beispiel: Gespraechs-Zusammenfassung",
    "Spart Lesezeit",
    "Kernaussagen behalten"],
   "AI summarization erklaert"),
 T("AI Classification",
   "KI-Klassifizierung sortiert Dinge automatisch in Kategorien - z.B. ordnet sie E-Mails den richtigen Abteilungen zu.",
   ["Automatisch in Kategorien einsortieren",
    "Beispiel: Anliegen -> Abteilung",
    "Schnell und einheitlich",
    "Basis fuer smartes Routing"],
   "AI text classification erklaert"),
 T("AI Sentiment Analysis",
   "Sentiment Analysis erkennt die Stimmung im Text: positiv, neutral oder negativ - so sieht man, ob ein Kunde veraergert ist.",
   ["Stimmung im Text erkennen",
    "Positiv / neutral / negativ",
    "Warnung bei Aerger",
    "Hilft, Eskalationen zu vermeiden"],
   "sentiment analysis erklaert deutsch"),
 T("AI Emotion Detection",
   "Emotion Detection erkennt Gefuehle (z.B. Wut, Sorge) in Stimme oder Text - so kann man besonders sensibel reagieren.",
   ["Gefuehle erkennen (Wut, Sorge ...)",
    "In Text oder Stimme",
    "Fuer einfuehlsame Reaktion",
    "Datenschutz beachten"],
   "emotion detection AI"),
 T("AI Fraud Detection",
   "Fraud Detection heisst Betrugserkennung: KI erkennt verdaechtige Muster (z.B. seltsame Ueberweisungen) und schlaegt Alarm.",
   ["Betrug/Missbrauch erkennen",
    "Ungewoehnliche Muster finden",
    "Alarm in Echtzeit",
    "Sehr wichtig in Banken"],
   "AI fraud detection banking",
   art=[("BaFin: Betrugspraevention & KI", BAFIN)]),
 T("AI Recommendation Systems",
   "Empfehlungssysteme schlagen passende Dinge vor - z.B. das richtige Produkt oder den naechsten Schritt fuer den Kunden.",
   ["Passende Vorschlaege machen",
    "Beispiel: passendes Produkt/Angebot",
    "Auf Basis von Daten/Verhalten",
    "Hilft Kunden und Vertrieb"],
   "recommendation systems erklaert"),
 T("AI Search",
   "AI Search ist eine intelligente Suche, die die Bedeutung versteht (semantisch) und so bessere Treffer liefert als reine Wortsuche.",
   ["Intelligente, sinn-verstehende Suche",
    "Bessere Treffer als Wortsuche",
    "Grundlage: Embeddings",
    "Fuer Kunden und Agenten"],
   "AI search semantic"),
 T("AI Knowledge Management",
   "KI-Wissensmanagement heisst, Firmenwissen mit KI zu ordnen, auffindbar zu machen und aktuell zu halten.",
   ["Wissen mit KI ordnen/auffindbar machen",
    "Aktuell und konsistent halten",
    "Fuer Bot, Agent, Self-Service",
    "Basis guter Auskuenfte"],
   "AI knowledge management"),
 T("AI Customer Service Automation",
   "Hier automatisiert KI den Kundenservice: Bots loesen Standardfaelle, Menschen kuemmern sich um das Schwierige.",
   ["KI automatisiert Kundenservice",
    "Bots fuer Standardfaelle",
    "Menschen fuer Komplexes",
    "Rund um die Uhr erreichbar"],
   "AI customer service automation"),
 T("AI Agent Assist",
   "AI Agent Assist unterstuetzt den menschlichen Agent live: sie schlaegt Antworten und Wissen vor, waehrend er mit dem Kunden spricht.",
   ["Live-Hilfe fuer den Agent",
    "Antworten und Wissen vorschlagen",
    "Schneller und sicherer arbeiten",
    "Siehe auch Genesys Agent Assist"],
   "AI agent assist"),
 T("AI Copilot Systeme",
   "Ein AI Copilot ist ein KI-Assistent, der einem Mitarbeiter zur Seite steht und mitdenkt - beim Schreiben, Suchen und Entscheiden.",
   ["KI-Assistent fuer Mitarbeiter",
    "Denkt mit, schlaegt vor",
    "Beispiel: Agent Copilot",
    "Mensch behaelt Kontrolle"],
   "AI copilot systems"),
 T("AI Banking Use Cases",
   "Hier eine Uebersicht, wo KI in der Bank hilft: Service, Betrug, Kredit, Karten, Online-Banking, Reporting.",
   ["Ueberblick der Bank-Einsatzfelder",
    "Service, Betrug, Kredit, Karten",
    "Immer mit Datenschutz/Compliance",
    "Klein starten, dann ausweiten"],
   "AI use cases banking deutsch",
   art=[("Bitkom: KI in Banken", "https://www.bitkom.org/Themen/Technologien-Software/Kuenstliche-Intelligenz")]),
 T("AI Contact Center Use Cases",
   "Im Contact Center hilft KI beim Routing, mit Bots, Agent Assist, Zusammenfassungen und Auswertungen.",
   ["Smart Routing und Bots",
    "Agent Assist und Copilot",
    "Zusammenfassungen und Analyse",
    "Kuerzere Wartezeiten"],
   "AI contact center use cases"),
 T("AI Service Desk Use Cases",
   "Am Service Desk (interne IT-Hilfe) loest KI haeufige Fragen (Passwort, Zugriff) automatisch und entlastet die IT.",
   ["Interne IT-Hilfe automatisieren",
    "Beispiel: Passwort zuruecksetzen",
    "Haeufige Tickets automatisch loesen",
    "Entlastet die IT"],
   "AI service desk automation"),
 T("AI Beschwerdemanagement",
   "KI hilft bei Beschwerden: sie erkennt Aerger frueh, sortiert die Beschwerde richtig ein und schlaegt Loesungen vor.",
   ["Beschwerden schneller bearbeiten",
    "Aerger frueh erkennen (Sentiment)",
    "Richtig einsortieren und priorisieren",
    "Loesungsvorschlaege liefern"],
   "AI Beschwerdemanagement"),
 T("AI Kreditprozess Unterstuetzung",
   "KI unterstuetzt beim Kredit: sie liest Unterlagen, prueft auf Vollstaendigkeit und hilft (nur unterstuetzend) bei der Einschaetzung.",
   ["Kredit-Unterlagen automatisch pruefen",
    "Vollstaendigkeit checken",
    "Unterstuetzt - Entscheidung bleibt beim Menschen",
    "EU AI Act: oft Hochrisiko - streng regeln"],
   "AI Kreditprozess Bank",
   art=[("EU AI Act (Hochrisiko)", EU_ACT)]),
 T("AI Kartenservice Unterstuetzung",
   "Beim Kartenservice hilft KI: Karte sperren, Ersatz bestellen, Umsaetze erklaeren - vieles automatisch und rund um die Uhr.",
   ["Karte sperren/ersetzen automatisieren",
    "Umsaetze erklaeren",
    "24/7 erreichbar",
    "Sicherheit vor sensiblen Aktionen"],
   "AI Kartenservice Bank"),
 T("AI Online-Banking Support",
   "KI hilft im Online-Banking: sie beantwortet Fragen zur Bedienung, hilft beim Login-Problem und fuehrt Schritt fuer Schritt.",
   ["Hilfe zur Online-Banking-Bedienung",
    "Login-Probleme loesen",
    "Schritt-fuer-Schritt-Anleitung",
    "Entlastet die Hotline"],
   "AI online banking support"),
 T("AI Depotservice Support",
   "Beim Depot (Wertpapiere) beantwortet KI allgemeine Fragen und erklaert Ablaeufe - Anlageberatung bleibt aber beim Menschen.",
   ["Allgemeine Depot-Fragen beantworten",
    "Ablaeufe erklaeren",
    "Keine Anlageberatung durch Bot",
    "Rechtliche Grenzen beachten"],
   "AI Depot Wertpapier Support"),
 T("AI Fraud Support",
   "Im Betrugsfall hilft KI: sie erkennt Verdachtsfaelle, informiert den Kunden schnell und leitet Sofortmassnahmen ein.",
   ["Verdachtsfaelle schnell erkennen",
    "Kunde sofort informieren",
    "Massnahmen einleiten (z.B. sperren)",
    "Eng mit Fraud Detection verbunden"],
   "AI fraud support banking"),
 T("AI Management Reporting",
   "KI erstellt Berichte fuer die Fuehrung: sie fasst Zahlen zusammen, erklaert Entwicklungen und spart das manuelle Zusammentragen.",
   ["Berichte fuer die Fuehrung erstellen",
    "Zahlen zusammenfassen und erklaeren",
    "Spart manuelle Arbeit",
    "Schnellere Entscheidungen"],
   "AI management reporting"),
])

# ===========================================================================
# MODUL 20 - Ergaenzende Themen (von mir hinzugefuegt)
# ===========================================================================
M("Ergaenzende Themen (empfohlen)", "➕",
  "Wichtige Themen, die zusaetzlich helfen und in keiner Liste fehlen sollten.",
[
 T("Conversational Design",
   "Conversational Design ist die Kunst, gute Gespraeche fuer Bots zu entwerfen: klare Fragen, kurze Antworten, natuerlicher Ablauf.",
   ["Gute Bot-Dialoge planen",
    "Klar, kurz, freundlich",
    "Nutzer fuehren, nicht verwirren",
    "Fehlerfaelle mitdenken"],
   "conversational design chatbot deutsch"),
 T("Genesys Predictive Routing",
   "Predictive Routing nutzt KI, um Anrufe an den Agent zu leiten, der sie am besten loesen kann - auf Basis frueherer Daten.",
   ["KI-gestuetztes Routing",
    "Kunde -> bester passender Agent",
    "Lernt aus frueheren Gespraechen",
    "Bessere Loesungsquote"],
   "Genesys predictive routing", (G_HELP + "articles/about-predictive-routing/", None)),
 T("Genesys Journey Management",
   "Journey Management schaut auf die gesamte Kundenreise ueber alle Kanaele - so versteht man, was der Kunde vorher schon getan hat.",
   ["Gesamte Kundenreise im Blick",
    "Ueber alle Kanaele hinweg",
    "Kontext fuer besseren Service",
    "Proaktiv helfen"],
   "Genesys journey management", (G_HELP + "articles/", None)),
 T("Speech & Text Analytics",
   "Speech & Text Analytics wertet Gespraeche automatisch aus: erkennt Themen, Stimmung und Stichworte - fuer Qualitaet und Verbesserung.",
   ["Gespraeche automatisch auswerten",
    "Themen und Stimmung erkennen",
    "Qualitaet und Trends sehen",
    "Basis fuer Verbesserungen"],
   "Genesys speech text analytics", (G_HELP + "articles/about-speech-and-text-analytics/", None)),
 T("Bias & Fairness",
   "Bias heisst Verzerrung: KI kann unfair sein, wenn ihre Trainingsdaten einseitig waren. Fairness heisst, das zu erkennen und zu vermeiden.",
   ["Bias = unfaire Verzerrung der KI",
    "Ursache: einseitige Daten",
    "Kann Kunden benachteiligen",
    "Pruefen und gegensteuern"],
   "AI bias fairness erklaert deutsch",
   art=[("Fraunhofer: Faire KI", "https://www.iis.fraunhofer.de/de/ff/ki.html")]),
 T("Explainability (Erklaerbarkeit)",
   "Explainability heisst, dass man nachvollziehen kann, warum die KI so entschieden hat - wichtig fuer Vertrauen und Aufsicht.",
   ["Warum hat die KI so entschieden?",
    "Nachvollziehbar machen",
    "Wichtig fuer Aufsicht/Kunde",
    "Teil des EU AI Act"],
   "explainable AI erklaert deutsch",
   art=[("EU AI Act: Transparenz", EU_ACT)]),
 T("Mehrsprachigkeit & Lokalisierung",
   "Mehrsprachigkeit heisst, dass der Bot mehrere Sprachen kann. Lokalisierung heisst, ihn passend fuer Land/Kultur anzupassen.",
   ["Bot in mehreren Sprachen",
    "Anpassung an Land/Kultur",
    "Wichtig fuer diverse Kunden",
    "Pro Sprache testen"],
   "multilingual chatbot design"),
 T("KI-Adoption & Change Management",
   "Damit KI wirklich hilft, muessen die Mitarbeiter sie annehmen. Change Management begleitet sie mit Schulung und Kommunikation.",
   ["Mitarbeiter mitnehmen",
    "Schulung und klare Kommunikation",
    "Aengste ernst nehmen",
    "Erfolge zeigen"],
   "KI Change Management Mitarbeiter",
   art=[("McKinsey: KI-Transformation", "https://www.mckinsey.com/de/publikationen")]),
 T("Nachhaltige KI (Green AI)",
   "Green AI heisst, den Energie- und Ressourcenverbrauch von KI im Blick zu behalten und moeglichst sparsam zu sein.",
   ["KI verbraucht Energie",
    "Sparsam waehlen (kleinere Modelle)",
    "Nur rechnen, was noetig ist",
    "Teil verantwortungsvoller KI"],
   "green AI nachhaltigkeit"),
])

# ---------------------------------------------------------------------------
# Nummerierung (globale Lern-Reihenfolge) hinzufuegen und JS schreiben
# ---------------------------------------------------------------------------
order = 1
total = 0
for m in MODULES:
    for tp in m["topics"]:
        tp["nr"] = order
        order += 1
        total += 1

data = {
    "updated": datetime.date.today().isoformat(),
    "total": total,
    "modules": MODULES,
}

out_dir = os.path.join(os.path.dirname(__file__), "..", "app", "data")
out_path = os.path.abspath(os.path.join(out_dir, "curriculum.js"))
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Automatisch erzeugt von scripts/build_curriculum.py - nicht direkt bearbeiten.\n")
    f.write("window.CURRICULUM = ")
    json.dump(data, f, ensure_ascii=False, indent=1)
    f.write(";\n")

print("Themen gesamt:", total)
print("Module:", len(MODULES))
print("Geschrieben:", out_path)
